import { canonicalJsonHash, canonicalJsonStringify } from '../domain/hash.js';

export class MemoryRepository {
  constructor({requireLease=false,now=Date.now}={}){this.requireLease=requireLease;this.now=now;this.raw=[];this.bars=[];this.provisional=[];this.facts={funding_rates:[],open_interest:[],long_short_ratios:[],taker_flow:[]};this.revisions=[];this.gaps=[];this.backfills=[];this.health=[];this.audits=[];this.runs=[];this.attempts=[];this.featureRecords=[];this.featureQuality=[];this.featureRuns=[];this.leases=new Map();this.connected=true;this.migrationsReady=true;}
  leaseOk(lease){if(!this.requireLease)return true;const current=this.leases.get(lease?.leaseName);if(!current||current.holderId!==lease.holderId||current.fencingToken!==lease.fencingToken||current.expiresAt<=this.now())throw Object.assign(new Error('Stale fencing token'),{code:'FENCING_TOKEN_REJECTED'});return true;}
  async ping(){if(!this.connected)throw Object.assign(new Error('db unavailable'),{code:'DATABASE_UNAVAILABLE'});return{ok:true,roundTripMs:0};}
  async migrationStatus(){return{ok:this.migrationsReady,versions:this.migrationsReady?['001','002','003']:[]};}
  async readinessSnapshot(){await this.ping();const latest_data_by_interval=Object.fromEntries(['15m','1h','4h'].map(interval=>[interval,Math.max(0,...this.bars.filter(x=>x.marketType==='spot'&&x.interval===interval).map(x=>x.closeTime))||null]));return{database:{ok:true},migrations:await this.migrationStatus(),bar_count:this.bars.length,unresolved_gap_count:this.gaps.filter(x=>x.status!=='RESOLVED').length,pending_backfill_count:this.backfills.filter(x=>['PENDING','RUNNING','RETRY_WAIT'].includes(x.status)).length,latest_data_ms:latest_data_by_interval['15m'],latest_data_by_interval};}
  async saveRaw(response,meta,lease){this.leaseOk(lease);const payload=canonicalJsonStringify(response.body),headers=canonicalJsonStringify(response.headers??{}),hash=canonicalJsonHash(response.body);if(meta.contentHash&&meta.contentHash!==hash)throw Object.assign(new Error('hash mismatch'),{code:'RAW_CONTENT_HASH_MISMATCH'});const key=`${response.requestId}:${hash}`,found=this.raw.find(x=>x.key===key);if(found)return found.rawPayloadId;const row=Object.freeze({key,rawPayloadId:meta.rawPayloadId||`raw-${this.raw.length+1}`,payload:JSON.parse(payload),headers:JSON.parse(headers),contentHash:hash,...meta});this.raw.push(row);return row.rawPayloadId;}
  async saveProvisionalBars(rows,lease){this.leaseOk(lease);let inserted=0;for(const row of rows){const key=`${row.sourceId}:${row.marketType}:${row.instrument}:${row.interval}:${row.openTime}:${row.contentHash}`;if(!this.provisional.some(x=>x.key===key)){this.provisional.push({key,...structuredClone(row)});inserted++;}}return{inserted,deduped:rows.length-inserted};}
  async upsertMarketBars(rows,lease){this.leaseOk(lease);const s={INSERTED:0,DEDUPED:0,REVISED:0,REJECTED:0};for(const row of rows){if(!row.vintageId||!row.contentHash||![row.publishedAt,row.availableAt,row.firstAvailableAt,row.fetchedAt].every(Number.isFinite)||row.publishedAt>row.availableAt||row.availableAt>row.firstAvailableAt||row.firstAvailableAt>row.fetchedAt){s.REJECTED++;continue;}const natural=`${row.sourceId}:${row.marketType}:${row.instrument}:${row.interval}:${row.openTime}`;const versions=this.bars.filter(x=>x.natural===natural).sort((a,b)=>b.revisionNumber-a.revisionNumber),previous=versions[0];if(previous?.contentHash===row.contentHash){s.DEDUPED++;continue;}const revision=previous?previous.revisionNumber+1:0,vintageId=String(row.vintageId).replace(/-rev\d+$/,`-rev${revision}`),next=Object.freeze({natural,...structuredClone(row),revisionNumber:revision,vintageId,firstAvailableAt:previous?.firstAvailableAt??row.firstAvailableAt,availableAt:row.availableAt});this.bars.push(next);if(previous)this.revisions.push({dataset:'market_bars',previousVintageId:previous.vintageId,newVintageId:vintageId});s[previous?'REVISED':'INSERTED']++;}return{inserted:s.INSERTED,revised:s.REVISED,deduped:s.DEDUPED,rejected:s.REJECTED,statuses:s};}
  async savePointFacts(table,rows,lease){this.leaseOk(lease);const s={INSERTED:0,DEDUPED:0,REVISED:0,REJECTED:0};for(const row of rows){if(!row.vintageId||!row.contentHash||![row.publishedAt,row.availableAt,row.firstAvailableAt,row.fetchedAt].every(Number.isFinite)||row.publishedAt>row.availableAt||row.availableAt>row.firstAvailableAt||row.firstAvailableAt>row.fetchedAt){s.REJECTED++;continue;}const natural=`${row.sourceId}:${row.instrument}:${row.interval||''}:${row.observedAt}`,versions=this.facts[table].filter(x=>x.natural===natural).sort((a,b)=>b.revisionNumber-a.revisionNumber),previous=versions[0];if(previous?.contentHash===row.contentHash){s.DEDUPED++;continue;}const revision=previous?previous.revisionNumber+1:0,vintageId=String(row.vintageId).replace(/:rev\d+$/,`:rev${revision}`),next=Object.freeze({natural,...structuredClone(row),revisionNumber:revision,vintageId,firstAvailableAt:previous?.firstAvailableAt??row.firstAvailableAt,availableAt:row.availableAt});this.facts[table].push(next);if(previous)this.revisions.push({dataset:table,previousVintageId:previous.vintageId,newVintageId:vintageId});s[previous?'REVISED':'INSERTED']++;}return{inserted:s.INSERTED,revised:s.REVISED,deduped:s.DEDUPED,rejected:s.REJECTED,statuses:s};}
  async saveGaps(rows,lease){this.leaseOk(lease);for(const row of rows){const key=row.gapId;if(!this.gaps.some(x=>x.gapId===key))this.gaps.push({...row,gapId:key});}return rows.map(x=>this.gaps.find(g=>g.gapId===x.gapId));}
  async createBackfill(gap,lease){this.leaseOk(lease);const id=`backfill:${gap.gapId||gap.gap_id}`;if(!this.backfills.some(x=>x.jobId===id))this.backfills.push({jobId:id,gapId:gap.gapId||gap.gap_id,gap:{...gap},status:'PENDING',attemptCount:0,maxAttempts:5,nextAttemptAt:this.now()});return this.backfills.find(x=>x.jobId===id);}
  async claimBackfill(workerId,lease){this.leaseOk(lease);const job=this.backfills.find(x=>['PENDING','RETRY_WAIT'].includes(x.status)&&(x.nextAttemptAt??0)<=this.now());if(!job)return null;Object.assign(job,{status:'RUNNING',workerId,attemptCount:job.attemptCount+1,fencingToken:lease?.fencingToken,startedAt:this.now()});return{...job};}
  async heartbeatBackfill(id,workerId,lease){this.leaseOk(lease);const job=this.backfills.find(x=>x.jobId===id&&x.workerId===workerId&&x.status==='RUNNING');if(job)job.lastHeartbeatAt=this.now();return job||null;}
  async finishBackfill(id,result,lease){this.leaseOk(lease);const job=this.backfills.find(x=>x.jobId===id);if(!job)return null;job.status=result.ok?'SUCCEEDED':result.retryable?'RETRY_WAIT':'FAILED_PERMANENT';job.nextAttemptAt=job.status==='RETRY_WAIT'?this.now()+result.delayMs:null;return job;}
  async resolveGap(id,lease){this.leaseOk(lease);const gap=this.gaps.find(x=>x.gapId===id);if(gap)gap.status='RESOLVED';return gap||null;}
  async countWork(){return{unresolved:this.gaps.filter(x=>x.status!=='RESOLVED').length,pending:this.backfills.filter(x=>['PENDING','RUNNING','RETRY_WAIT'].includes(x.status)).length};}
  async acquireLease(name,holderId,ttlMs,now=this.now()){const old=this.leases.get(name);if(old&&old.expiresAt>now&&old.holderId!==holderId)return null;const row={leaseName:name,holderId,expiresAt:now+ttlMs,fencingToken:(old?.fencingToken||0)+1};this.leases.set(name,row);return{...row};}
  async heartbeatLease(name,holderId,token,ttlMs){const x=this.leases.get(name);if(!x||x.holderId!==holderId||x.fencingToken!==token||x.expiresAt<=this.now())return null;x.expiresAt=this.now()+ttlMs;return{...x};}
  async releaseLease(lease){const x=this.leases.get(lease?.leaseName);if(!x||x.holderId!==lease?.holderId||x.fencingToken!==lease?.fencingToken)return null;x.expiresAt=this.now();return{...x};}
  async startRun(run,lease){this.leaseOk(lease);this.runs.push({...run,status:'RUNNING'});}async finishRun(id,status,errorCode,lease){this.leaseOk(lease);Object.assign(this.runs.find(x=>x.runId===id)||{},{status,errorCode});}async saveAttempt(x,lease){this.leaseOk(lease);this.attempts.push({...x});}
  async saveHealth(x,lease){this.leaseOk(lease);this.health.push(structuredClone(x));}async audit(x,lease){this.leaseOk(lease);this.audits.push(structuredClone(x));}
  async loadFeatureInputs({targetBarCloseTime,asOfTime=targetBarCloseTime}){const bars=(instrument,marketType,interval)=>this.bars.filter(x=>x.instrument===instrument&&x.marketType===marketType&&x.interval===interval&&x.closeTime<=targetBarCloseTime&&x.availableAt<=asOfTime&&x.fetchedAt<=asOfTime).sort((a,b)=>a.closeTime-b.closeTime).slice(-80),facts=table=>this.facts[table].filter(x=>x.instrument==='ETHUSDT'&&x.observedAt<=targetBarCloseTime&&x.availableAt<=asOfTime&&x.fetchedAt<=asOfTime).sort((a,b)=>a.observedAt-b.observedAt).slice(-80);return{eth15:bars('ETHUSDT','spot','15m'),eth1h:bars('ETHUSDT','spot','1h'),eth4h:bars('ETHUSDT','spot','4h'),btc15:bars('BTCUSDT','spot','15m'),btc1h:bars('BTCUSDT','spot','1h'),btc4h:bars('BTCUSDT','spot','4h'),funding:facts('funding_rates'),openInterest:facts('open_interest'),longShort:facts('long_short_ratios'),takerFlow:facts('taker_flow'),sourceRevisionRefs:this.revisions.map(x=>structuredClone(x)),databaseAvailable:this.connected};}
  async loadHistoricalFeatureInputs({targetBarCloseTime,historicalAsOfTime,replayNowMs}){const bars=(instrument,interval)=>this.bars.filter(x=>x.instrument===instrument&&x.marketType==='spot'&&x.interval===interval&&x.closeTime<=targetBarCloseTime&&x.fetchedAt<=replayNowMs).sort((a,b)=>a.closeTime-b.closeTime).slice(-80).map(x=>({...structuredClone(x),publishedAt:x.closeTime,availableAt:x.closeTime,fetchedAt:x.closeTime,operationalAvailableAt:x.availableAt,operationalFetchedAt:x.fetchedAt,researchAvailabilityAt:x.closeTime,researchAvailabilityRuleVersion:'v1.4d-research-availability-1'})),facts=table=>this.facts[table].filter(x=>x.instrument==='ETHUSDT'&&x.observedAt<=targetBarCloseTime&&x.publishedAt<=historicalAsOfTime&&x.availableAt<=historicalAsOfTime&&x.fetchedAt<=historicalAsOfTime).sort((a,b)=>a.observedAt-b.observedAt).slice(-80);return{eth15:bars('ETHUSDT','15m'),eth1h:bars('ETHUSDT','1h'),eth4h:bars('ETHUSDT','4h'),btc15:bars('BTCUSDT','15m'),btc1h:[],btc4h:[],funding:facts('funding_rates'),openInterest:facts('open_interest'),longShort:facts('long_short_ratios'),takerFlow:facts('taker_flow'),sourceRevisionRefs:structuredClone(this.revisions),databaseAvailable:this.connected};}
  async verifyHistoricalFeatureDataset({datasetVersion,symbol,from,to}){return{datasetVersion,symbol,intervals:['15m','1h','4h'],dataFrom:from-100*14400000,dataTo:to,researchAvailabilityRuleVersion:'v1.4d-research-availability-1'};}
  async startHistoricalFeatureRun(run){this.featureRuns.push({...structuredClone(run),status:'RUNNING'});}
  async finishHistoricalFeatureRun(id,result){Object.assign(this.featureRuns.find(x=>x.runId===id),structuredClone(result));}
  async saveHistoricalFeatureRecord(record,{runId}){const previous=this.featureRecords.filter(x=>x.symbol===record.symbol&&x.targetInterval===record.targetInterval&&x.targetBarCloseTime===record.targetBarCloseTime&&x.featureSetVersion===record.featureSetVersion).sort((a,b)=>b.revisionNumber-a.revisionNumber)[0];if(previous){if(previous.contentHash===record.contentHash&&previous.algorithmVersion===record.algorithmVersion&&previous.sourceDatasetVersion===record.sourceDatasetVersion)return{status:'ALREADY_PRESENT',record:previous,featureRecordId:previous.featureRecordId,revisionNumber:previous.revisionNumber};throw Object.assign(new Error('Existing historical feature differs in content or version'),{code:'HISTORICAL_FEATURE_CONFLICT'});}const next=Object.freeze({...structuredClone(record),generationRunId:runId,revisionNumber:0,featureRecordId:this.featureRecords.length+1});this.featureRecords.push(next);this.featureQuality.push({featureId:next.featureId,qualityState:next.qualityState,reasons:next.degradedReasons});return{status:'INSERTED',record:next,featureRecordId:next.featureRecordId,revisionNumber:0};}
  async listFeatureTargets({symbol,targetInterval,from,to,resumeAfter=null}){return this.bars.filter(x=>x.instrument===symbol&&x.marketType==='spot'&&x.interval===targetInterval&&x.closeTime>=from&&x.closeTime<=to&&(!resumeAfter||x.closeTime>resumeAfter)).sort((a,b)=>a.closeTime-b.closeTime).map(x=>({closeTime:x.closeTime}));}
  async saveFeatureRecord(record,lease){this.leaseOk(lease);const versions=this.featureRecords.filter(x=>x.featureId===record.featureId).sort((a,b)=>b.revisionNumber-a.revisionNumber),previous=versions[0];if(previous?.contentHash===record.contentHash)return{status:'DEDUPED',record:previous,revisionNumber:previous.revisionNumber};const next=Object.freeze({...structuredClone(record),revisionNumber:previous?previous.revisionNumber+1:0,featureRecordId:this.featureRecords.length+1});this.featureRecords.push(next);this.featureQuality.push({featureId:next.featureId,qualityState:next.qualityState,reasons:next.degradedReasons});return{status:previous?'REVISED':'INSERTED',record:next,revisionNumber:next.revisionNumber};}
  async startFeatureRun(run,lease){this.leaseOk(lease);this.featureRuns.push({...run,status:'RUNNING'});}
  async finishFeatureRun(id,result,lease){this.leaseOk(lease);Object.assign(this.featureRuns.find(x=>x.runId===id),result);}
  async getFeatureById(id){return this.featureRecords.filter(x=>x.featureId===id).sort((a,b)=>b.revisionNumber-a.revisionNumber)[0]||null;}
  async listFeatures(q){return this.featureRecords.filter(x=>x.symbol===q.symbol&&x.targetInterval===q.targetInterval&&x.targetBarCloseTime>=q.from&&x.targetBarCloseTime<=q.to).slice(0,q.limit);}
  async listPendingFeatureTargets({symbol,targetInterval,asOfTime,featureSetVersion,limit=32}){const closes=[...new Set(this.bars.filter(x=>x.instrument===symbol&&x.marketType==='spot'&&x.interval===targetInterval&&x.closeTime<=asOfTime&&x.availableAt<=asOfTime&&x.fetchedAt<=asOfTime).map(x=>Number(x.closeTime)))].sort((a,b)=>b-a);return closes.filter(closeTime=>!this.featureRecords.some(x=>x.symbol===symbol&&x.targetInterval===targetInterval&&x.targetBarCloseTime===closeTime&&x.featureSetVersion===featureSetVersion)).slice(0,limit).sort((a,b)=>a-b).map(closeTime=>({closeTime}));}
  async getFeatureLineage(id){return (await this.getFeatureById(id))?.sourceVintageRefs||[];}
  async listFeatureQuality(id){return this.featureQuality.filter(x=>x.featureId===id);}
  async listFeatureIssues({symbol='ETHUSDT',limit=100}={}){return this.featureRecords.filter(x=>x.symbol===symbol&&(x.qualityState!=='HEALTHY'||x.missingFeatures?.length)).slice(0,limit).map(x=>({featureId:x.featureId,qualityState:x.qualityState,missingFeatures:x.missingFeatures,degradedReasons:x.degradedReasons,targetBarCloseTime:x.targetBarCloseTime}));}
  async listFeatureRuns(limit=100){return this.featureRuns.slice(-limit);}
  async cleanupHealthSnapshots({retentionDays=90,dryRun=false}={}){const cutoff=this.now()-retentionDays*86400000,old=this.health.filter(x=>(x.evaluatedAt||0)<cutoff);if(!dryRun)this.health=this.health.filter(x=>(x.evaluatedAt||0)>=cutoff);return{deleted:old.length};}
  async listBars(q){return this.bars.filter(x=>x.instrument===q.instrument&&x.marketType===q.marketType&&x.interval===q.interval&&x.openTime>=q.from&&x.openTime<=q.to).slice(0,q.limit);}async listSimple(table,q){return this.facts[table].filter(x=>x.instrument===q.instrument&&x.observedAt>=q.from&&x.observedAt<=q.to).slice(0,q.limit);}async listGaps(limit=100){return this.gaps.slice(-limit);}async listSources(){return [];}async latestHealth(){return this.health;}async close(){this.connected=false;}
}
