import { randomUUID } from 'node:crypto';
import { canonicalJsonHash, canonicalJsonStringify, sha256 } from '../domain/hash.js';
import { featureSetDefinition } from '../features/feature-version.js';

const FACT_SPECS = Object.freeze({
  funding_rates: { key: ['source_id','instrument','observation_time'], values: [['market_type',x=>x.marketType],['observation_time',x=>new Date(x.observedAt)],['funding_rate',x=>x.fundingRate],['mark_price',x=>x.markPrice]] },
  open_interest: { key: ['source_id','instrument','observation_time'], values: [['market_type',x=>x.marketType],['observation_time',x=>new Date(x.observedAt)],['open_interest',x=>x.openInterest]] },
  long_short_ratios: { key: ['source_id','instrument','interval_name','observation_time'], values: [['interval_name',x=>x.interval],['observation_time',x=>new Date(x.observedAt)],['long_short_ratio',x=>x.longShortRatio],['long_account',x=>x.longAccount],['short_account',x=>x.shortAccount]] },
  taker_flow: { key: ['source_id','instrument','interval_name','observation_time'], values: [['interval_name',x=>x.interval],['observation_time',x=>new Date(x.observedAt)],['buy_sell_ratio',x=>x.buySellRatio],['buy_volume',x=>x.buyVolume],['sell_volume',x=>x.sellVolume]] }
});
const COMMON = [['source_id',x=>x.sourceId],['endpoint_id',x=>x.endpointId],['instrument',x=>x.instrument],['published_at',x=>new Date(x.publishedAt)],['available_at',x=>new Date(x.availableAt)],['first_available_at',x=>new Date(x.firstAvailableAt)],['fetched_at',x=>new Date(x.fetchedAt)],['revision_number',x=>x.revisionNumber],['vintage_id',x=>x.vintageId],['raw_payload_id',x=>x.rawPayloadId],['request_id',x=>x.requestId],['schema_version',x=>x.schemaVersion],['quality_state',x=>x.qualityState],['content_hash',x=>x.contentHash]];

export async function createPgPool(config) {
  if (!config.databaseUrl) throw Object.assign(new Error('DATABASE_URL_REQUIRED'), { code: 'DATABASE_URL_REQUIRED' });
  const { Pool } = await import('pg');
  return new Pool({ connectionString: config.databaseUrl, ssl: config.dbSsl ? { rejectUnauthorized: true } : false, max: 10, idleTimeoutMillis: 30_000 });
}

function leaseValues(lease) {
  if (!lease || !lease.leaseName || !lease.holderId || !Number.isSafeInteger(Number(lease.fencingToken))) throw Object.assign(new Error('Collector lease context required'), { code: 'LEASE_CONTEXT_REQUIRED' });
  return [lease.leaseName, lease.holderId, Number(lease.fencingToken)];
}
async function assertLease(client, lease) {
  const values=leaseValues(lease);
  const result=await client.query(`SELECT fencing_token FROM collector_leases WHERE lease_name=$1 AND holder_id=$2 AND fencing_token=$3 AND expires_at>clock_timestamp() FOR SHARE`,values);
  if(!result.rowCount)throw Object.assign(new Error('Stale or expired collector fencing token'),{code:'FENCING_TOKEN_REJECTED'});
}
const ms = value => value instanceof Date ? value.getTime() : new Date(value).getTime();
const revisionVintage = (base, revision) => String(base).replace(/:rev\d+$|-rev\d+$/, match => match.startsWith(':') ? `:rev${revision}` : `-rev${revision}`);
const validTimeOrder = fact => [fact.publishedAt,fact.availableAt,fact.firstAvailableAt,fact.fetchedAt].every(Number.isFinite) && fact.publishedAt<=fact.availableAt && fact.availableAt<=fact.firstAvailableAt && fact.firstAvailableAt<=fact.fetchedAt;
const validIdentity = fact => typeof fact.contentHash==='string'&&/^[a-f0-9]{64}$/.test(fact.contentHash)&&typeof fact.vintageId==='string'&&fact.vintageId.length>0;
const validBar = bar => validTimeOrder(bar)&&validIdentity(bar)&&Number.isSafeInteger(bar.openTime)&&Number.isSafeInteger(bar.closeTime)&&bar.openTime<bar.closeTime&&[bar.open,bar.high,bar.low,bar.close,bar.volume,bar.quoteVolume].every(value=>Number.isFinite(Number(value)))&&Number(bar.high)>=Math.max(Number(bar.open),Number(bar.close),Number(bar.low))&&Number(bar.low)<=Math.min(Number(bar.open),Number(bar.close),Number(bar.high))&&Number(bar.volume)>=0&&Number(bar.quoteVolume)>=0;
const MARKET_BAR_COLUMNS = Object.freeze([
  'source_id','endpoint_id','instrument','market_type','interval_name','open_time','close_time',
  'open','high','low','close','volume','quote_volume','trade_count','taker_buy_base_volume','taker_buy_quote_volume',
  'observation_start','observation_end','published_at','available_at','first_available_at','fetched_at',
  'revision_number','vintage_id','raw_payload_id','request_id','schema_version','normalizer_version','quality_state','content_hash'
]);
const marketBarValues = (bar,{availableAt,firstAvailableAt,revisionNumber,vintageId}) => [
  bar.sourceId,bar.endpointId,bar.instrument,bar.marketType,bar.interval,new Date(bar.openTime),new Date(bar.closeTime),
  bar.open,bar.high,bar.low,bar.close,bar.volume,bar.quoteVolume,bar.tradeCount,bar.takerBuyBaseVolume,bar.takerBuyQuoteVolume,
  new Date(bar.openTime),new Date(bar.closeTime),new Date(bar.closeTime),new Date(availableAt),new Date(firstAvailableAt),new Date(bar.fetchedAt),
  revisionNumber,vintageId,bar.rawPayloadId,bar.requestId,bar.schemaVersion,bar.normalizerVersion,bar.qualityState,bar.contentHash
];
const positionalValues = length => Array.from({length},(_,index)=>`$${index+1}`).join(',');

export class PostgresRepository {
  constructor(pool) { this.pool = pool; }
  async transaction(work, lease) {
    const client = await this.pool.connect();
    try { await client.query('BEGIN'); await assertLease(client,lease); const result=await work(client); await assertLease(client,lease); await client.query('COMMIT'); return result; }
    catch(error){await client.query('ROLLBACK');throw error;} finally{client.release();}
  }
  async ping(){const started=Date.now();const result=await this.pool.query('SELECT 1 AS ok');return{ok:result.rows[0]?.ok===1,roundTripMs:Date.now()-started};}
  async migrationStatus(){const result=await this.pool.query("SELECT version FROM schema_migrations WHERE version IN ('001','002','003') ORDER BY version");return{ok:result.rows.length===3,versions:result.rows.map(x=>x.version)};}
  async readinessSnapshot(){const [db,migrations,counts]=await Promise.all([this.ping(),this.migrationStatus(),this.pool.query(`SELECT (SELECT count(*)::int FROM market_bars) bar_count,(SELECT count(*)::int FROM data_gaps WHERE status<>'RESOLVED') unresolved_gap_count,(SELECT count(*)::int FROM backfill_jobs WHERE status IN ('PENDING','RUNNING','RETRY_WAIT')) pending_backfill_count,(SELECT extract(epoch from max(close_time))*1000 FROM market_bars) latest_data_ms,(SELECT jsonb_object_agg(interval_name,latest_ms) FROM (SELECT interval_name,extract(epoch from max(close_time))*1000 latest_ms FROM market_bars WHERE market_type='spot' GROUP BY interval_name) x) latest_data_by_interval`)]);return{database:db,migrations,...counts.rows[0]};}
  async acquireLease(name,holderId,ttlMs){const result=await this.pool.query(`INSERT INTO collector_leases(lease_name,holder_id,acquired_at,heartbeat_at,expires_at,fencing_token) VALUES($1,$2,clock_timestamp(),clock_timestamp(),clock_timestamp()+($3||' milliseconds')::interval,1) ON CONFLICT(lease_name) DO UPDATE SET holder_id=EXCLUDED.holder_id,acquired_at=clock_timestamp(),heartbeat_at=clock_timestamp(),expires_at=EXCLUDED.expires_at,fencing_token=collector_leases.fencing_token+1 WHERE collector_leases.expires_at<=clock_timestamp() OR collector_leases.holder_id=EXCLUDED.holder_id RETURNING lease_name AS "leaseName",holder_id AS "holderId",fencing_token::bigint AS "fencingToken",expires_at AS "expiresAt"`,[name,holderId,ttlMs]);return result.rows[0]||null;}
  async heartbeatLease(name,holderId,token,ttlMs){const result=await this.pool.query(`UPDATE collector_leases SET heartbeat_at=clock_timestamp(),expires_at=clock_timestamp()+($4||' milliseconds')::interval WHERE lease_name=$1 AND holder_id=$2 AND fencing_token=$3 AND expires_at>clock_timestamp() RETURNING lease_name AS "leaseName",holder_id AS "holderId",fencing_token::bigint AS "fencingToken",expires_at AS "expiresAt"`,[name,holderId,token,ttlMs]);return result.rows[0]||null;}
  async releaseLease(lease){if(!lease)return null;const result=await this.pool.query(`UPDATE collector_leases SET expires_at=clock_timestamp(),heartbeat_at=clock_timestamp() WHERE lease_name=$1 AND holder_id=$2 AND fencing_token=$3 RETURNING lease_name AS "leaseName",holder_id AS "holderId",fencing_token::bigint AS "fencingToken",expires_at AS "expiresAt"`,[lease.leaseName,lease.holderId,lease.fencingToken]);return result.rows[0]||null;}
  async saveRaw(response,meta,lease){
    let headersJson,payloadJson;try{headersJson=canonicalJsonStringify(response.headers??{});payloadJson=canonicalJsonStringify(response.body);}catch(error){throw Object.assign(new Error('Raw payload JSON serialization rejected'),{code:error.code||'RAW_JSON_UNSERIALIZABLE'});}
    const contentHash=canonicalJsonHash(response.body);if(meta.contentHash&&meta.contentHash!==contentHash)throw Object.assign(new Error('Raw content hash mismatch'),{code:'RAW_CONTENT_HASH_MISMATCH'});
    return this.transaction(async client=>{const id=meta.rawPayloadId||randomUUID();const result=await client.query(`INSERT INTO raw_payloads(raw_payload_id,request_id,source_id,endpoint_id,fetched_at,http_status,response_headers,payload,content_hash,schema_version,quality_state) VALUES($1,$2,$3,$4,to_timestamp($5/1000.0),$6,$7::jsonb,$8::jsonb,$9,$10,$11) ON CONFLICT(request_id,content_hash) DO NOTHING RETURNING raw_payload_id`,[id,response.requestId,meta.sourceId,meta.endpointId,response.receivedAt,response.status,headersJson,payloadJson,contentHash,meta.schemaVersion,meta.qualityState]);if(result.rowCount)return id;const existing=await client.query('SELECT raw_payload_id FROM raw_payloads WHERE request_id=$1 AND content_hash=$2',[response.requestId,contentHash]);return existing.rows[0].raw_payload_id;},lease);
  }
  async saveProvisionalBars(bars,lease){return this.transaction(async client=>{let inserted=0;for(const b of bars){const r=await client.query(`INSERT INTO provisional_market_bars(source_id,endpoint_id,instrument,market_type,interval_name,open_time,close_time,open,high,low,close,volume,quote_volume,fetched_at,raw_payload_id,content_hash,expires_at,request_id) VALUES($1,$2,$3,$4,$5,to_timestamp($6/1000.0),to_timestamp($7/1000.0),$8,$9,$10,$11,$12,$13,to_timestamp($14/1000.0),$15,$16,to_timestamp($7/1000.0)+interval '1 day',$17) ON CONFLICT(source_id,market_type,instrument,interval_name,open_time,content_hash) DO NOTHING`,[b.sourceId,b.endpointId,b.instrument,b.marketType,b.interval,b.openTime,b.closeTime,b.open,b.high,b.low,b.close,b.volume,b.quoteVolume,b.fetchedAt,b.rawPayloadId,b.contentHash,b.requestId]);inserted+=r.rowCount;}return{inserted,deduped:bars.length-inserted};},lease);}
  async upsertMarketBars(bars,lease){const summary={INSERTED:0,DEDUPED:0,REVISED:0,REJECTED:0};for(const bar of bars){const status=await this.saveMarketBar(bar,lease);summary[status]++;}return{inserted:summary.INSERTED,revised:summary.REVISED,deduped:summary.DEDUPED,rejected:summary.REJECTED,statuses:summary};}
  async saveMarketBar(bar,lease){if(!validBar(bar))return'REJECTED';return this.transaction(async client=>{
    const lockKey=`market_bars:${bar.sourceId}:${bar.marketType}:${bar.instrument}:${bar.interval}:${bar.openTime}`;await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[lockKey]);
    const previous=(await client.query(`SELECT * FROM market_bars WHERE source_id=$1 AND market_type=$2 AND instrument=$3 AND interval_name=$4 AND open_time=to_timestamp($5/1000.0) ORDER BY revision_number DESC LIMIT 1 FOR UPDATE`,[bar.sourceId,bar.marketType,bar.instrument,bar.interval,bar.openTime])).rows[0];
    if(previous?.content_hash===bar.contentHash)return'DEDUPED';const revision=previous?previous.revision_number+1:0;const first=previous?ms(previous.first_available_at):bar.firstAvailableAt;const available=bar.availableAt;const vintage=revisionVintage(bar.vintageId,revision);
    const values=marketBarValues(bar,{availableAt:available,firstAvailableAt:first,revisionNumber:revision,vintageId:vintage});
    const inserted=await client.query(`INSERT INTO market_bars(${MARKET_BAR_COLUMNS.join(',')}) VALUES(${positionalValues(values.length)}) RETURNING market_bar_id`,values);
    if(previous)await this.insertRevisionEvent(client,'market_bars',lockKey,previous.vintage_id,vintage,available,bar.fetchedAt,bar.contentHash);
    await client.query(`UPDATE provisional_market_bars SET promoted_market_bar_id=$1,promoted_at=clock_timestamp() WHERE source_id=$2 AND market_type=$3 AND instrument=$4 AND interval_name=$5 AND open_time=to_timestamp($6/1000.0) AND promoted_market_bar_id IS NULL`,[inserted.rows[0].market_bar_id,bar.sourceId,bar.marketType,bar.instrument,bar.interval,bar.openTime]);return previous?'REVISED':'INSERTED';
  },lease);}
  async savePointFacts(table,facts,lease){if(!FACT_SPECS[table])throw Object.assign(new Error('Invalid fact table'),{code:'INVALID_FACT_TABLE'});const summary={INSERTED:0,DEDUPED:0,REVISED:0,REJECTED:0};for(const fact of facts){summary[await this.savePointFact(table,fact,lease)]++;}return{inserted:summary.INSERTED,revised:summary.REVISED,deduped:summary.DEDUPED,rejected:summary.REJECTED,statuses:summary};}
  async savePointFact(table,fact,lease){const spec=FACT_SPECS[table];if(!validTimeOrder(fact)||!validIdentity(fact)||!Number.isSafeInteger(fact.observedAt))return'REJECTED';return this.transaction(async client=>{const keyValues={source_id:fact.sourceId,instrument:fact.instrument,interval_name:fact.interval,observation_time:new Date(fact.observedAt)};const lockKey=`${table}:${spec.key.map(k=>keyValues[k]).join(':')}`;await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[lockKey]);const where=spec.key.map((k,i)=>`${k}=$${i+1}`).join(' AND ');const previous=(await client.query(`SELECT * FROM ${table} WHERE ${where} ORDER BY revision_number DESC LIMIT 1 FOR UPDATE`,spec.key.map(k=>keyValues[k]))).rows[0];if(previous?.content_hash===fact.contentHash)return'DEDUPED';const revision=previous?previous.revision_number+1:0;const normalized={...fact,revisionNumber:revision,vintageId:revisionVintage(fact.vintageId,revision),firstAvailableAt:previous?ms(previous.first_available_at):fact.firstAvailableAt,availableAt:fact.availableAt};const columns=[...COMMON,...spec.values];const names=[...new Set(columns.map(x=>x[0]))];const valueByName=new Map(columns);const values=names.map(name=>valueByName.get(name)(normalized));await client.query(`INSERT INTO ${table}(${names.join(',')}) VALUES(${positionalValues(values.length)})`,values);if(previous)await this.insertRevisionEvent(client,table,lockKey,previous.vintage_id,normalized.vintageId,normalized.availableAt,normalized.fetchedAt,normalized.contentHash);return previous?'REVISED':'INSERTED';},lease);}
  async insertRevisionEvent(client,dataset,naturalKey,previousVintageId,newVintageId,availableAt,fetchedAt,contentHash){const id=`revision:${sha256({dataset,naturalKey,previousVintageId,newVintageId})}`;await client.query(`INSERT INTO data_revision_events(revision_event_id,dataset,natural_key,previous_vintage_id,new_vintage_id,detected_at,reason,content_hash,available_at,fetched_at) VALUES($1,$2,$3::jsonb,$4,$5,clock_timestamp(),'CONTENT_CHANGED',$6,to_timestamp($7/1000.0),to_timestamp($8/1000.0))`,[id,dataset,canonicalJsonStringify({key:naturalKey}),previousVintageId,newVintageId,contentHash,availableAt,fetchedAt]);}
  async saveGaps(rows,lease){return this.transaction(async client=>{const saved=[];for(const g of rows){const result=await client.query(`INSERT INTO data_gaps(gap_id,source_id,instrument,market_type,interval_name,start_open_time,end_open_time,missing_count,status,missing_reason,detected_at) VALUES($1,$2,$3,$4,$5,to_timestamp($6/1000.0),to_timestamp($7/1000.0),$8,'OPEN',$9,clock_timestamp()) ON CONFLICT(source_id,instrument,market_type,interval_name,start_open_time,end_open_time) DO UPDATE SET updated_at=clock_timestamp() RETURNING *`,[g.gapId,g.sourceId,g.instrument,g.marketType,g.interval,g.startOpenTime,g.endOpenTime,g.missingCount,g.missingReason||null]);saved.push(result.rows[0]);}return saved;},lease);}
  async createBackfill(gap,lease){return this.transaction(async client=>{const id=`backfill:${gap.gap_id||gap.gapId}`;return(await client.query(`INSERT INTO backfill_jobs(job_id,gap_id,status,next_attempt_at) VALUES($1,$2,'PENDING',clock_timestamp()) ON CONFLICT(job_id) DO NOTHING RETURNING *`,[id,gap.gap_id||gap.gapId])).rows[0]||null;},lease);}
  async claimBackfill(workerId,lease,staleMs=120000){return this.transaction(async client=>{await client.query(`UPDATE backfill_jobs SET status='RETRY_WAIT',next_attempt_at=clock_timestamp(),worker_id=NULL WHERE status='RUNNING' AND last_heartbeat_at<clock_timestamp()-($1||' milliseconds')::interval`,[staleMs]);return(await client.query(`WITH candidate AS (SELECT job_id FROM backfill_jobs WHERE status IN ('PENDING','RETRY_WAIT') AND COALESCE(next_attempt_at,clock_timestamp())<=clock_timestamp() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1), claimed AS (UPDATE backfill_jobs b SET status='RUNNING',worker_id=$1,lease_name=$2,fencing_token=$3,attempt_count=attempt_count+1,started_at=clock_timestamp(),last_heartbeat_at=clock_timestamp(),updated_at=clock_timestamp() FROM candidate WHERE b.job_id=candidate.job_id RETURNING b.*) SELECT c.*,g.source_id,g.instrument,g.market_type,g.interval_name,g.start_open_time,g.end_open_time,g.missing_count FROM claimed c JOIN data_gaps g ON g.gap_id=c.gap_id`,[workerId,lease.leaseName,lease.fencingToken])).rows[0]||null;},lease);}
  async heartbeatBackfill(jobId,workerId,lease){return this.transaction(async client=>(await client.query(`UPDATE backfill_jobs SET last_heartbeat_at=clock_timestamp(),updated_at=clock_timestamp() WHERE job_id=$1 AND worker_id=$2 AND status='RUNNING' AND fencing_token=$3 RETURNING job_id`,[jobId,workerId,lease.fencingToken])).rows[0]||null,lease);}
  async finishBackfill(jobId,{ok,retryable,errorCode,delayMs=1000},lease){return this.transaction(async client=>{const status=ok?'SUCCEEDED':retryable?'RETRY_WAIT':'FAILED_PERMANENT';return(await client.query(`UPDATE backfill_jobs SET status=$2,finished_at=CASE WHEN $2 IN ('SUCCEEDED','FAILED_PERMANENT') THEN clock_timestamp() ELSE NULL END,next_attempt_at=CASE WHEN $2='RETRY_WAIT' THEN clock_timestamp()+($3||' milliseconds')::interval ELSE NULL END,last_error_code=$4,updated_at=clock_timestamp() WHERE job_id=$1 AND fencing_token=$5 RETURNING *`,[jobId,status,delayMs,errorCode||null,lease.fencingToken])).rows[0]||null;},lease);}
  async resolveGap(id,lease){return this.transaction(async client=>(await client.query(`UPDATE data_gaps SET status='RESOLVED',resolved_at=clock_timestamp(),updated_at=clock_timestamp() WHERE gap_id=$1 RETURNING *`,[id])).rows[0]||null,lease);}
  async countWork(){return(await this.pool.query(`SELECT (SELECT count(*)::int FROM data_gaps WHERE status<>'RESOLVED') unresolved,(SELECT count(*)::int FROM backfill_jobs WHERE status IN ('PENDING','RUNNING','RETRY_WAIT')) pending`)).rows[0];}
  async startRun(run,lease){return this.transaction(async client=>{await client.query(`INSERT INTO collection_runs(run_id,collector_id,started_at,status,server_time,lease_name,fencing_token) VALUES($1,$2,to_timestamp($3/1000.0),'RUNNING',$4::jsonb,$5,$6)`,[run.runId,run.collectorId,run.startedAt,canonicalJsonStringify(run.serverTime||null),lease.leaseName,lease.fencingToken]);return run.runId;},lease);}
  async finishRun(runId,status,errorCode,lease){return this.transaction(async client=>{await client.query(`UPDATE collection_runs SET finished_at=clock_timestamp(),status=$2,error_code=$3 WHERE run_id=$1 AND fencing_token=$4`,[runId,status,errorCode||null,lease.fencingToken]);},lease);}
  async saveAttempt(attempt,lease){return this.transaction(async client=>{await client.query(`INSERT INTO collection_attempts(run_id,request_id,source_id,endpoint_id,instrument,market_type,interval_name,attempt_number,started_at,finished_at,http_status,round_trip_ms,rate_limited,success,error_code,error_detail,fencing_token) VALUES($1,$2,$3,$4,$5,$6,$7,$8,to_timestamp($9/1000.0),to_timestamp($10/1000.0),$11,$12,$13,$14,$15,$16,$17)`,[attempt.runId,attempt.requestId,attempt.sourceId,attempt.endpointId,attempt.instrument,attempt.marketType,attempt.interval,attempt.attemptNumber||1,attempt.startedAt,attempt.finishedAt,attempt.httpStatus,attempt.roundTripMs,attempt.rateLimited||false,attempt.success,attempt.errorCode||null,attempt.errorDetail?.slice(0,300)||null,lease.fencingToken]);},lease);}
  async saveHealth(snapshot,lease){return this.transaction(async client=>{await client.query(`INSERT INTO data_health_snapshots(source_id,endpoint_id,dataset_key,health_state,latest_attempt_at,latest_success_at,latest_data_at,data_age_ms,expected_frequency_ms,missing_count,duplicate_count,anomaly_count,consecutive_failures,last_http_status,rate_limited,clock_offset_ms,pending_backfill_count,recovery_started_at,last_recovered_at,circuit_state,last_error_code,reasons,evaluated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22::jsonb,$23)`,[snapshot.sourceId||'collector',snapshot.endpointId||null,snapshot.datasetKey||'collector:overall',snapshot.state,snapshot.latestAttemptAt?new Date(snapshot.latestAttemptAt):null,snapshot.latestSuccessAt?new Date(snapshot.latestSuccessAt):null,(snapshot.latestDataAt||snapshot.latestDataObservationAt)?new Date(snapshot.latestDataAt||snapshot.latestDataObservationAt):null,snapshot.dataAgeMs??null,snapshot.expectedFrequencyMs??null,snapshot.missingCount||0,snapshot.duplicateCount||0,snapshot.anomalyCount||0,snapshot.consecutiveFailures||0,snapshot.lastHttpStatus||null,!!snapshot.rateLimited,snapshot.clockOffsetMs??null,snapshot.pendingBackfillCount||0,snapshot.recoveryStartedAt?new Date(snapshot.recoveryStartedAt):null,snapshot.lastRecoveredAt?new Date(snapshot.lastRecoveredAt):null,snapshot.circuitState||null,snapshot.lastErrorCode||null,canonicalJsonStringify(snapshot.reasons||[]),new Date(snapshot.evaluatedAt)]);},lease);}
  async audit(event,lease){return this.transaction(async client=>{await client.query(`INSERT INTO source_audit_events(audit_event_id,event_type,source_id,endpoint_id,request_id,severity,detail,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,to_timestamp($8/1000.0))`,[event.auditEventId||randomUUID(),event.eventType,event.sourceId||null,event.endpointId||null,event.requestId||null,event.severity||'INFO',canonicalJsonStringify(event.detail||{}),event.occurredAt||Date.now()]);},lease);}
  async listBars({instrument,marketType='spot',interval,from,to,limit}){return(await this.pool.query(`SELECT * FROM market_bars WHERE instrument=$1 AND market_type=$2 AND interval_name=$3 AND open_time>=to_timestamp($4/1000.0) AND open_time<=to_timestamp($5/1000.0) ORDER BY open_time LIMIT $6`,[instrument,marketType,interval,from,to,limit])).rows;}
  async listSimple(table,{instrument,from,to,limit}){const allowed={funding_rates:'observation_time',open_interest:'observation_time'};const time=allowed[table];if(!time)throw new Error('INVALID_TABLE');return(await this.pool.query(`SELECT * FROM ${table} WHERE instrument=$1 AND ${time}>=to_timestamp($2/1000.0) AND ${time}<=to_timestamp($3/1000.0) ORDER BY ${time} DESC LIMIT $4`,[instrument,from,to,limit])).rows;}
  async listGaps(limit=100){return(await this.pool.query('SELECT * FROM data_gaps ORDER BY detected_at DESC LIMIT $1',[limit])).rows;}
  async listSources(){return(await this.pool.query('SELECT * FROM source_registry ORDER BY source_id')).rows;}
  async latestHealth(){return(await this.pool.query('SELECT DISTINCT ON(dataset_key) * FROM data_health_snapshots ORDER BY dataset_key,evaluated_at DESC')).rows;}
  async loadFeatureInputs({targetBarCloseTime,asOfTime=targetBarCloseTime}){
    const barQuery=async(instrument,marketType,interval,limit=80)=>{const result=await this.pool.query(`SELECT DISTINCT ON(open_time) market_bar_id AS "marketBarId",source_id AS "sourceId",endpoint_id AS "endpointId",instrument,market_type AS "marketType",interval_name AS interval,extract(epoch from open_time)*1000 AS "openTime",extract(epoch from close_time)*1000 AS "closeTime",open::text,high::text,low::text,close::text,volume::text,quote_volume::text AS "quoteVolume",trade_count AS "tradeCount",taker_buy_base_volume::text AS "takerBuyBaseVolume",taker_buy_quote_volume::text AS "takerBuyQuoteVolume",extract(epoch from published_at)*1000 AS "publishedAt",extract(epoch from available_at)*1000 AS "availableAt",extract(epoch from first_available_at)*1000 AS "firstAvailableAt",extract(epoch from fetched_at)*1000 AS "fetchedAt",revision_number AS "revisionNumber",vintage_id AS "vintageId",raw_payload_id AS "rawPayloadId",content_hash AS "contentHash" FROM market_bars WHERE instrument=$1 AND market_type=$2 AND interval_name=$3 AND close_time<=to_timestamp($4/1000.0) AND available_at<=to_timestamp($5/1000.0) AND fetched_at<=to_timestamp($5/1000.0) ORDER BY open_time DESC,revision_number DESC LIMIT $6`,[instrument,marketType,interval,targetBarCloseTime,asOfTime,limit]);return result.rows.reverse();};
    const pointQuery=async(table,interval=null,limit=80)=>{const intervalClause=interval?' AND interval_name=$4':'';const values=interval?['ETHUSDT',targetBarCloseTime,asOfTime,interval,limit]:['ETHUSDT',targetBarCloseTime,asOfTime,limit],limitIndex=interval?5:4;const result=await this.pool.query(`SELECT DISTINCT ON(observation_time) id,source_id AS "sourceId",endpoint_id AS "endpointId",instrument,${interval?'interval_name AS interval,':'NULL::text AS interval,'}extract(epoch from observation_time)*1000 AS "observedAt",extract(epoch from published_at)*1000 AS "publishedAt",extract(epoch from available_at)*1000 AS "availableAt",extract(epoch from first_available_at)*1000 AS "firstAvailableAt",extract(epoch from fetched_at)*1000 AS "fetchedAt",revision_number AS "revisionNumber",vintage_id AS "vintageId",raw_payload_id AS "rawPayloadId",content_hash AS "contentHash",to_jsonb(${table}) AS raw FROM ${table} WHERE instrument=$1 AND observation_time<=to_timestamp($2/1000.0) AND available_at<=to_timestamp($3/1000.0) AND fetched_at<=to_timestamp($3/1000.0)${intervalClause} ORDER BY observation_time DESC,revision_number DESC LIMIT $${limitIndex}` ,values);return result.rows.reverse().map(row=>({...row,fundingRate:row.raw.funding_rate,markPrice:row.raw.mark_price,openInterest:row.raw.open_interest,longShortRatio:row.raw.long_short_ratio,longAccount:row.raw.long_account,shortAccount:row.raw.short_account,buySellRatio:row.raw.buy_sell_ratio,buyVolume:row.raw.buy_volume,sellVolume:row.raw.sell_volume}));};
    const [eth15,eth1h,eth4h,btc15,btc1h,btc4h,funding,openInterest,longShort,takerFlow]=await Promise.all([barQuery('ETHUSDT','spot','15m'),barQuery('ETHUSDT','spot','1h'),barQuery('ETHUSDT','spot','4h'),barQuery('BTCUSDT','spot','15m'),barQuery('BTCUSDT','spot','1h'),barQuery('BTCUSDT','spot','4h'),pointQuery('funding_rates'),pointQuery('open_interest'),pointQuery('long_short_ratios','15m'),pointQuery('taker_flow','15m')]);
    const selected=[...eth15,...eth1h,...eth4h,...btc15,...btc1h,...btc4h,...funding,...openInterest,...longShort,...takerFlow],revised=selected.filter(x=>Number(x.revisionNumber)>0).map(x=>x.vintageId);let sourceRevisionRefs=[];
    if(revised.length)sourceRevisionRefs=(await this.pool.query(`SELECT revision_event_id AS "revisionEventId",dataset,previous_vintage_id AS "previousVintageId",new_vintage_id AS "vintageId",content_hash AS "contentHash",extract(epoch from detected_at)*1000 AS "detectedAt" FROM data_revision_events WHERE new_vintage_id=ANY($1::text[])`,[revised])).rows;
    return{eth15,eth1h,eth4h,btc15,btc1h,btc4h,funding,openInterest,longShort,takerFlow,sourceRevisionRefs,databaseAvailable:true};
  }
  async listFeatureTargets({symbol,targetInterval,from,to,resumeAfter=null}){return(await this.pool.query(`SELECT DISTINCT ON(close_time) extract(epoch from close_time)*1000 AS "closeTime" FROM market_bars WHERE instrument=$1 AND market_type='spot' AND interval_name=$2 AND close_time>=to_timestamp($3/1000.0) AND close_time<=to_timestamp($4/1000.0) AND ($5::bigint IS NULL OR extract(epoch from close_time)*1000>$5) ORDER BY close_time`,[symbol,targetInterval,from,to,resumeAfter])).rows;}
  async listPendingFeatureTargets({symbol,targetInterval,asOfTime,featureSetVersion,limit=32}){return(await this.pool.query(`SELECT extract(epoch from candidate.close_time)*1000 AS "closeTime" FROM (SELECT DISTINCT ON(b.close_time) b.close_time FROM market_bars b WHERE b.instrument=$1 AND b.market_type='spot' AND b.interval_name=$2 AND b.close_time<=to_timestamp($3/1000.0) AND b.available_at<=to_timestamp($3/1000.0) AND b.fetched_at<=to_timestamp($3/1000.0) AND NOT EXISTS (SELECT 1 FROM feature_records f WHERE f.symbol=$1 AND f.target_interval=$2 AND f.target_bar_close_time=b.close_time AND f.feature_set_version=$4) ORDER BY b.close_time DESC LIMIT $5) candidate ORDER BY candidate.close_time ASC`,[symbol,targetInterval,asOfTime,featureSetVersion,limit])).rows;}
  async ensureFeatureSet(client,record){const definition=canonicalJsonStringify(featureSetDefinition),hash=canonicalJsonHash(featureSetDefinition);const result=await client.query(`INSERT INTO feature_sets(feature_set_version,algorithm_version,schema_version,definition,definition_hash) VALUES($1,$2,$3,$4::jsonb,$5) ON CONFLICT(feature_set_version) DO UPDATE SET active=feature_sets.active WHERE feature_sets.definition_hash=EXCLUDED.definition_hash AND feature_sets.algorithm_version=EXCLUDED.algorithm_version RETURNING feature_set_version`,[record.featureSetVersion,record.algorithmVersion,featureSetDefinition.schemaVersion,definition,hash]);if(!result.rowCount)throw Object.assign(new Error('Feature set version content mismatch'),{code:'FEATURE_SET_VERSION_MISMATCH'});}
  async saveFeatureRecord(record,lease){return this.transaction(async client=>{
    await this.ensureFeatureSet(client,record);
    const lock=`feature:${record.symbol}:${record.targetInterval}:${record.targetBarCloseTime}:${record.featureSetVersion}`;
    await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[lock]);
    const previous=(await client.query(`SELECT * FROM feature_records WHERE symbol=$1 AND target_interval=$2 AND target_bar_close_time=to_timestamp($3/1000.0) AND feature_set_version=$4 ORDER BY revision_number DESC LIMIT 1 FOR UPDATE`,[record.symbol,record.targetInterval,record.targetBarCloseTime,record.featureSetVersion])).rows[0];
    if(previous?.content_hash===record.contentHash)return{status:'DEDUPED',featureRecordId:previous.feature_record_id,revisionNumber:previous.revision_number,record};
    const revision=previous?previous.revision_number+1:0;
    const values=[record.featureId,record.symbol,record.targetInterval,record.targetBarOpenTime,record.targetBarCloseTime,record.asOfTime,record.generatedAt,record.featureSetVersion,record.algorithmVersion,record.sourceDatasetVersion,revision,record.completeness,record.qualityState,canonicalJsonStringify(record.missingFeatures),canonicalJsonStringify(record.degradedReasons),canonicalJsonStringify(record.sourceVintageRefs),canonicalJsonStringify(record.sourceRevisionRefs),canonicalJsonStringify(record.features),canonicalJsonStringify(record.availability),record.contentHash];
    const inserted=await client.query(`INSERT INTO feature_records(feature_id,symbol,target_interval,target_bar_open_time,target_bar_close_time,as_of_time,generated_at,feature_set_version,algorithm_version,source_dataset_version,revision_number,completeness,quality_state,missing_features,degraded_reasons,source_vintage_refs,source_revision_refs,feature_values,availability,content_hash) VALUES($1,$2,$3,to_timestamp($4/1000.0),to_timestamp($5/1000.0),to_timestamp($6/1000.0),to_timestamp($7/1000.0),$8,$9,$10,$11,$12,$13,$14::jsonb,$15::jsonb,$16::jsonb,$17::jsonb,$18::jsonb,$19::jsonb,$20) RETURNING feature_record_id`,values);
    const id=inserted.rows[0].feature_record_id;
    for(const ref of record.sourceVintageRefs)await client.query(`INSERT INTO feature_source_refs(feature_record_id,dataset,source_name,symbol,interval_name,natural_key,source_revision,source_time,published_at,available_at,raw_payload_id,source_record_id,vintage_id,content_hash) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,to_timestamp($8/1000.0),to_timestamp($9/1000.0),to_timestamp($10/1000.0),$11,$12,$13,$14)`,[id,ref.dataset,ref.sourceName,ref.symbol,ref.interval,canonicalJsonStringify(ref.naturalKey),ref.revision,ref.sourceTime,ref.publishedAt,ref.availableAt,ref.rawPayloadId,ref.sourceRecordId,ref.vintageId,ref.contentHash]);
    const qualityHash=canonicalJsonHash({featureId:record.featureId,revision,qualityState:record.qualityState,reasons:record.degradedReasons});
    await client.query(`INSERT INTO feature_quality_events(feature_quality_event_id,feature_record_id,feature_id,quality_state,event_type,reasons,occurred_at,content_hash) VALUES($1,$2,$3,$4,$5,$6::jsonb,clock_timestamp(),$7)`,[`feature-quality:${qualityHash}`,id,record.featureId,record.qualityState,'FEATURE_GENERATED',canonicalJsonStringify(record.degradedReasons),qualityHash]);
    if(previous){const eventHash=canonicalJsonHash({featureId:record.featureId,previous:previous.content_hash,next:record.contentHash});await client.query(`INSERT INTO feature_revision_events(feature_revision_event_id,feature_id,previous_feature_record_id,new_feature_record_id,previous_content_hash,new_content_hash,detected_at) VALUES($1,$2,$3,$4,$5,$6,clock_timestamp())`,[`feature-revision:${eventHash}`,record.featureId,previous.feature_record_id,id,previous.content_hash,record.contentHash]);}
    return{status:previous?'REVISED':'INSERTED',featureRecordId:id,revisionNumber:revision,record};
  },lease);}
  async startFeatureRun(run,lease){return this.transaction(async client=>{await this.ensureFeatureSet(client,{featureSetVersion:run.featureSetVersion,algorithmVersion:featureSetDefinition.algorithmVersion});await client.query(`INSERT INTO feature_generation_runs(generation_run_id,feature_set_version,symbol,target_interval,range_start,range_end,status,dry_run,lease_name,fencing_token,started_at) VALUES($1,$2,$3,$4,to_timestamp($5/1000.0),to_timestamp($6/1000.0),'RUNNING',false,$7,$8,to_timestamp($9/1000.0))`,[run.runId,run.featureSetVersion,run.symbol,run.targetInterval,run.from,run.to,lease.leaseName,lease.fencingToken,run.startedAt]);},lease);}
  async finishFeatureRun(runId,result,lease){return this.transaction(async client=>{const count=status=>result.results.filter(x=>x.status===status).length;await client.query(`UPDATE feature_generation_runs SET status=$2,generated_count=$3,deduped_count=$4,revised_count=$5,blocked_count=$6,cursor_close_time=CASE WHEN $7::bigint IS NULL THEN NULL ELSE to_timestamp($7/1000.0) END,error_code=$8,finished_at=clock_timestamp() WHERE generation_run_id=$1`,[runId,result.status,count('INSERTED'),count('DEDUPED'),count('REVISED'),count('BLOCKED'),result.cursorCloseTime??null,result.errorCode||null]);},lease);}
  async getFeatureById(featureId){return(await this.pool.query(`SELECT * FROM feature_records WHERE feature_id=$1 ORDER BY revision_number DESC LIMIT 1`,[featureId])).rows[0]||null;}
  async listFeatures({symbol,targetInterval,from,to,limit}){return(await this.pool.query(`SELECT DISTINCT ON(target_bar_close_time) * FROM feature_records WHERE symbol=$1 AND target_interval=$2 AND target_bar_close_time BETWEEN to_timestamp($3/1000.0) AND to_timestamp($4/1000.0) ORDER BY target_bar_close_time DESC,revision_number DESC LIMIT $5`,[symbol,targetInterval,from,to,limit])).rows;}
  async getFeatureLineage(featureId){return(await this.pool.query(`SELECT r.* FROM feature_source_refs r JOIN feature_records f ON f.feature_record_id=r.feature_record_id WHERE f.feature_id=$1 ORDER BY r.source_time`,[featureId])).rows;}
  async listFeatureQuality(featureId){return(await this.pool.query(`SELECT * FROM feature_quality_events WHERE feature_id=$1 ORDER BY occurred_at DESC`,[featureId])).rows;}
  async listFeatureIssues({symbol='ETHUSDT',limit=100}={}){return(await this.pool.query(`SELECT feature_id,quality_state,missing_features,degraded_reasons,target_bar_close_time FROM feature_records WHERE symbol=$1 AND (quality_state<>'HEALTHY' OR jsonb_array_length(missing_features)>0) ORDER BY target_bar_close_time DESC LIMIT $2`,[symbol,limit])).rows;}
  async listFeatureRuns(limit=100){return(await this.pool.query(`SELECT * FROM feature_generation_runs ORDER BY started_at DESC LIMIT $1`,[limit])).rows;}
  async cleanupHealthSnapshots({retentionDays=90,dryRun=false}={}){if(!Number.isInteger(retentionDays)||retentionDays<1)throw new Error('INVALID_RETENTION_DAYS');const query=dryRun?`SELECT count(*)::int AS deleted FROM data_health_snapshots WHERE evaluated_at<clock_timestamp()-($1||' days')::interval`:`WITH deleted AS (DELETE FROM data_health_snapshots WHERE evaluated_at<clock_timestamp()-($1||' days')::interval RETURNING 1) SELECT count(*)::int AS deleted FROM deleted`;return(await this.pool.query(query,[retentionDays])).rows[0];}
  async close(){await this.pool.end();}
}
