'use strict';
const assert=require('node:assert/strict'),C=require('../v1-core.js');let passed=0,failed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name)}catch(e){failed++;console.error('FAIL '+name+': '+e.message)}}
const zone=(l,u)=>({lower:l,upper:u,center:(l+u)/2}),q={sufficientForEMA20:true};
function context(){const e15={price:100,confirmedPrice:99,atr14:4,state:'RANGE_CHOP',trend:'flat',isBreakout:false,isBreakdown:false,falseBreakoutTier:'none'},e1={state:'RANGE_CHOP',dataQuality:q},e4={htfState:'HTF_RANGE',dataQuality:q},b={trend:'flat'},vol={ratio:.8},zones={supportZones:[zone(88,90),zone(80,82)],resistanceZones:[zone(110,112),zone(120,122)]};return{e15,e1,e4,b,vol,zones};}
test('双向预案固定为尚未触发',()=>{const x=context(),l=C.buildTriggerPlan('long',x.e15,x.e1,x.e4,x.b,x.vol,'normal','none',x.zones),s=C.buildTriggerPlan('short',x.e15,x.e1,x.e4,x.b,x.vol,'normal','none',x.zones);assert.equal(l.triggered,false);assert.equal(s.triggered,false);assert.match(l.disclaimer,/不构成当前交易建议/);});
test('双向预案字段完整',()=>{const x=context(),p=C.buildTriggerPlan('long',x.e15,x.e1,x.e4,x.b,x.vol,'normal','none',x.zones);for(const k of ['triggerCondition','entryZone','closeConfirmation','btcCondition','volumeCondition','invalidation','targets','riskReward','missing'])assert.ok(k in p,k);assert.equal(p.targets.length,3);});
test('条件进度含九项检查',()=>{const x=context(),p=C.buildTriggerPlan('long',x.e15,x.e1,x.e4,x.b,x.vol,'normal','none',x.zones);assert.equal(p.checks.length,9);assert.match(p.summary,/还缺/);});
test('多空机会评分互相独立',()=>{const x=context(),l=C.buildTriggerPlan('long',{...x.e15,state:'BULL_CONFIRMATION',trend:'up',isBreakout:true}, {state:'BULL_CONFIRMATION',dataQuality:q},{htfState:'HTF_BULL_TREND',dataQuality:q},{trend:'up'}, {ratio:1.5},'normal','none',x.zones),s=C.buildTriggerPlan('short',x.e15,x.e1,x.e4,x.b,x.vol,'normal','none',x.zones),r=C.calcOpportunityScores(l,s,'normal',{level:'trend_entry_allowed'});assert.notEqual(r.long,r.short);});
test('硬性否决优先于高评分',()=>{const x=context(),p=C.buildTriggerPlan('long',{...x.e15,state:'BULL_CONFIRMATION',trend:'up',isBreakout:true},{state:'BULL_CONFIRMATION',dataQuality:q},{htfState:'HTF_BULL_TREND',dataQuality:q},{trend:'up'},{ratio:2},'invalid','confirmation_failed',x.zones),r=C.calcOpportunityScores(p,p,'invalid',{level:'blocked_by_data'});assert.equal(r.hardBlocked,true);assert.equal(r.tradability,0);});
test('位置距离与ATR距离',()=>{const m=C.calcPositionMetrics(100,zone(88,90),zone(110,112),5);assert.equal(m.supportDistanceUsd,10);assert.equal(m.resistanceDistanceUsd,10);assert.equal(m.supportDistanceAtr,2);assert.equal(m.rangePositionPct,50);});
test('进入支撑区明确标记',()=>assert.equal(C.calcPositionMetrics(89,zone(88,90),zone(110,112),5).message,'已进入第一支撑区'));
test('进入压力区明确标记',()=>assert.equal(C.calcPositionMetrics(111,zone(88,90),zone(110,112),5).message,'已进入第一压力区'));
test('15分钟倒计时起点边界',()=>{const x=C.getCountdown15m(1800000);assert.equal(x.remainingMs,900000);assert.equal(x.text,'15:00');});
test('15分钟倒计时末秒边界',()=>{const x=C.getCountdown15m(2699999);assert.equal(x.remainingMs,1);assert.equal(x.text,'00:00');});
test('图表只取最近50根且区域一致',()=>{const bars=Array.from({length:60},(_,i)=>({close:i,open:i,high:i+1,low:i-1})),z={supportZones:[zone(1,2)],resistanceZones:[zone(8,9)]},m=C.buildChartModel(bars,{price:7},z,{worthBetting:false});assert.equal(m.bars.length,50);assert.deepEqual(m.supportZones,z.supportZones);assert.equal(m.trade,null);});
test('有效方案才显示图表交易线',()=>{const m=C.buildChartModel([],{price:7},{supportZones:[],resistanceZones:[]},{worthBetting:true,entryZone:'1-2',stopLoss:1,targets:[2,3,4]});assert.ok(m.trade);});
test('风险预算与建议试仓金额',()=>{const r=C.calcRiskBudget(100,95,{capital:10000,maxRiskPct:.01,leverage:2,takerFeeRate:.0005,slippageRate:.0003,spreadRate:.0002});assert.equal(r.maxLossAmount,100);assert.ok(r.suggestedNotional>0);assert.equal(r.suggestedMargin,r.suggestedNotional/2);assert.equal(r.withinBudget,true);assert.ok(r.projectedAddOnRisk>r.maxLossAmount);assert.equal(r.addOnWithinBudget,false);});
class Store{constructor(){this.m={}}getItem(k){return this.m[k]??null}setItem(k,v){this.m[k]=String(v)}removeItem(k){delete this.m[k]}}
test('设置localStorage保存恢复',()=>{const s=new Store(),x={capital:20000,maxRiskPct:.02,leverage:2,takerFeeRate:.001,slippageRate:.0004,spreadRate:.0003};assert.equal(C.saveRiskSettings(s,x).ok,true);assert.equal(C.loadRiskSettings(s).capital,20000);});
test('日志JSON和CSV导出',()=>{const a=[{timestamp:1,source:'Binance',marketType:'现货',advice:'观察'}];assert.equal(JSON.parse(C.exportLogsJSON(a))[0].source,'Binance');const csv=C.exportLogsCSV(a);assert.match(csv,/timestamp,source/);assert.match(csv,/Binance/);});
test('清除日志必须确认',()=>{const s=new Store();s.setItem('ethAlphaDecisionLogsV11','x');assert.equal(C.clearDecisionLogs(s,()=>false),false);assert.equal(s.getItem('ethAlphaDecisionLogsV11'),'x');assert.equal(C.clearDecisionLogs(s,()=>true),true);assert.equal(s.getItem('ethAlphaDecisionLogsV11'),null);});
test('未收盘K线仍不能改变正式状态',()=>{const MS=C.TF_MS['15m'],base=1700000000000,k=Array.from({length:40},(_,i)=>({openTime:base+i*MS,open:100,high:i===30?110:105,low:95,close:100,volume:100,takerBuyVolume:50,closeTime:base+(i+1)*MS-1,isClosed:true}));k.push({openTime:base+40*MS,open:100,high:120,low:99,close:115,volume:300,takerBuyVolume:200,closeTime:base+41*MS-1,isClosed:false});const e=C.analyzeKlines(k,'15m');assert.equal(e.isBreakout,false);assert.match(e.intrabarWarning,/盘中/);});
console.log(`RESULT passed=${passed} failed=${failed}`);if(failed)process.exitCode=1;
