'use strict';
const assert=require('node:assert/strict'),S=require('../v1_4-storage-core.js'),C=require('../v1-core.js');
let passed=0,failed=0;
function test(name,fn){return Promise.resolve().then(fn).then(()=>{passed++;console.log('PASS '+name)},e=>{failed++;console.error('FAIL '+name+': '+e.stack)})}
class Storage{constructor(seed={}){this.m=new Map(Object.entries(seed))}get length(){return this.m.size}key(i){return[...this.m.keys()][i]??null}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
const EXACT='SIG-1784362500000-ranging-raft4final';
const snapshot=i=>({schemaVersion:'v1.4-forecastsnapshot-1',predictionId:`GMKG-${i}`,instrument:'ETH',horizon:i%2?'24h':'72h',generatedAt:1784300000000+i,algorithmVersion:'raft4final',weightVersion:'w1',datasetVersion:'d1',payload:'x'.repeat(1000)});
const signal=(i,origin='local')=>({schemaVersion:'v1.3-signal-3',signalId:i===0?EXACT:`SIG-${i}`,signalFingerprint:`FP-${i}`,symbol:'ETHUSDT',direction:i%3===0?'ranging':'long',archiveCategory:origin==='local'?'OBSERVATION':'WATCHLIST',eligibleForTrigger:false,generatedAt:1784362500000+i,sourceConfirmedBarTime:1784362500000+i,entryZone:{lower:1841,upper:1846.63,estimatedEntry:1843.815,valid:true},origin});
const shadow=(i,origin='local')=>({schemaVersion:'v1.3-signal-3',signalId:i===0?EXACT:`SIG-${i}`,lifecycleStatus:origin==='local'?'OBSERVING':'STOPPED',verified:origin!=='local',baselinePrice:1845,entryFillPrice:origin==='local'?null:1843.815,exitPrice:origin==='local'?null:1835,grossR:origin==='local'?null:-1,lastProcessedBarOpenTime:1784362500000+i,origin});
const diagnostic=i=>({schemaVersion:'v1.3.1-trade-gate-1',diagnosticKey:`ETHUSDT|${i}`,evaluatedAt:i,sourceConfirmedBarTime:i,finalConclusion:'观察'});
function seed(){return new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify(Array.from({length:52},(_,i)=>snapshot(i))),ethAlphaSignalArchive:JSON.stringify(Array.from({length:100},(_,i)=>signal(i))),ethAlphaSignalEvents:'[]',ethAlphaShadowResults:JSON.stringify(Array.from({length:100},(_,i)=>shadow(i))),ethAlphaTradeGateDiagnostics:JSON.stringify({schemaVersion:'v1.3.1-trade-gate-1',stats:{totalEvaluations:25},records:Array.from({length:25},(_,i)=>diagnostic(i))}),ethAlphaPaperAccount:JSON.stringify({cash:500,equity:510,marginUsed:20}),ethAlphaPaperTrades:JSON.stringify([{tradeId:'OPEN-1',status:'OPEN',quantity:.01}])})}
function repo(storage,adapter){return S.createRepository({localStorage:storage,adapter,navigatorStorage:{estimate:async()=>({usage:1,quota:10_000_000})},entryZoneNormalizer:C.normalizeEntryZone})}
async function prepopulate(r){for(let i=0;i<100;i++){await r.putImmutable('signalArchive',signal(i,'indexeddb'));await r.putProjection('shadowResults',shadow(i,'indexeddb'))}await r.putImmutable('snapshots',{...snapshot(999),predictionId:'RUNTIME-NEW'})}
async function sourceCovered(r,name,records){for(const record of records){const id=S.recordId(name,record),d=await r.inspectMigrationRecord(name,id),wanted=S.stableHash(S.canonicalStringify(S.canonicalizeForCompare(name,record,{entryZoneNormalizer:C.normalizeEntryZone}))),formalMatch=d.canonical.formalHash===wanted,conflictMatch=d.migrationConflicts.some(x=>x.datasetName===name&&x.originalId===id&&x.contentHash===wanted);assert.ok(formalMatch||conflictMatch,`${name}:${id}未在正式记录或dataset隔离冲突中验证`)}}
(async()=>{
await test('精确ID对象级差异诊断同时导出localStorage、IndexedDB与dataset冲突',async()=>{const s=seed(),a=new S.MemoryAdapter(),r=repo(s,a);await r.open();await prepopulate(r);const m=await r.migrateLegacy();assert.equal(m.state,'VERIFIED_WITH_CONFLICTS');const d=await r.inspectMigrationRecord('shadowResults',EXACT);assert.equal(d.localStorageRecord.origin,'local');assert.equal(d.indexedDbRecord.origin,'indexeddb');assert.ok(d.canonical.differencePaths.includes('lifecycleStatus'));assert.ok(d.migrationConflicts.some(x=>x.datasetName==='shadowResults'&&x.originalId===EXACT&&x.record.origin==='local'));const exported=JSON.parse(await r.exportMigrationConflictDiagnostic('shadowResults',EXACT));assert.deepEqual(exported.localStorageRecord,d.localStorageRecord);assert.deepEqual(exported.indexedDbRecord,d.indexedDbRecord)});
await test('冲突ID包含dataset、schema和内容哈希且跨dataset不碰撞',async()=>{const canon=S.canonicalStringify({signalId:EXACT,value:1}),a=S.conflictIdentity('signalArchive',EXACT,canon),b=S.conflictIdentity('shadowResults',EXACT,canon);assert.notEqual(a.conflictId,b.conflictId);assert.match(a.conflictId,/v1\.4-migrationconflict-2__signalArchive__/);assert.match(b.conflictId,/v1\.4-migrationconflict-2__shadowResults__/)});
await test('真实规模大于100冲突仍完成、全部可验证、完整导出不截断',async()=>{const s=seed(),a=new S.MemoryAdapter(),r=repo(s,a);await r.open();await prepopulate(r);const account=s.getItem('ethAlphaPaperAccount'),trades=s.getItem('ethAlphaPaperTrades'),m=await r.migrateLegacy();assert.equal(m.state,'VERIFIED_WITH_CONFLICTS');assert.ok(m.totalConflictCount>=200);assert.equal(m.displayedConflictCount,100);assert.equal((await r.getConflicts()).length,m.totalConflictCount);assert.equal(JSON.parse(await r.exportConflicts()).conflicts.length,m.totalConflictCount);await sourceCovered(r,'signalArchive',Array.from({length:100},(_,i)=>signal(i)));await sourceCovered(r,'shadowResults',Array.from({length:100},(_,i)=>shadow(i)));assert.equal((await r.get('snapshots','RUNTIME-NEW')).predictionId,'RUNTIME-NEW');assert.equal(s.getItem('ethAlphaPaperAccount'),account);assert.equal(s.getItem('ethAlphaPaperTrades'),trades);assert.equal(s.getItem('ethAlphaGmkgForecastSnapshots'),null)});
await test('FAILED多次重试复用确定性冲突、不产生副本，成功后刷新保持成功',async()=>{const s=seed(),a=new S.MemoryAdapter(),r0=repo(s,a);await r0.open();await prepopulate(r0);a.interruptAfter=a.writes+80;const first=await r0.migrateLegacy();assert.equal(first.state,'FAILED');assert.ok(s.getItem('ethAlphaGmkgForecastSnapshots'));const count1=(await r0.getConflicts()).length;a.interruptAfter=null;await r0.putImmutable('snapshots',{...snapshot(1001),predictionId:'RUNTIME-DURING-MIGRATION'});a.interruptAfter=a.writes+60;const r1=repo(s,a);await r1.open();const second=await r1.migrateLegacy();assert.equal(second.state,'FAILED');const count2=(await r1.getConflicts()).length;assert.ok(count2>=count1);a.interruptAfter=null;const r2=repo(s,a);await r2.open();const done=await r2.migrateLegacy();assert.equal(done.state,'VERIFIED_WITH_CONFLICTS');const count3=(await r2.getConflicts()).length;assert.equal((await r2.get('snapshots','RUNTIME-DURING-MIGRATION')).predictionId,'RUNTIME-DURING-MIGRATION');const r3=repo(s,a);await r3.open();const refreshed=await r3.migrateLegacy();assert.equal(refreshed.state,'VERIFIED_WITH_CONFLICTS');assert.equal(refreshed.resumedVerified,true);assert.equal((await r3.getConflicts()).length,count3);assert.equal(new Set((await r3.getConflicts()).map(x=>x.conflictId)).size,count3);assert.equal(s.getItem('ethAlphaPaperAccount'),JSON.stringify({cash:500,equity:510,marginUsed:20}))});
await test('shadowResults是日常可覆盖投影，但迁移旧版本只进审计且不进入交易许可',async()=>{const s=seed(),a=new S.MemoryAdapter(),r=repo(s,a);await r.open();await r.putProjection('shadowResults',shadow(0,'indexeddb'));await r.migrateLegacy();const current=await r.get('shadowResults',EXACT),old=(await r.getConflicts('shadowResults')).find(x=>x.originalId===EXACT);assert.equal(current.origin,'indexeddb');assert.equal(old.record.origin,'local');assert.equal(Object.hasOwn(old.record,'eligibleForTrigger'),false);assert.equal(Object.hasOwn(current,'eligibleForTrigger'),false)});
console.log(`RESULT passed=${passed} failed=${failed}`);if(failed)process.exitCode=1
})();
