'use strict';
const assert=require('node:assert/strict'),C=require('../v1-core.js'),P=require('../v1_3-paper-trading-core.js'),S=require('../v1_3-signal-archive-core.js'),D=require('../v1_3-trade-gate-diagnostics.js'),X=require('./v13-fixtures.js');
let passed=0,failed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name)}catch(e){failed++;console.error('FAIL '+name+': '+e.stack)}}
function structuredDecision(direction='long',lower=1841,upper=1846.63,entry=1845){const d=X.decision({biasDirection:direction,confirmedPrice:1845,price:1845}),base=d.triggerPlans[direction];d.triggerPlans[direction]={...base,entryZone:'展示文案可以任意变化',entryZoneValues:{lower,upper,estimatedEntry:entry},estimatedEntry:entry,invalidation:direction==='long'?1835:1855,targets:direction==='long'?[1855,1865,1875]:[1835,1825,1815]};d.stopLoss=d.triggerPlans[direction].invalidation;d.targets=d.triggerPlans[direction].targets;return d}
test('千位分隔符旧字符串解析为完整价格',()=>{const z=C.normalizeEntryZone({entryZone:'1,841.00 – 1,846.63',estimatedEntry:1845});assert.equal(z.valid,true);assert.deepEqual([z.lower,z.upper],[1841,1846.63]);assert.equal(z.source,'legacy_display_string')});
test('多头结构化入场区距离计算正确',()=>{const d=structuredDecision('long',1841,1843,1842),v=D.planView(d,'long'),r=D.distanceToZone(1845,v.entryZone,2);assert.equal(v.entryZone.source,'structured_values');assert.equal(r.usd,2);assert.equal(r.atr,1);assert.equal(r.inside,false)});
test('空头结构化入场区距离计算正确',()=>{const d=structuredDecision('short',1847,1849,1848),v=D.planView(d,'short'),r=D.distanceToZone(1845,v.entryZone,2);assert.equal(v.entryZone.source,'structured_values');assert.equal(r.usd,2);assert.equal(r.atr,1);assert.equal(r.inside,false)});
test('旧存档带千位逗号兼容恢复正确',()=>{const raw={...X.signal(),entryZone:'1,841.00 – 1,846.63',estimatedEntry:1845,archiveCategory:'WATCHLIST'},s=new X.Storage({[S.KEYS.archive]:JSON.stringify([raw]),[S.KEYS.events]:'[]',[S.KEYS.shadow]:'[]'}),v=S.getSignalCurrentView(raw.signalId,s);assert.equal(v.entryZone.valid,true);assert.deepEqual([v.entryZone.lower,v.entryZone.upper,v.entryZone.estimatedEntry],[1841,1846.63,1845]);assert.equal(S.isSignalTriggerEligible(v),true)});
test('中文展示文案变化不影响结构化核心数值',()=>{const d=structuredDecision('long',1841.123456,1846.654321,1845.5),a=S.entryNumbers(d,'long');d.triggerPlans.long.entryZone='新版中文：等待确认，不含任何价格';const b=S.entryNumbers(d,'long');assert.deepEqual(b,a);assert.deepEqual([b.lower,b.upper,b.estimatedEntry],[1841.123456,1846.654321,1845.5])});
test('malformed旧字符串严格失效且不回退确认价',()=>{for(const text of ['1,84.00 – 1,846.63','约1841到1846','1841','1,841.00 / 1,846.63']){const z=C.normalizeEntryZone({entryZone:text,estimatedEntry:1845});assert.equal(z.valid,false,text);assert.equal(z.lower,null);assert.equal(z.estimatedEntry,null)}});
test('lower大于upper严格失效',()=>{const z=C.normalizeEntryZone({entryZoneValues:{lower:1847,upper:1841,estimatedEntry:1845},entryZone:'1,841.00 – 1,847.00',estimatedEntry:1845});assert.equal(z.valid,false);assert.match(z.reason,/下界高于上界/);assert.equal(D.distanceToZone(1845,{lower:1847,upper:1841},2).valid,false)});
test('ATR无效时仅美元距离有效且distanceAtr为null',()=>{for(const atr of [null,0,-1,NaN]){const r=D.distanceToZone(1845,{lower:1841,upper:1843},atr);assert.equal(r.valid,true);assert.equal(r.usd,2);assert.equal(r.atr,null)}});
test('无效结构化方案被门控并阻止模拟开仓',()=>{const {a,s}=X.account(P),d=structuredDecision('long');d.triggerPlans.long.entryZoneValues={lower:1847,upper:1841,estimatedEntry:1845};const proposal=P.buildTradeProposal(d,a,'long'),opened=P.autoEngineOpenPosition(X.signal(d),d,null,a,s);assert.equal(proposal.ok,false);assert.match(proposal.reason,/结构化入场区无效/);assert.equal(opened.ok,false);assert.equal(P.loadPaperTrades(s).length,0)});
test('自动引擎结构门读取结构化入场区并默认拒绝无效区间',()=>{const A=require('../v1_3-auto-engine-core.js'),{a}=X.account(P),d=structuredDecision('long');a.engineState='AUTO_PAPER_RUNNING';d.triggerPlans.long.entryZoneValues={lower:1847,upper:1841,estimatedEntry:1845};const c=A.opportunityChecks(d,X.signal(d),a,[]);assert.equal(c.find(x=>x.name==='结构有效').met,false)});
test('JSON和CSV导出保持原始数值精度与含义',()=>{const d=structuredDecision('long',1841.123456,1846.654321,1845.432109),s=new X.Storage(),market={eth:{tf15m:[],tf1h:[],tf4h:[]},btc:{tf15m:[],tf1h:[],tf4h:[]}},r=S.recordSignalIfEligible(d,null,market,s);assert.equal(r.ok,true);const json=JSON.parse(S.exportSignalArchiveJSON(s)),z=json.signals[0].entryZone,csv=S.exportSignalArchiveCSV(s);assert.deepEqual([z.lower,z.upper,z.estimatedEntry],[1841.123456,1846.654321,1845.432109]);assert.match(csv,/1841\.123456,1846\.654321,1845\.432109/)});
test('正式TriggerPlan同时保留展示字符串和结构化数值',()=>{const plan=C.buildTriggerPlan('long',{atr14:2,price:1845,confirmedPrice:1845,state:'BULL_CONFIRMATION',trend:'up',isBreakout:true,isBreakdown:false},{state:'BULL_CONFIRMATION'},{htfState:'HTF_BULL_TREND'},{trend:'up'}, {ratio:1.3},'normal','none',{resistanceZones:[{lower:1845.89,upper:1846.63},{lower:1850,upper:1851}],supportZones:[{lower:1843,upper:1844},{lower:1840,upper:1841}]});assert.equal(typeof plan.entryZone,'string');assert.deepEqual(plan.entryZoneValues,{lower:1845.89,upper:1846.63,estimatedEntry:1846.63});assert.equal(C.normalizeEntryZone(plan).source,'structured_values')});
test('保存的真实复现证明旧错误并验证结构化结果',()=>{const f=require('./fixtures/entry-zone-live-reproduction-2026-07-18.json'),legacy=C.normalizeEntryZone({entryZone:f.beforeFix.long.displayEntryZone,estimatedEntry:f.beforeFix.long.estimatedEntry}),fixed=C.normalizeEntryZone(f.afterFix.long.structuredEntryZone,f.afterFix.long.structuredEntryZone.estimatedEntry);assert.deepEqual([f.beforeFix.long.parsedLower,f.beforeFix.long.parsedUpper],[1,846.63]);assert.deepEqual([legacy.lower,legacy.upper],[1845.89,1846.63]);assert.equal(fixed.valid,true);assert.deepEqual([fixed.lower,fixed.upper],[1845.89325,1846.62675]);assert.ok(f.afterFix.long.distanceUsdt<1);assert.ok(f.beforeFix.long.distanceUsdt>900)});
console.log(`RESULT passed=${passed} failed=${failed}`);if(failed)process.exitCode=1;
