'use strict';const assert=require('node:assert/strict'),F=require('../v1_4-gmkg-forecast-core.js'),O=require('../v1_4-gmkg-outcome-core.js');let passed=0,failed=0;function t(n,f){try{f();passed++;console.log('PASS '+n)}catch(e){failed++;console.error('FAIL '+n+': '+e.message)}}
const N=6,start=1700000000000,ref={symbol:'ETH',timeframe:'15m',openTime:start,closeTime:start+899999,timeframeMs:900000,sequenceIndex:0,barKey:`ETH-15m-${start+899999}`};
const b=i=>({openTime:start+i*900000,closeTime:start+(i+1)*900000-1,open:100+i,high:102+i,low:99+i,close:101+i,volume:10,isClosed:true,sequenceIndex:i,barKey:`ETH-15m-${start+(i+1)*900000-1}`}),complete=()=>Array.from({length:N+1},(_,i)=>b(i));
const windowRefs=Array.from({length:6},(_,i)=>({contentHash:String(i).padStart(64,'a')})),snapshot={predictionId:'p',referenceBarRef:ref,targetBarRef:{...b(N),symbol:'ETH',timeframe:'15m',timeframeMs:900000},expectedBarCount:N,referencePrice:101,directionThreshold:.02,expectedDirection:'UP',expectedPriceZones:{baseline:[99,103],upside:[104,110],downside:[90,98]},targetEndTime:b(N).closeTime,klineWindowRefs:windowRefs};
t('完整路径',()=>{const r=O.locateTargetPath(ref,N,complete());assert.equal(r.pathDataComplete,true);assert.equal(r.endpointDataComplete,true);assert.equal(r.observedBarCount,N)});
t('reference不计入observed',()=>assert.equal(O.locateTargetPath(ref,N,complete()).observedBarCount,N));
t('reference缺失不影响pathComplete',()=>{const r=O.locateTargetPath(ref,N,complete().slice(1));assert.equal(r.pathDataComplete,true);assert.equal(r.endpointDataComplete,false)});
t('缺一根路径失败',()=>{const a=complete().filter(x=>x.sequenceIndex!==3),r=O.locateTargetPath(ref,N,a);assert.equal(r.pathDataComplete,false);assert.equal(r.missingBarRefs[0].sequenceIndex,3)});
t('观测数量不等失败',()=>assert.equal(O.locateTargetPath(ref,N,complete().slice(0,-1)).pathDataComplete,false));
t('重复sequenceIndex失败',()=>{const a=complete();a.push({...b(3),barKey:'other'});assert.equal(O.locateTargetPath(ref,N,a).pathDataComplete,false)});
t('重复barKey失败',()=>{const a=complete();a[4].barKey=a[3].barKey;assert.equal(O.locateTargetPath(ref,N,a).pathDataComplete,false)});
t('时间乱序失败',()=>{const a=complete();a[4].openTime=a[3].openTime-1;assert.equal(O.locateTargetPath(ref,N,a).pathDataComplete,false)});
t('target缺失失败',()=>assert.equal(O.locateTargetPath(ref,N,complete().slice(0,-1)).endpointDataComplete,false));
t('未收盘失败',()=>{const a=complete();a[2].isClosed=false;assert.equal(O.locateTargetPath(ref,N,a).pathDataComplete,false)});
t('estimated失败',()=>{const a=complete();a[2].estimated=true;assert.equal(O.locateTargetPath(ref,N,a).pathDataComplete,false)});
t('synthetic失败',()=>{const a=complete();a[2].synthetic=true;assert.equal(O.locateTargetPath(ref,N,a).pathDataComplete,false)});
t('缺失原因带barKey和序号',()=>{const r=O.locateTargetPath(ref,N,complete().filter(x=>x.sequenceIndex!==3));assert.match(r.exclusionReasons.join(' '),/bar|K线/);assert.match(r.exclusionReasons.join(' '),/3/)});
t('完整结果端点计算',()=>{const o=O.buildOutcomeEvent(snapshot,{bars:complete(),evaluatedAt:9},'e1');assert.equal(o.actualStartPrice,101);assert.equal(o.actualEndPrice,107);assert.equal(o.actualDirection,'UP');assert.equal(o.directionCorrect,true)});
t('结果事件独立ID',()=>assert.equal(O.buildOutcomeEvent(snapshot,complete(),'e1').outcomeEventId,'p-e1'));
t('路径高低点',()=>{const o=O.buildOutcomeEvent(snapshot,complete(),'e1');assert.equal(o.actualHigh,108);assert.equal(o.actualLow,100)});
t('UP MFE MAE',()=>{const o=O.buildOutcomeEvent(snapshot,complete(),'e1');assert.equal(o.mfe,(108-101)/101);assert.equal(o.mae,(100-101)/101)});
t('DOWN MFE MAE',()=>{const o=O.buildOutcomeEvent({...snapshot,expectedDirection:'DOWN'},complete(),'e1');assert.equal(o.mfe,(101-100)/101);assert.equal(o.mae,(101-108)/101)});
t('RANGE mfe mae恒null',()=>{const o=O.buildOutcomeEvent({...snapshot,expectedDirection:'RANGE'},complete(),'e1');assert.equal(o.mfe,null);assert.equal(o.mae,null);assert.ok(o.maxAbsoluteExcursion>0)});
t('路径不完整指标全null',()=>{const a=complete().filter(x=>x.sequenceIndex!==3),o=O.buildOutcomeEvent(snapshot,a,'e1');for(const k of ['actualHigh','actualLow','mfe','mae','upperExcursion','lowerExcursion','maxAbsoluteExcursion','rangeBreachExcursion','realizedRangeInsideExpectedEnvelope','expectedEnvelopeTouched','invalidationTriggered'])assert.equal(o[k],null)});
t('reference缺失端点指标null但路径完整',()=>{const o=O.buildOutcomeEvent(snapshot,complete().slice(1),'e1');assert.equal(o.pathDataComplete,true);assert.equal(o.endpointDataComplete,false);assert.equal(o.actualStartPrice,null);assert.equal(o.actualReturn,null);assert.equal(o.pathEligibleForStatistics,false)});
t('target缺失方向分母false',()=>{const o=O.buildOutcomeEvent(snapshot,complete().slice(0,-1),'e1');assert.equal(o.directionEligibleForStatistics,false);assert.equal(o.actualEndPrice,null)});
t('方向分母与路径分母独立',()=>{const a=complete().filter(x=>x.sequenceIndex!==3),o=O.buildOutcomeEvent(snapshot,a,'e1');assert.equal(o.directionEligibleForStatistics,true);assert.equal(o.pathEligibleForStatistics,false)});
t('端点基准区命中',()=>assert.equal(O.buildOutcomeEvent({...snapshot,expectedPriceZones:{...snapshot.expectedPriceZones,baseline:[106,108]}},complete(),'e1').endpointInBaselineZone,true));
t('任一情景区命中',()=>assert.equal(O.buildOutcomeEvent(snapshot,complete(),'e1').endpointInAnyScenarioZone,true));
t('结果事件不可变',()=>assert.ok(Object.isFrozen(O.buildOutcomeEvent(snapshot,complete(),'e1'))));
t('窗口无法审计时排除正式统计',()=>{const o=O.buildOutcomeEvent({...snapshot,klineWindowRefs:[]},complete(),'e1');assert.equal(o.directionEligibleForStatistics,false);assert.equal(o.pathEligibleForStatistics,false);assert.match(o.exclusionReasons.join(' '),/unverifiable/)});
console.log(`RESULT passed=${passed} failed=${failed}`);if(failed)process.exitCode=1;
