'use strict';
const assert=require('node:assert/strict'),F=require('../v1_4-gmkg-forecast-core.js');let passed=0,failed=0;
function t(name,fn){try{fn();passed++;console.log('PASS '+name)}catch(e){failed++;console.error('FAIL '+name+': '+e.message)}}
const bar=(i,tf=900000,extra={})=>({openTime:1700000000000+i*tf,closeTime:1700000000000+(i+1)*tf-1,open:2000+i,high:2010+i,low:1990+i,close:2002+i,volume:100+i,isClosed:true,...extra});
function bars(n,tf=900000){const a=Array.from({length:n},(_,i)=>bar(i,tf));a.fetchedAt=1800000000000;return a}
const base={confirmedPrice:2200,atr14:40,trend:'flat',firstSupport:{price:2195},recentLow20:2150,isBreakout:false,isBreakdown:false,breakoutBarsCount:0,breakdownBarsCount:0,volumeRatio:1,dataQuality:{isStale:false}},e1={confirmedPrice:2200,atr14:20,trend:'flat',dataQuality:{isStale:false}},decision={dataHealth:'normal',falseBreakoutTier:'none'};
t('SHA-256固定向量',()=>assert.equal(F.sha256('abc'),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'));
t('SHA-256重复调用确定',()=>assert.equal(F.sha256('abc'),F.sha256('abc')));
t('窗口引用字段完整',()=>{const r=F.computeKlineWindowRef('ETHUSDT','15m',bars(3));assert.equal(r.closedBarCount,3);assert.equal(r.source,'BINANCE_SPOT');assert.equal(r.contentHash.length,64)});
t('T30.5 相同窗口哈希字节级确定',()=>{const a=bars(3);assert.equal(F.computeKlineWindowRef('ETHUSDT','15m',a).contentHash,F.computeKlineWindowRef('ETHUSDT','15m',a).contentHash)});
t('窗口内容变化改变哈希',()=>{const a=bars(3),b=bars(3);b[1].close++;assert.notEqual(F.computeKlineWindowRef('ETHUSDT','15m',a).contentHash,F.computeKlineWindowRef('ETHUSDT','15m',b).contentHash)});
t('T30.7 七个K线内容字段全部参与哈希',()=>{const baseline=bars(3),hash=F.computeKlineWindowRef('ETHUSDT','15m',baseline).contentHash;for(const field of ['open','high','low','close','volume','openTime','closeTime']){const variant=bars(3);variant[1][field]+=.25;assert.notEqual(F.computeKlineWindowRef('ETHUSDT','15m',variant).contentHash,hash,field)}});
t('窗口顺序变化拒绝',()=>{const a=bars(3);[a[0],a[1]]=[a[1],a[0]];assert.throws(()=>F.computeKlineWindowRef('ETHUSDT','15m',a),/ORDERED/) });
t('窗口重复时间拒绝',()=>{const a=bars(3);a[1].openTime=a[0].openTime;assert.throws(()=>F.computeKlineWindowRef('ETHUSDT','15m',a),/ORDERED/) });
t('T30.9 移除参与K线改变窗口哈希',()=>{const a=bars(3),b=bars(3);b.splice(1,1);assert.notEqual(F.computeKlineWindowRef('ETHUSDT','15m',a).contentHash,F.computeKlineWindowRef('ETHUSDT','15m',b).contentHash)});
t('T30.10 重复插入K线拒绝',()=>{const a=bars(3);a.splice(2,0,{...a[1]});assert.throws(()=>F.computeKlineWindowRef('ETHUSDT','15m',a),/ORDERED/)});
t('窗口未收盘拒绝',()=>{const a=bars(3);a[2].isClosed=false;assert.throws(()=>F.computeKlineWindowRef('ETHUSDT','15m',a),/UNCLOSED/) });
t('窗口空数组拒绝',()=>assert.throws(()=>F.computeKlineWindowRef('ETHUSDT','15m',[]),/EMPTY/));
t('窗口未知标的拒绝',()=>assert.throws(()=>F.computeKlineWindowRef('X','15m',bars(2)),/SYMBOL/));
t('窗口未知周期拒绝',()=>assert.throws(()=>F.computeKlineWindowRef('ETHUSDT','5m',bars(2)),/TIMEFRAME/));
t('窗口哈希不受fetchedAt影响',()=>{const a=bars(3),b=bars(3);a.fetchedAt=1;b.fetchedAt=2;assert.equal(F.computeKlineWindowRef('ETHUSDT','15m',a).contentHash,F.computeKlineWindowRef('ETHUSDT','15m',b).contentHash)});
t('T30.14-T30.17 窗口边界、数量和barKey精确',()=>{const a=bars(3),r=F.computeKlineWindowRef('ETHUSDT','15m',a);assert.equal(r.firstOpenTime,a[0].openTime);assert.equal(r.lastCloseTime,a.at(-1).closeTime);assert.equal(r.closedBarCount,a.length);assert.equal(r.firstBarKey,`ETH-15m-${a[0].closeTime}`);assert.equal(r.lastBarKey,`ETH-15m-${a.at(-1).closeTime}`)});
t('DataVintage availableAt等于收盘时间',()=>{const x=F.buildDataVintageRef('ETHUSDT','15m',bar(0),1800,1700);assert.equal(x.availableAt,x.observationPeriod[1]);assert.equal(x.publishedAt,x.availableAt)});
t('DataVintage revision固定0',()=>assert.equal(F.buildDataVintageRef('BTCUSDT','4h',bar(0,14400000),1800,1700).revisionNumber,0));
t('DataVintage来源唯一',()=>{const x=F.buildDataVintageRef('ETHUSDT','1h',bar(0,3600000),1800,1700);assert.equal(x.sourceId,'binance-spot-rest');assert.equal(x.sourceRef,'binance-spot-klines')});
t('DataVintage首次可用时间保留',()=>assert.equal(F.buildDataVintageRef('ETHUSDT','15m',bar(0),1800,1700).firstAvailableAt,1700));
t('DataVintage未收盘拒绝',()=>assert.throws(()=>F.buildDataVintageRef('ETHUSDT','15m',bar(0,900000,{isClosed:false}),1800,1700),/INVALID/));
const classify=(e4,more={})=>F.classifyProxyState({...base,...e4},{...e1,...more.e1},{...decision,...more});
t('PO_RANGE_LOW_STRUCTURE',()=>assert.equal(classify({confirmedPrice:2195}).proxyState,'PO_RANGE_LOW_STRUCTURE'));
t('PO_BREAKOUT_UP_STRUCTURE',()=>assert.equal(classify({trend:'up',isBreakout:true,breakoutBarsCount:1}).proxyState,'PO_BREAKOUT_UP_STRUCTURE'));
t('PO_TREND_UP_STRUCTURE',()=>assert.equal(classify({trend:'up',isBreakout:true,breakoutBarsCount:4}).proxyState,'PO_TREND_UP_STRUCTURE'));
t('PO_STALL_HIGH_STRUCTURE',()=>assert.equal(classify({trend:'up',breakoutBarsCount:4},{gmkgPreviousProxyState:'PO_TREND_UP_STRUCTURE',gmkgNoNewHighBars:2}).proxyState,'PO_STALL_HIGH_STRUCTURE'));
t('PO_BREAKDOWN_STRUCTURE',()=>assert.equal(classify({trend:'down',isBreakdown:true,breakdownBarsCount:1}).proxyState,'PO_BREAKDOWN_STRUCTURE'));
t('PO_TREND_DOWN_STRUCTURE',()=>assert.equal(classify({trend:'down',isBreakdown:true,breakdownBarsCount:4}).proxyState,'PO_TREND_DOWN_STRUCTURE'));
t('PO_SHARP_DROP_STRUCTURE',()=>assert.equal(classify({confirmedPrice:2000,atr14:20,trend:'down',volumeRatio:2},{gmkgLastClosed4h:{open:2200,close:2000}}).proxyState,'PO_SHARP_DROP_STRUCTURE'));
t('PO_RANGE_RECOVERY_STRUCTURE',()=>assert.equal(classify({trend:'flat',atr14:20},{gmkgPreviousProxyState:'PO_SHARP_DROP_STRUCTURE',gmkgSharpDropAtr:40}).proxyState,'PO_RANGE_RECOVERY_STRUCTURE'));
t('PO_UNKNOWN',()=>assert.equal(classify({confirmedPrice:2300,trend:'flat',firstSupport:{price:2100},recentLow20:2000}).proxyState,'PO_UNKNOWN'));
t('假突破确认失败不产出突破状态',()=>assert.notEqual(classify({trend:'up',isBreakout:true,breakoutBarsCount:1},{falseBreakoutTier:'confirmation_failed'}).proxyState,'PO_BREAKOUT_UP_STRUCTURE'));
t('数据陈旧归入INSUFFICIENT_DATA',()=>assert.equal(classify({dataQuality:{isStale:true}}).operatingMode,'INSUFFICIENT_DATA'));
t('置信度上限60',()=>assert.equal(classify({trend:'up',isBreakout:true,breakoutBarsCount:4},{e1:{trend:'up'}}).stateConfidence,60));
t('代理证据带PRICE_ONLY',()=>assert.match(classify({confirmedPrice:2195}).stateEvidence[0],/PRICE_ONLY/));
const frozenWeightTable={PO_RANGE_LOW_STRUCTURE:{baseline:50,upside:25,downside:25},PO_BREAKOUT_UP_STRUCTURE:{baseline:30,upside:50,downside:20},PO_TREND_UP_STRUCTURE:{baseline:30,upside:50,downside:20},PO_STALL_HIGH_STRUCTURE:{baseline:35,upside:25,downside:40},PO_BREAKDOWN_STRUCTURE:{baseline:30,upside:20,downside:50},PO_TREND_DOWN_STRUCTURE:{baseline:30,upside:20,downside:50},PO_SHARP_DROP_STRUCTURE:{baseline:30,upside:20,downside:50},PO_RANGE_RECOVERY_STRUCTURE:{baseline:50,upside:25,downside:25},PO_UNKNOWN:{baseline:50,upside:25,downside:25}};
for(const[state,expected]of Object.entries(frozenWeightTable))t(`§7.4冻结权重 ${state}`,()=>{const actual=F.computeScenarioWeights(state,60),message=`state=${state} expected=${JSON.stringify(expected)} actual=${JSON.stringify(actual)}`;assert.deepEqual(actual,expected,message);assert.equal(Object.values(actual).reduce((a,b)=>a+b,0),100,message);assert.ok(Object.values(actual).every(x=>Number.isFinite(x)&&x>=0&&x<=100),message)});
t('低置信向中性组合插值',()=>assert.deepEqual(F.computeScenarioWeights('PO_TREND_UP_STRUCTURE',0),{baseline:45,upside:27,downside:28}));
t('低置信多头状态按冻结算法插值',()=>assert.deepEqual(F.computeScenarioWeights('PO_TREND_UP_STRUCTURE',22.5),{baseline:38,upside:38,downside:24}));
t('低置信空头状态按冻结算法插值',()=>assert.deepEqual(F.computeScenarioWeights('PO_TREND_DOWN_STRUCTURE',22.5),{baseline:38,upside:24,downside:38}));
t('低置信区间状态按冻结算法插值',()=>assert.deepEqual(F.computeScenarioWeights('PO_RANGE_LOW_STRUCTURE',22.5),{baseline:47,upside:26,downside:27}));
t('24H阈值平方根6',()=>{const x=F.computeDirectionThreshold(40,2000,'24h');assert.equal(x.rawThreshold,.02*Math.sqrt(6));assert.equal(x.thresholdFormulaVersion,'v1.4-threshold-formula-2')});
t('72H阈值平方根18',()=>assert.equal(F.computeDirectionThreshold(40,2000,'72h').rawThreshold,.02*Math.sqrt(18)));
t('24H阈值下限',()=>assert.equal(F.computeDirectionThreshold(1,2000,'24h').directionThreshold,.008));
t('24H阈值上限',()=>assert.equal(F.computeDirectionThreshold(1000,2000,'24h').directionThreshold,.05));
t('72H阈值下限',()=>assert.equal(F.computeDirectionThreshold(1,2000,'72h').directionThreshold,.015));
t('72H阈值上限',()=>assert.equal(F.computeDirectionThreshold(1000,2000,'72h').directionThreshold,.08));
for(const x of [null,0,-1,NaN,Infinity])t(`ATR无效 ${String(x)}`,()=>assert.equal(F.computeDirectionThreshold(x,2000,'24h').reason,'ATR_INVALID'));
t('predictionId稳定',()=>assert.equal(F.generatePredictionId('ETH','24h',{closeTime:9},'v'),'GMKG-ETH-24h-9-v'));
const referencePrice=bar(119).close,ref=F.barRef('ETH',bar(119),0),target=h=>{const n=F.HORIZON_BARS[h];return{symbol:'ETH',timeframe:'15m',openTime:ref.openTime+n*900000,closeTime:ref.closeTime+n*900000,timeframeMs:900000,sequenceIndex:n,barKey:`ETH-15m-${ref.closeTime+n*900000}`}},windows=[];
for(const s of ['ETHUSDT','BTCUSDT'])for(const [tf,ms] of [['15m',900000],['1h',3600000],['4h',14400000]])windows.push(F.computeKlineWindowRef(s,tf,bars(30,ms)));
const snapDecision={confirmedPrice:referencePrice,htf4h:{...base,confirmedPrice:referencePrice,trend:'up',isBreakout:true,breakoutBarsCount:4},mtf1h:{...e1,trend:'up'},dataHealth:'normal',falseBreakoutTier:'none'};
function snapshot(h='24h'){return F.buildForecastSnapshot('ETH',h,ref,target(h),windows,snapDecision,{ok:true,serverTime:ref.closeTime+1000,fetchedAt:ref.closeTime+900},F.ALGORITHM_VERSION)}
t('24H快照96根',()=>assert.equal(snapshot().expectedBarCount,96));
t('72H快照288根',()=>assert.equal(snapshot('72h').expectedBarCount,288));
t('快照六窗口引用',()=>assert.equal(snapshot().klineWindowRefs.length,6));
t('T30.1 六窗口组合精确且唯一',()=>assert.deepEqual(snapshot().klineWindowRefs.map(x=>`${x.symbol}-${x.timeframe}`).sort(),['BTCUSDT-15m','BTCUSDT-1h','BTCUSDT-4h','ETHUSDT-15m','ETHUSDT-1h','ETHUSDT-4h']));
t('T30.18 快照窗口哈希可由冻结输入独立复算',()=>{const s=snapshot();for(const [i,symbol] of ['ETHUSDT','ETHUSDT','ETHUSDT','BTCUSDT','BTCUSDT','BTCUSDT'].entries()){const tf=['15m','1h','4h'][i%3],ms={"15m":900000,"1h":3600000,"4h":14400000}[tf];assert.equal(s.klineWindowRefs[i].contentHash,F.computeKlineWindowRef(symbol,tf,bars(30,ms)).contentHash)}});
t('快照正式状态UNKNOWN',()=>{const s=snapshot();assert.equal(s.primaryState,'UNKNOWN');assert.equal(s.fusionState,'UNKNOWN')});
t('快照模式PRICE_ONLY',()=>assert.equal(snapshot().operatingMode,'PRICE_ONLY_MODE'));
t('快照仅展示许可',()=>{const a=snapshot().actionPermission;assert.equal(a.mode,'DISPLAY_ONLY');assert.equal(a.gateStatus,'WAIT')});
t('校准概率恒null',()=>{const s=snapshot();assert.equal(s.calibratedProbability,null);assert.deepEqual(s.calibratedProbabilities,{baseline:null,upside:null,downside:null})});
t('快照内容哈希64位',()=>assert.equal(snapshot().contentHash.length,64));
t('快照不可变',()=>assert.ok(Object.isFrozen(snapshot())&&Object.isFrozen(snapshot().scenarioWeights)));
t('快照同输入确定',()=>assert.equal(snapshot().contentHash,snapshot().contentHash));
t('快照dataCutoff等于生成时间',()=>{const s=snapshot();assert.equal(s.dataCutoffTime,s.generatedAt)});
t('情景区域严格有序',()=>{const z=snapshot().expectedPriceZones;for(const v of Object.values(z))assert.ok(v[0]<v[1])});
t('基准区公式',()=>{const s=snapshot(),d=s.directionThreshold,p=s.referencePrice;assert.equal(s.expectedPriceZones.baseline[0],p*(1-.5*d))});
t('上行情景公式',()=>{const s=snapshot(),d=s.directionThreshold,p=s.referencePrice;assert.equal(s.expectedPriceZones.upside[1],p*(1+2*d))});
t('下行情景公式',()=>{const s=snapshot(),d=s.directionThreshold,p=s.referencePrice;assert.equal(s.expectedPriceZones.downside[0],p*(1-2*d))});
t('服务器时间缺失阻断',()=>assert.throws(()=>F.buildForecastSnapshot('ETH','24h',ref,target('24h'),windows,snapDecision,{ok:false},F.ALGORITHM_VERSION),/SERVER_TIME/));
t('reference未收盘阻断',()=>assert.throws(()=>F.buildForecastSnapshot('ETH','24h',ref,target('24h'),windows,snapDecision,{ok:true,serverTime:ref.closeTime-1},F.ALGORITHM_VERSION),/NOT_CLOSED/));
t('窗口不是六个阻断',()=>assert.throws(()=>F.buildForecastSnapshot('ETH','24h',ref,target('24h'),windows.slice(1),snapDecision,{ok:true,serverTime:ref.closeTime+1},F.ALGORITHM_VERSION),/SIX/));
t('六窗口存在重复组合时阻断',()=>{const bad=[...windows];bad[5]=bad[0];assert.throws(()=>F.buildForecastSnapshot('ETH','24h',ref,target('24h'),bad,snapDecision,{ok:true,serverTime:ref.closeTime+1},F.ALGORITHM_VERSION),/UNAUDITABLE/)});
t('窗口哈希损坏时阻断',()=>{const bad=windows.map((x,i)=>i?x:{...x,contentHash:'bad'});assert.throws(()=>F.buildForecastSnapshot('ETH','24h',ref,target('24h'),bad,snapDecision,{ok:true,serverTime:ref.closeTime+1},F.ALGORITHM_VERSION),/UNAUDITABLE/)});
console.log(`RESULT passed=${passed} failed=${failed}`);if(failed)process.exitCode=1;
