'use strict';
const assert=require('node:assert/strict'),S=require('../v1_4-storage-core.js');let passed=0,failed=0;
function test(name,fn){return Promise.resolve().then(fn).then(()=>{passed++;console.log('PASS '+name)},e=>{failed++;console.error('FAIL '+name+': '+e.stack)})}
class Storage{constructor(seed={},quota=Infinity){this.m=new Map(Object.entries(seed));this.quota=quota}get length(){return this.m.size}key(i){return[...this.m.keys()][i]??null}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){v=String(v);const copy=new Map(this.m);copy.set(k,v);const size=[...copy].reduce((n,[a,b])=>n+a.length+b.length,0);if(size>this.quota){const e=Error('quota');e.name='QuotaExceededError';throw e}this.m=copy}removeItem(k){this.m.delete(k)}}
const snapshot=(id,payload='x'.repeat(6000))=>({schemaVersion:'v1.4-forecastsnapshot-1',predictionId:id,instrument:'ETH',horizon:id.includes('72')?'72h':'24h',generatedAt:Number(id.replace(/\D/g,''))||1,algorithmVersion:'a',weightVersion:'w',datasetVersion:'d',payload});
const outcome=id=>({schemaVersion:'v1.4-outcomeevent-1',outcomeEventId:'O-'+id,predictionId:id,evaluationVersion:'e1',evaluatedAt:1});
const diagnostic=i=>({schemaVersion:'v1.3.1-trade-gate-1',diagnosticKey:'ETHUSDT|'+i,evaluatedAt:i,sourceConfirmedBarTime:i,finalConclusion:'观察'});
function repo(storage=new Storage(),adapter=new S.MemoryAdapter()){return S.createRepository({localStorage:storage,adapter,navigatorStorage:{estimate:async()=>({usage:0,quota:10_000_000})}})}
(async()=>{
await test('localStorage接近容量上限仍可准确审计',()=>{const s=new Storage({large:'x'.repeat(9000)},10000),a=S.auditLocalStorage(s);assert.ok(a.totalBytes>=9005);assert.equal(a.largest.key,'large')});
await test('QuotaExceededError被独立识别',()=>{const e=Error('full');e.name='QuotaExceededError';assert.equal(S.classifyError(e).code,'QUOTA_EXCEEDED')});
await test('52条大型旧快照迁移到IndexedDB并删除已验证旧数组',async()=>{const rows=Array.from({length:52},(_,i)=>snapshot('P'+i)),s=new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify(rows)}),r=repo(s);await r.open();const m=await r.migrateLegacy();assert.equal(m.state,'VERIFIED');assert.equal((await r.getAll('snapshots')).length,52);assert.equal(s.getItem('ethAlphaGmkgForecastSnapshots'),null)});
await test('迁移前完整备份保留52条摘要',async()=>{const s=new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify(Array.from({length:52},(_,i)=>snapshot('P'+i)))}),r=repo(s);await r.open();await r.migrateLegacy();const b=JSON.parse(r.lastLegacyBackup);assert.equal(b.summary.records.snapshots,52);assert.equal(b.schemaVersion,S.SCHEMA_VERSION)});
await test('迁移中断保留localStorage原数据',async()=>{const rows=[snapshot('P1'),snapshot('P2')],s=new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify(rows)}),a=new S.MemoryAdapter({interruptAfter:1}),r=repo(s,a);await r.open();const m=await r.migrateLegacy();assert.equal(m.state,'FAILED');assert.ok(s.getItem('ethAlphaGmkgForecastSnapshots'))});
await test('迁移中断后下次启动安全续传',async()=>{const rows=[snapshot('P1'),snapshot('P2')],s=new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify(rows)}),a=new S.MemoryAdapter({interruptAfter:1}),r1=repo(s,a);await r1.open();await r1.migrateLegacy();a.interruptAfter=null;const r2=repo(s,a);await r2.open();const m=await r2.migrateLegacy();assert.equal(m.state,'VERIFIED');assert.equal((await r2.getAll('snapshots')).length,2)});
await test('迁移后健康检查失败会恢复全部旧localStorage',async()=>{class ProbeFailAdapter extends S.MemoryAdapter{async putMany(entries,options){if(entries.some(x=>x.store==='repositoryMeta'))throw Error('probe failed');return super.putMany(entries,options)}}const original=JSON.stringify([snapshot('P1')]),s=new Storage({ethAlphaGmkgForecastSnapshots:original}),r=repo(s,new ProbeFailAdapter());await r.open();const x=await r.migrateLegacy();assert.equal(x.state,'FAILED');assert.equal(s.getItem('ethAlphaGmkgForecastSnapshots'),original)});
await test('重复执行迁移不重复记录',async()=>{const s=new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify([snapshot('P1')])}),a=new S.MemoryAdapter(),r1=repo(s,a);await r1.open();await r1.migrateLegacy();s.setItem('ethAlphaGmkgForecastSnapshots',JSON.stringify([snapshot('P1')]));const r2=repo(s,a);await r2.open();assert.equal((await r2.migrateLegacy()).state,'VERIFIED');assert.equal((await r2.getAll('snapshots')).length,1)});
await test('迁移前后关键ID一致',async()=>{const ids=['P1','P2','P3'],s=new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify(ids.map(snapshot))}),r=repo(s);await r.open();await r.migrateLegacy();assert.deepEqual((await r.getAll('snapshots')).map(x=>x.predictionId).sort(),ids)});
await test('正式快照相同ID相同内容幂等',async()=>{const r=repo();await r.open();assert.equal((await r.putImmutable('snapshots',snapshot('P1'))).deduped,false);assert.equal((await r.putImmutable('snapshots',snapshot('P1'))).deduped,true);assert.equal((await r.getAll('snapshots')).length,1)});
await test('正式快照相同ID不同内容拒绝覆盖',async()=>{const r=repo();await r.open();await r.putImmutable('snapshots',snapshot('P1','a'));const x=await r.putImmutable('snapshots',snapshot('P1','b'));assert.equal(x.error.code,'ID_CONFLICT');assert.equal((await r.get('snapshots','P1')).payload,'a')});
await test('追加OutcomeEvent不覆盖既有事件',async()=>{const r=repo();await r.open();await r.putImmutable('outcomes',outcome('P1'));await r.putImmutable('outcomes',outcome('P2'));assert.equal((await r.getAll('outcomes')).length,2)});
await test('快照与Outcome bundle写入失败保持原子',async()=>{const a=new S.MemoryAdapter(),r=repo(new Storage(),a);await r.open();a.interruptAfter=1;const x=await r.putBundle([{name:'snapshots',record:snapshot('P1')},{name:'outcomes',record:outcome('P1')}]);assert.equal(x.ok,false);assert.equal((await r.getAll('snapshots')).length,0);assert.equal((await r.getAll('outcomes')).length,0)});
await test('Outcome不得缺少稳定ID',async()=>{const r=repo();await r.open();const x=await r.putImmutable('outcomes',{predictionId:'P1'});assert.equal(x.ok,false);assert.equal(x.error.code,'DATA_ERROR')});
await test('同一收盘K线predictionId不会重复生成',async()=>{const r=repo();await r.open();for(let i=0;i<30;i++)await r.putImmutable('snapshots',snapshot('GMKG-ETH-24h-1700000000-a'));assert.equal((await r.getAll('snapshots')).length,1)});
await test('诊断同一收盘K线更新投影不追加',async()=>{const r=repo();await r.open();await r.putProjection('diagnostics',diagnostic(1));await r.putProjection('diagnostics',{...diagnostic(1),revision:2});const rows=await r.getAll('diagnostics');assert.equal(rows.length,1);assert.equal(rows[0].revision,2)});
await test('诊断历史最多1000条',async()=>{const r=repo();await r.open();for(let i=0;i<1005;i++)await r.putProjection('diagnostics',diagnostic(i));const rows=await r.getAll('diagnostics');assert.equal(rows.length,1000);assert.equal(Math.min(...rows.map(x=>x.evaluatedAt)),5)});
await test('诊断裁剪不删除正式快照',async()=>{const r=repo();await r.open();await r.putImmutable('snapshots',snapshot('P1'));for(let i=0;i<1005;i++)await r.putProjection('diagnostics',diagnostic(i));assert.equal((await r.getAll('snapshots')).length,1)});
await test('IndexedDB容量失败进入BLOCKED且错误类型不伪装',async()=>{const e=Error('full');e.name='QuotaExceededError';const r=repo(new Storage(),new S.MemoryAdapter({failWrite:e}));await r.open();const x=await r.putImmutable('snapshots',snapshot('P1')),a=await r.audit();assert.equal(x.error.code,'QUOTA_EXCEEDED');assert.equal(a.status,'BLOCKED')});
await test('IndexedDB其他写入失败不是容量错误',async()=>{const r=repo(new Storage(),new S.MemoryAdapter({failWrite:Error('disk')}));await r.open();const x=await r.putImmutable('snapshots',snapshot('P1'));assert.equal(x.error.code,'DATABASE_ERROR')});
await test('IndexedDB不可用明确BLOCKED',async()=>{const e=Error('denied');e.name='SecurityError';const r=repo(new Storage(),new S.MemoryAdapter({failOpen:e})),x=await r.open();assert.equal(x.ok,false);assert.equal((await r.audit()).status,'BLOCKED');assert.equal(r.lastError.code,'PERMISSION_DENIED')});
await test('导出后可验证导入并恢复诊断累计统计',async()=>{const sa=new Storage({ethAlphaTradeGateDiagnostics:JSON.stringify({schemaVersion:'v1.3.1-trade-gate-1',stats:{totalEvaluations:88},records:[]})}),a=repo(sa);await a.open();await a.putImmutable('snapshots',snapshot('P1'));await a.putImmutable('outcomes',outcome('P1'));const text=await a.exportAll(),parsed=JSON.parse(text),sb=new Storage(),b=repo(sb);assert.equal(parsed.metadata.diagnosticStats.totalEvaluations,88);await b.open();const x=await b.importBackup(text);assert.equal(x.ok,true);assert.equal((await b.getAll('snapshots')).length,1);assert.equal((await b.getAll('outcomes')).length,1);assert.equal(JSON.parse(sb.getItem('ethAlphaTradeGateDiagnostics')).stats.totalEvaluations,88)});
await test('重复导入按稳定ID去重',async()=>{const a=repo();await a.open();await a.putImmutable('snapshots',snapshot('P1'));const text=await a.exportAll(),b=repo();await b.open();await b.importBackup(text);const x=await b.importBackup(text);assert.equal(x.ok,true);assert.equal((await b.getAll('snapshots')).length,1)});
await test('相同ID不同内容导入产生冲突且不覆盖',async()=>{const r=repo();await r.open();await r.putImmutable('snapshots',snapshot('P1','old'));const data={schemaVersion:S.SCHEMA_VERSION,datasets:{snapshots:[snapshot('P1','new')]}};const x=await r.importBackup(data);assert.equal(x.ok,false);assert.equal(x.conflicts.length,1);assert.equal((await r.get('snapshots','P1')).payload,'old')});
await test('诊断投影导入同ID不同内容同样不得覆盖',async()=>{const r=repo();await r.open();await r.putProjection('diagnostics',{...diagnostic(1),finalConclusion:'原结论'});const data={schemaVersion:S.SCHEMA_VERSION,datasets:{diagnostics:[{...diagnostic(1),finalConclusion:'冲突结论'}]}};const x=await r.importBackup(data);assert.equal(x.ok,false);assert.equal((await r.get('diagnostics','ETHUSDT|1')).finalConclusion,'原结论')});
await test('导入拒绝未知格式版本',async()=>{const r=repo();await r.open();const x=await r.importBackup({schemaVersion:'future',datasets:{}});assert.equal(x.error.code,'DATA_ERROR')});
await test('BLOCKED时已有正式结果仍可读取',async()=>{const a=new S.MemoryAdapter(),r=repo(new Storage(),a);await r.open();await r.putImmutable('snapshots',snapshot('P1'));const e=Error('full');e.name='QuotaExceededError';a.failWrite=e;await r.putImmutable('snapshots',snapshot('P2'));assert.equal((await r.get('snapshots','P1')).predictionId,'P1');assert.equal((await r.audit()).status,'BLOCKED')});
await test('存储恢复必须通过健康探针才解除错误',async()=>{const a=new S.MemoryAdapter(),r=repo(new Storage(),a);await r.open();a.failWrite=Error('down');await r.putImmutable('snapshots',snapshot('P1'));assert.equal((await r.audit()).status,'BLOCKED');a.failWrite=null;assert.equal((await r.healthCheck()).ok,true);assert.notEqual((await r.audit()).status,'BLOCKED')});
await test('迁移不删除模拟账户、持仓和建议档案',async()=>{const signal=JSON.stringify([{signalId:'S1'}]),s=new Storage({ethAlphaGmkgForecastSnapshots:JSON.stringify([snapshot('P1')]),ethAlphaPaperAccount:'{"cash":500}',ethAlphaPaperTrades:'[{"tradeId":"T1"}]',ethAlphaSignalArchive:signal}),r=repo(s);await r.open();await r.migrateLegacy();assert.equal(s.getItem('ethAlphaPaperAccount'),'{"cash":500}');assert.equal(s.getItem('ethAlphaPaperTrades'),'[{"tradeId":"T1"}]');assert.equal(JSON.parse(s.getItem('ethAlphaSignalArchive')).length,1);assert.equal(JSON.parse(s.getItem('ethAlphaSignalArchive'))[0].signalId,'S1');assert.equal((await r.getAll('signalArchive')).length,1)});
await test('建议档案完整历史进IndexedDB且localStorage仅保留100条运行缓存',async()=>{const signals=Array.from({length:150},(_,i)=>({signalId:'S'+i,generatedAt:i,forecastSnapshot:{m15:{directionLabel:'偏多'},large:'x'.repeat(1000)}})),s=new Storage({ethAlphaSignalArchive:JSON.stringify(signals),ethAlphaSignalEvents:'[]',ethAlphaShadowResults:'[]'}),r=repo(s);await r.open();await r.migrateLegacy();assert.equal((await r.getAll('signalArchive')).length,150);const local=JSON.parse(s.getItem('ethAlphaSignalArchive'));assert.equal(local.length,S.SIGNAL_LOCAL_CACHE_LIMIT);assert.equal(local[0].forecastSnapshot.large,undefined);assert.equal((await r.get('signalArchive','S0')).forecastSnapshot.large.length,1000)});
await test('运行缓存压缩后重复归档不会与完整不可变快照冲突',async()=>{const signal={signalId:'S1',generatedAt:1,forecastSnapshot:{m15:{directionLabel:'偏多'},large:'x'.repeat(1000)}},s=new Storage({ethAlphaSignalArchive:JSON.stringify([signal]),ethAlphaSignalEvents:'[]',ethAlphaShadowResults:'[]'}),r=repo(s);await r.open();await r.migrateLegacy();const x=await r.archiveOperationalDatasets();assert.equal(x.ok,true);assert.equal((await r.get('signalArchive','S1')).forecastSnapshot.large.length,1000)});
await test('旧诊断迁移后localStorage仅保留25条缓存和累计统计',async()=>{const records=Array.from({length:80},(_,i)=>diagnostic(i)),s=new Storage({ethAlphaTradeGateDiagnostics:JSON.stringify({schemaVersion:'v1.3.1-trade-gate-1',stats:{totalEvaluations:100},records})}),r=repo(s);await r.open();await r.migrateLegacy();const local=JSON.parse(s.getItem('ethAlphaTradeGateDiagnostics'));assert.equal(local.records.length,25);assert.equal(local.stats.totalEvaluations,100);assert.equal((await r.getAll('diagnostics')).length,80)});
await test('损坏旧JSON迁移失败且原数据保留',async()=>{const s=new Storage({ethAlphaGmkgForecastSnapshots:'{bad'}),r=repo(s);await r.open();const x=await r.migrateLegacy();assert.equal(x.state,'FAILED');assert.equal(s.getItem('ethAlphaGmkgForecastSnapshots'),'{bad')});
console.log(`RESULT passed=${passed} failed=${failed}`);if(failed)process.exitCode=1
})();
