import { randomUUID } from 'node:crypto';
import { freshnessThresholdMs, INTERVALS, SCHEMA_VERSION, SYMBOLS } from '../domain/constants.js';
import { canonicalJsonHash, sha256 } from '../domain/hash.js';
import { detectGaps, normalizeFunding, normalizeKlines, normalizeLongShort, normalizeOpenInterest, normalizeTakerFlow } from '../domain/normalize.js';
import { EndpointHealthRegistry, evaluateHealth } from '../health/evaluator.js';
import { BackfillWorker } from './backfill.js';
import { measureServerTime } from './time-guard.js';

const endpoint={time:'binance-spot-time',spotKlines:'binance-spot-klines',futuresKlines:'binance-futures-klines',funding:'binance-futures-funding-rate',openInterest:'binance-futures-open-interest',longShort:'binance-futures-global-long-short',taker:'binance-futures-taker-flow'};
const frequencies={[endpoint.time]:30000,[endpoint.spotKlines]:30000,[endpoint.futuresKlines]:60000,[endpoint.funding]:300000,[endpoint.openInterest]:60000,[endpoint.longShort]:900000,[endpoint.taker]:900000};

export class CollectorService{
  constructor({adapter,repository,config,now=Date.now,logger=console}){this.adapter=adapter;this.repository=repository;this.config=config;this.now=now;this.logger=logger;this.startedAt=null;this.lastRun=null;this.lastServerTime=null;this.running=false;this.lease=null;this.leaseLost=false;this.blockedReason='NOT_STARTED';this.inflight=new Set();this.timers=[];this.abortController=new AbortController();this.endpointHealth=new EndpointHealthRegistry(frequencies,now);this.databaseAvailable=null;this.databaseWriteHealthy=null;this.workCounts={unresolved:0,pending:0};this.backfillWorker=new BackfillWorker({adapter,repository,collector:this,maxAttempts:config.backfillMaxAttempts||5});}
  async start(){if(this.running)throw new Error('COLLECTOR_ALREADY_RUNNING');this.abortController=new AbortController();const lease=await this.repository.acquireLease('primary-collector',this.config.collectorId,this.config.leaseTtlMs);if(!lease)throw Object.assign(new Error('Collector lease held'),{code:'COLLECTOR_LEASE_HELD'});this.lease=lease;this.leaseLost=false;this.running=true;this.blockedReason=null;this.startedAt=this.now();try{await this.runCycle();}catch(error){this.running=false;this.blockedReason=error.code||'STARTUP_FAILED';this.clearSchedulers();this.abortController.abort(this.blockedReason);throw error;}if(this.running){this.schedule(()=>this.runCycle(),30000);this.schedule(()=>this.collectDerivatives(),60000);this.schedule(()=>this.runBackfill(),this.config.backfillPollMs||15000);this.schedule(()=>this.heartbeat(),Math.floor(this.config.leaseTtlMs/3));}return this.status();}
  requireLease(){if(!this.running||this.leaseLost||!this.lease)throw Object.assign(new Error('Collector is not an active lease holder'),{code:this.leaseLost?'LEASE_LOST':'COLLECTOR_NOT_RUNNING'});return this.lease;}
  schedule(task,ms){if(!this.running)return;const timer=setInterval(()=>{if(!this.running)return;const promise=Promise.resolve().then(()=>task()).catch(error=>{if(error.code==='FENCING_TOKEN_REJECTED'||error.code==='LEASE_LOST')this.loseLease(error.code);else this.logger.error('scheduled task failed',{code:error.code||error.message});}).finally(()=>this.inflight.delete(promise));this.inflight.add(promise);},ms);this.timers.push(timer);}
  clearSchedulers(){for(const timer of this.timers)clearInterval(timer);this.timers=[];}
  loseLease(reason='LEASE_LOST'){if(this.leaseLost)return;this.leaseLost=true;this.running=false;this.blockedReason=reason;this.clearSchedulers();this.abortController.abort(reason);}
  async heartbeat(){const lease=this.requireLease();const renewed=await this.repository.heartbeatLease(lease.leaseName,lease.holderId,lease.fencingToken,this.config.leaseTtlMs);if(!renewed){this.loseLease('LEASE_LOST');throw Object.assign(new Error('Collector lease lost'),{code:'LEASE_LOST'});}this.lease=renewed;return renewed;}
  async currentServerTime(signal=this.abortController.signal){this.requireLease();this.endpointHealth.attempt(endpoint.time);const time=await measureServerTime(this.adapter,{now:this.now,maxClockOffsetMs:this.config.maxClockOffsetMs,signal});if(time.ok)this.endpointHealth.success(endpoint.time,{httpStatus:200,dataObservationAt:time.sourceServerTime});else this.endpointHealth.failure(endpoint.time,{code:time.reason});this.lastServerTime=time;return time;}
  async trackedFetch(endpointId,meta,fetcher){this.requireLease();this.endpointHealth.attempt(endpointId);try{const response=await fetcher(this.abortController.signal);this.endpointHealth.success(endpointId,{httpStatus:response.status,dataObservationAt:meta.dataObservationAt});await this.repository.saveAttempt?.({runId:meta.runId||null,requestId:response.requestId,sourceId:meta.sourceId,endpointId,instrument:meta.instrument,marketType:meta.marketType,interval:meta.interval,startedAt:response.startedAt,finishedAt:response.receivedAt,httpStatus:response.status,roundTripMs:response.roundTripMs,success:true},this.lease);return response;}catch(error){this.endpointHealth.failure(endpointId,{httpStatus:error.status,code:error.code});if(meta.runId)await this.repository.saveAttempt?.({runId:meta.runId,requestId:randomUUID(),sourceId:meta.sourceId,endpointId,instrument:meta.instrument,marketType:meta.marketType,interval:meta.interval,startedAt:this.now(),finishedAt:this.now(),httpStatus:error.status,success:false,rateLimited:error.code==='RATE_LIMITED',errorCode:error.code||'UNKNOWN',errorDetail:error.message},this.lease).catch(()=>{});throw error;}}
  async recordWriteFailure(error,{sourceId,endpointId,requestId}){if(!['RAW_JSON_UNSERIALIZABLE','RAW_JSON_CIRCULAR','RAW_CONTENT_HASH_MISMATCH'].includes(error.code))return;await this.repository.audit?.({eventType:'RAW_PAYLOAD_REJECTED',sourceId,endpointId,requestId,severity:'ERROR',detail:{errorCode:error.code},occurredAt:this.now()},this.lease).catch(()=>{});}
  async runCycle(){this.requireLease();const runId=randomUUID();try{await this.repository.ping();this.databaseAvailable=true;await this.repository.startRun?.({runId,collectorId:this.config.collectorId,startedAt:this.now(),serverTime:this.lastServerTime},this.lease);this.databaseWriteHealthy=true;const time=await this.currentServerTime();if(!time.ok){this.lastRun={at:this.now(),state:'BLOCKED',reason:time.reason,time};await this.persistHealth();await this.repository.finishRun?.(runId,'BLOCKED',time.reason,this.lease);return this.lastRun;}const results=await Promise.allSettled(SYMBOLS.flatMap(symbol=>INTERVALS.map(interval=>this.collectBars('spot',symbol,interval,time.sourceServerTime,runId))));const failed=results.filter(x=>x.status==='rejected').length;this.workCounts=await this.repository.countWork?.()||this.workCounts;this.lastRun={at:this.now(),state:failed?'DEGRADED':'HEALTHY',time,results:results.map(x=>x.status==='fulfilled'?x.value:{ok:false,error:x.reason?.code||x.reason?.message})};await this.persistHealth();await this.repository.finishRun?.(runId,failed?'DEGRADED':'SUCCEEDED',failed?'PARTIAL_FAILURE':null,this.lease);return this.lastRun;}catch(error){this.databaseWriteHealthy=false;if(error.code==='FENCING_TOKEN_REJECTED')this.loseLease(error.code);this.lastRun={at:this.now(),state:'BLOCKED',reason:error.code||'DATABASE_WRITE_FAILED'};throw error;}}
  async collectBars(marketType,instrument,interval,serverTime,runId=null){const sourceId=marketType==='spot'?'binance-spot-rest':'binance-usdt-futures-rest',endpointId=marketType==='spot'?endpoint.spotKlines:endpoint.futuresKlines;const response=await this.trackedFetch(endpointId,{sourceId,instrument,marketType,interval,runId},signal=>marketType==='spot'?this.adapter.spotKlines(instrument,interval,{limit:500,signal}):this.adapter.futuresKlines(instrument,interval,{limit:500,signal}));return this.collectBarsFromResponse({response,sourceId,endpointId,instrument,marketType,interval,serverTime});}
  async collectBarsFromResponse({response,sourceId,endpointId=sourceId==='binance-spot-rest'?endpoint.spotKlines:endpoint.futuresKlines,instrument,marketType,interval,serverTime}){const lease=this.requireLease();try{const contentHash=canonicalJsonHash(response.body);const rawPayloadId=await this.repository.saveRaw(response,{sourceId,endpointId,contentHash,schemaVersion:SCHEMA_VERSION,qualityState:'NORMAL'},lease);const normalized=normalizeKlines({rows:response.body,sourceId,endpointId,instrument,marketType,interval,serverTime,fetchedAt:response.receivedAt,rawPayloadId,requestId:response.requestId});const provisional=await this.repository.saveProvisionalBars?.(normalized.provisional,lease)||{inserted:0,deduped:0};const saved=await this.repository.upsertMarketBars(normalized.formal,lease);const gaps=detectGaps(normalized.formal,interval).map(g=>({...g,gapId:`gap:${sha256({sourceId,instrument,marketType,interval,start:g.startOpenTime,end:g.endOpenTime})}`,sourceId,instrument,marketType,interval}));for(const gap of await this.repository.saveGaps(gaps,lease))await this.repository.createBackfill(gap,lease);this.endpointHealth.observation(endpointId,Math.max(0,...normalized.formal.map(x=>x.closeTime))||null);this.databaseWriteHealthy=true;return{ok:true,sourceId,instrument,marketType,interval,formal:normalized.formal.length,provisional:normalized.provisional.length,provisionalInserted:provisional.inserted,rejected:normalized.rejected.length,gaps:gaps.length,...saved};}catch(error){this.databaseWriteHealthy=false;await this.recordWriteFailure(error,{sourceId,endpointId,requestId:response.requestId});throw error;}}
  async collectDerivatives(){this.requireLease();const runId=randomUUID();await this.repository.startRun?.({runId,collectorId:this.config.collectorId,startedAt:this.now(),serverTime:this.lastServerTime},this.lease);try{const time=await this.currentServerTime();if(!time.ok){await this.repository.finishRun?.(runId,'BLOCKED',time.reason,this.lease);return{ok:false,blocked:true,reason:time.reason};}const jobs=SYMBOLS.flatMap(symbol=>[this.collectPoint('funding_rates',symbol,endpoint.funding,signal=>this.adapter.fundingRates(symbol,{limit:8,signal}),normalizeFunding,null,runId),this.collectPoint('open_interest',symbol,endpoint.openInterest,signal=>this.adapter.openInterest(symbol,{signal}),normalizeOpenInterest,null,runId),this.collectPoint('long_short_ratios',symbol,endpoint.longShort,signal=>this.adapter.longShortRatio(symbol,'15m',30,{signal}),normalizeLongShort,'15m',runId),this.collectPoint('taker_flow',symbol,endpoint.taker,signal=>this.adapter.takerFlow(symbol,'15m',30,{signal}),normalizeTakerFlow,'15m',runId),...INTERVALS.map(interval=>this.collectBars('usdt_perpetual',symbol,interval,time.sourceServerTime,runId))]);const results=await Promise.allSettled(jobs),failed=results.filter(x=>x.status==='rejected').length;await this.persistHealth();await this.repository.finishRun?.(runId,failed?'DEGRADED':'SUCCEEDED',failed?'PARTIAL_FAILURE':null,this.lease);return results;}catch(error){await this.repository.finishRun?.(runId,'BLOCKED',error.code||'DERIVATIVES_FAILED',this.lease).catch(()=>{});throw error;}}
  async collectPoint(table,instrument,endpointId,fetcher,normalizer,interval=null,runId=null){const sourceId='binance-usdt-futures-rest';const response=await this.trackedFetch(endpointId,{sourceId,instrument,marketType:'usdt_perpetual',interval,runId},fetcher);try{const rawPayloadId=await this.repository.saveRaw(response,{sourceId,endpointId,contentHash:canonicalJsonHash(response.body),schemaVersion:SCHEMA_VERSION,qualityState:'NORMAL'},this.lease);const rows=Array.isArray(response.body)?response.body:[response.body],context={sourceId,endpointId,instrument,marketType:'usdt_perpetual',interval,fetchedAt:response.receivedAt,rawPayloadId,requestId:response.requestId,qualityState:'NORMAL'};const facts=rows.map(row=>normalizer(row,context));const saved=await this.repository.savePointFacts(table,facts,this.lease);this.endpointHealth.observation(endpointId,Math.max(0,...facts.map(x=>x.observedAt))||null);this.databaseWriteHealthy=true;return saved;}catch(error){this.databaseWriteHealthy=false;await this.recordWriteFailure(error,{sourceId,endpointId,requestId:response.requestId});throw error;}}
  async runBackfill(){this.requireLease();return this.backfillWorker.runOne(`${this.config.collectorId}:backfill`,this.lease,this.abortController.signal);}
  endpointSnapshots(){return this.endpointHealth.snapshots(this.adapter.client?.breakerStates?.()||{});}
  health(){const endpoints=this.endpointSnapshots(),latestSuccessAt=Math.max(0,...endpoints.map(x=>x.latestSuccessAt||0))||null,latestData=Math.max(0,...endpoints.map(x=>x.latestDataObservationAt||0))||null,failures=Math.max(0,...endpoints.map(x=>x.consecutiveFailures||0));return evaluateHealth({databaseAvailable:this.databaseAvailable,databaseWriteHealthy:this.databaseWriteHealthy,leaseValid:!!this.lease&&!this.leaseLost,serverTimeAvailable:this.lastServerTime?.ok??false,clockOffsetMs:this.lastServerTime?.clockOffsetMs,maxClockOffsetMs:this.config.maxClockOffsetMs,latestAttemptAt:Math.max(0,...endpoints.map(x=>x.latestAttemptAt||0))||null,latestSuccessAt,latestDataObservationAt:latestData,dataAgeMs:latestData?this.now()-latestData:null,expectedFrequencyMs:30000,unresolvedGapCount:this.workCounts.unresolved||0,pendingBackfillCount:this.workCounts.pending||0,consecutiveFailures:failures,consecutiveSuccesses:Math.min(...endpoints.map(x=>x.consecutiveSuccesses||0)),circuitOpen:endpoints.some(x=>x.circuitState==='OPEN'),rateLimited:endpoints.some(x=>x.rateLimited),partialEndpointFailure:endpoints.some(x=>x.consecutiveFailures>0||!x.latestSuccessAt),recovering:endpoints.some(x=>x.recovering),endpointHealth:endpoints,blockedReason:this.blockedReason},this.now());}
  async persistHealth(){const overall=this.health();await this.repository.saveHealth(overall,this.lease);for(const e of overall.endpointHealth){const stale=Number.isFinite(e.dataAgeMs)&&e.dataAgeMs>e.expectedFrequencyMs*3;const state=e.circuitState==='OPEN'||e.consecutiveFailures>=5||stale?'DEGRADED':e.recovering?'RECOVERING':e.consecutiveFailures>0?'WARNING':e.latestSuccessAt?'HEALTHY':'DEGRADED';await this.repository.saveHealth({...overall,...e,sourceId:e.endpointId.startsWith('binance-spot')?'binance-spot-rest':'binance-usdt-futures-rest',datasetKey:`endpoint:${e.endpointId}`,state},this.lease);}}
  async readiness(){try{const db=await this.repository.readinessSnapshot(),health=this.health(),leaseValid=!!this.lease&&!this.leaseLost&&this.running,timeValid=this.lastServerTime?.ok===true,grace=this.config.freshnessGraceMultiplier||3,freshness=Object.fromEntries(INTERVALS.map(interval=>{const observed=Number(db.latest_data_by_interval?.[interval]??(interval==='15m'?db.latest_data_ms:null));const thresholdMs=freshnessThresholdMs(interval,grace);return[interval,{observedAt:observed||null,expectedFrequencyMs:freshnessThresholdMs(interval,1),graceMultiplier:grace,thresholdMs,fresh:Number.isFinite(observed)&&this.now()-observed<=thresholdMs}];})),fresh=Object.values(freshness).every(x=>x.fresh),ok=db.database.ok&&db.migrations.ok&&leaseValid&&timeValid&&fresh&&health.state!=='BLOCKED';return{ok,status:ok?health.state:'BLOCKED',checks:{database:db.database.ok,migrations:db.migrations.ok,lease:leaseValid,serverTime:timeValid,coreDataFresh:fresh,freshness},health};}catch(error){this.databaseAvailable=false;return{ok:false,status:'BLOCKED',checks:{database:false,migrations:false,lease:!!this.lease&&!this.leaseLost,serverTime:this.lastServerTime?.ok===true,coreDataFresh:false},errorCode:'READINESS_CHECK_FAILED'};}}
  status(){return{running:this.running,collectorId:this.config.collectorId,startedAt:this.startedAt,lease:this.lease?{leaseName:this.lease.leaseName,holderId:this.lease.holderId,fencingToken:this.lease.fencingToken,expiresAt:this.lease.expiresAt}:null,lastRun:this.lastRun,health:this.health()};}
  async stop({closeRepository=true}={}){this.running=false;this.clearSchedulers();this.abortController.abort('shutdown');await Promise.allSettled([...this.inflight]);if(closeRepository)await this.repository.close();}
}
