import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createPgPool, PostgresRepository } from '../../src/db/postgres.js';
import { runMigrations } from '../../src/db/migrate.js';
import { CollectorService } from '../../src/collector/service.js';
import { canonicalJsonHash } from '../../src/domain/hash.js';
import { sha256 } from '../../src/domain/hash.js';
import { normalizeFunding, normalizeLongShort, normalizeOpenInterest, normalizeTakerFlow } from '../../src/domain/normalize.js';

const url=process.env.TEST_DATABASE_URL;
const enabled=Boolean(url);
const pgtest=enabled?test:test.skip;
const NOW=1_784_000_000_000, OPEN=NOW-1_800_000;
let pool,repo,lease,collector;
const response=(body,endpointId='binance-spot-klines')=>({body,requestId:randomUUID(),status:200,headers:{'content-type':'application/json','x-endpoint':endpointId},startedAt:NOW-2,receivedAt:NOW,roundTripMs:2});
const bar=(open=OPEN,close='100')=>[open,'100','102','99',close,'10',open+899999,'1000',10,'5','500','0'];
const meta=(endpointId='binance-spot-klines',sourceId='binance-spot-rest')=>({sourceId,endpointId,schemaVersion:'v1.4a-server-schema-1',qualityState:'NORMAL'});

if(enabled){
  before(async()=>{const parsed=new URL(url);if(!/test|ci|v14a/i.test(parsed.pathname))throw new Error('TEST_DATABASE_URL must name an isolated test/ci database');pool=await createPgPool({databaseUrl:url,dbSsl:false});await runMigrations(pool,'down');await runMigrations(pool,'up');repo=new PostgresRepository(pool);lease=await repo.acquireLease('primary-collector','pg-integration',60_000);collector=new CollectorService({adapter:{client:{breakerStates:()=>({})}},repository:repo,config:{collectorId:'pg-integration',leaseTtlMs:60_000,maxClockOffsetMs:5000},now:()=>NOW,logger:{error(){}}});collector.lease=lease;collector.running=true;});
  after(async()=>{await pool?.end();});
}

pgtest('迁移支持up/down/up、并发锁、19张表和版本完整',async()=>{assert.deepEqual((await repo.migrationStatus()).versions,['001','002']);await runMigrations(pool,'down');await Promise.all([runMigrations(pool,'up'),runMigrations(pool,'up')]);assert.equal((await repo.migrationStatus()).ok,true);const tables=await pool.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public'");assert.equal(tables.rows.length,19);repo=new PostgresRepository(pool);lease=await repo.acquireLease('primary-collector','pg-integration',60_000);collector.repository=repo;collector.lease=lease;});

pgtest('saveRaw真实JSONB支持对象、数组、null、布尔、数字和字符串',async()=>{for(const body of [{b:2,a:1},[1,{a:true}],null,false,12.5,'文本']){const r=response(body);const id=await repo.saveRaw(r,{...meta(),contentHash:canonicalJsonHash(body)},lease);const stored=(await pool.query('SELECT payload,response_headers FROM raw_payloads WHERE raw_payload_id=$1',[id])).rows[0];assert.deepEqual(stored.payload,body);assert.equal(stored.response_headers['x-endpoint'],'binance-spot-klines');}});

pgtest('saveRaw拒绝不可序列化值且不形成半成品',async()=>{const beforeCount=Number((await pool.query('SELECT count(*) FROM raw_payloads')).rows[0].count);for(const body of [undefined,1n,(()=>{const x={};x.self=x;return x;})()])await assert.rejects(repo.saveRaw(response(body),meta(),lease));assert.equal(Number((await pool.query('SELECT count(*) FROM raw_payloads')).rows[0].count),beforeCount);});

pgtest('生产CollectorService写入现货与永续数组K线及provisional追踪',async()=>{for(const [sourceId,endpointId,marketType] of [['binance-spot-rest','binance-spot-klines','spot'],['binance-usdt-futures-rest','binance-futures-klines','usdt_perpetual']]){const closed=response([bar()],endpointId);const saved=await collector.collectBarsFromResponse({response:closed,sourceId,endpointId,instrument:'ETHUSDT',marketType,interval:'15m',serverTime:NOW});assert.equal(saved.formal,1);const open=response([bar(NOW-1000)],endpointId);const provisional=await collector.collectBarsFromResponse({response:open,sourceId,endpointId,instrument:'ETHUSDT',marketType,interval:'15m',serverTime:NOW});assert.equal(provisional.provisional,1);}assert.equal(Number((await pool.query('SELECT count(*) FROM market_bars')).rows[0].count),2);assert.equal(Number((await pool.query('SELECT count(*) FROM provisional_market_bars')).rows[0].count),2);});

pgtest('生产CollectorService写入资金费率、OI、多空比和主动买卖量',async()=>{const cases=[['funding_rates','binance-futures-funding-rate',[{symbol:'ETHUSDT',fundingTime:NOW-1000,fundingRate:'-0.0001',markPrice:'100'}],normalizeFunding,null],['open_interest','binance-futures-open-interest',{symbol:'ETHUSDT',time:NOW-1000,openInterest:'10'},normalizeOpenInterest,null],['long_short_ratios','binance-futures-global-long-short',[{symbol:'ETHUSDT',timestamp:NOW-1000,longShortRatio:'1',longAccount:'0.5',shortAccount:'0.5'}],normalizeLongShort,'15m'],['taker_flow','binance-futures-taker-flow',[{timestamp:NOW-1000,buySellRatio:'1',buyVol:'1',sellVol:'1'}],normalizeTakerFlow,'15m']];for(const [table,endpointId,body,normalizer,interval] of cases){const saved=await collector.collectPoint(table,'ETHUSDT',endpointId,async()=>response(body,endpointId),normalizer,interval);assert.equal(saved.inserted,1);assert.equal(Number((await pool.query(`SELECT count(*) FROM ${table}`)).rows[0].count),1);}});

pgtest('四类点状事实同自然键内容变化均追加revision和事件',async()=>{const cases=[['funding_rates','binance-futures-funding-rate',[{symbol:'ETHUSDT',fundingTime:NOW-1000,fundingRate:'0.0002',markPrice:'100'}],normalizeFunding,null],['open_interest','binance-futures-open-interest',{symbol:'ETHUSDT',time:NOW-1000,openInterest:'11'},normalizeOpenInterest,null],['long_short_ratios','binance-futures-global-long-short',[{symbol:'ETHUSDT',timestamp:NOW-1000,longShortRatio:'1.2',longAccount:'0.6',shortAccount:'0.4'}],normalizeLongShort,'15m'],['taker_flow','binance-futures-taker-flow',[{timestamp:NOW-1000,buySellRatio:'1.2',buyVol:'1.2',sellVol:'1'}],normalizeTakerFlow,'15m']];for(const [table,endpointId,body,normalizer,interval] of cases){const saved=await collector.collectPoint(table,'ETHUSDT',endpointId,async()=>response(body,endpointId),normalizer,interval);assert.equal(saved.revised,1);const versions=await pool.query(`SELECT revision_number FROM ${table} WHERE instrument='ETHUSDT' ORDER BY revision_number`);assert.deepEqual(versions.rows.map(x=>x.revision_number),[0,1]);assert.equal(Number((await pool.query('SELECT count(*) FROM data_revision_events WHERE dataset=$1',[table])).rows[0].count),1);}});

pgtest('同自然键相同内容DEDUPED、不同内容原子REVISED并追加事件',async()=>{const first=response([bar(OPEN,'100')]);await collector.collectBarsFromResponse({response:first,sourceId:'binance-spot-rest',instrument:'BTCUSDT',marketType:'spot',interval:'15m',serverTime:NOW});const duplicate={...first,requestId:randomUUID()};assert.equal((await collector.collectBarsFromResponse({response:duplicate,sourceId:'binance-spot-rest',instrument:'BTCUSDT',marketType:'spot',interval:'15m',serverTime:NOW})).deduped,1);const revised=response([bar(OPEN,'101')]);assert.equal((await collector.collectBarsFromResponse({response:revised,sourceId:'binance-spot-rest',instrument:'BTCUSDT',marketType:'spot',interval:'15m',serverTime:NOW})).revised,1);const versions=await pool.query("SELECT revision_number,close::text FROM market_bars WHERE instrument='BTCUSDT' ORDER BY revision_number");assert.deepEqual(versions.rows.map(x=>x.revision_number),[0,1]);assert.equal(Number((await pool.query("SELECT count(*) FROM data_revision_events WHERE dataset='market_bars'")).rows[0].count),1);});

pgtest('修订事件写入失败会回滚新事实避免孤儿vintage',async()=>{const open=OPEN-900000,closeTime=open+899999;const first=response([bar(open,'100')]);await collector.collectBarsFromResponse({response:first,sourceId:'binance-spot-rest',instrument:'ETHUSDT',marketType:'spot',interval:'15m',serverTime:NOW});const previousVintageId=`ETHUSDT-spot-15m-${closeTime}-rev0`,newVintageId=`ETHUSDT-spot-15m-${closeTime}-rev1`,naturalKey=`market_bars:binance-spot-rest:spot:ETHUSDT:15m:${open}`,eventId=`revision:${sha256({dataset:'market_bars',naturalKey,previousVintageId,newVintageId})}`;await pool.query(`INSERT INTO data_revision_events(revision_event_id,dataset,natural_key,previous_vintage_id,new_vintage_id,detected_at,content_hash) VALUES($1,'test','{}','occupied-a','occupied-b',clock_timestamp(),$2)`,[eventId,'0'.repeat(64)]);await assert.rejects(collector.collectBarsFromResponse({response:response([bar(open,'101')]),sourceId:'binance-spot-rest',instrument:'ETHUSDT',marketType:'spot',interval:'15m',serverTime:NOW}),error=>error.code==='23505');const rows=await pool.query('SELECT revision_number FROM market_bars WHERE instrument=$1 AND open_time=to_timestamp($2/1000.0)',['ETHUSDT',open]);assert.deepEqual(rows.rows.map(x=>x.revision_number),[0]);await pool.query('DELETE FROM data_revision_events WHERE revision_event_id=$1',[eventId]);});

pgtest('数据库时间红线拒绝四类点状事实乱序UPDATE并完整回滚',async()=>{for(const table of ['funding_rates','open_interest','long_short_ratios','taker_flow']){const before=await pool.query(`SELECT first_available_at FROM ${table} WHERE instrument='ETHUSDT' ORDER BY revision_number LIMIT 1`);await assert.rejects(pool.query(`UPDATE ${table} SET first_available_at=available_at-interval '1 second' WHERE instrument='ETHUSDT'`),error=>error.code==='23514');const afterRow=await pool.query(`SELECT first_available_at FROM ${table} WHERE instrument='ETHUSDT' ORDER BY revision_number LIMIT 1`);assert.equal(afterRow.rows[0].first_available_at.getTime(),before.rows[0].first_available_at.getTime());}});

pgtest('gap与backfill使用SKIP LOCKED只允许一个worker领取',async()=>{const gap={gapId:'pg-gap',sourceId:'binance-spot-rest',instrument:'ETHUSDT',marketType:'spot',interval:'15m',startOpenTime:NOW-900000,endOpenTime:NOW-900000,missingCount:1};const saved=(await repo.saveGaps([gap],lease))[0];await repo.createBackfill(saved,lease);const [a,b]=await Promise.all([repo.claimBackfill('worker-a',lease),repo.claimBackfill('worker-b',lease)]);assert.equal([a,b].filter(Boolean).length,1);await repo.finishBackfill((a||b).job_id,{ok:true},lease);});

pgtest('旧token过期后数据库原子拒写，新token成功，并发租约只有一主',async()=>{await pool.query("UPDATE collector_leases SET expires_at=clock_timestamp()-interval '1 second' WHERE lease_name='primary-collector'");const next=await repo.acquireLease('primary-collector','pg-integration-b',60_000);await assert.rejects(repo.saveRaw(response({old:true}),meta(),lease),error=>error.code==='FENCING_TOKEN_REJECTED');await repo.saveRaw(response({new:true}),meta(),next);const concurrent=await Promise.all([repo.acquireLease('race','a',60_000),repo.acquireLease('race','b',60_000)]);assert.equal(concurrent.filter(Boolean).length,1);lease=next;collector.lease=next;});

pgtest('raw_payloads在数据库层拒绝UPDATE和DELETE',async()=>{const id=await repo.saveRaw(response({immutable:true}),meta(),lease);await assert.rejects(pool.query('UPDATE raw_payloads SET quality_state=$2 WHERE raw_payload_id=$1',[id,'BAD']),error=>error.code==='55000');await assert.rejects(pool.query('DELETE FROM raw_payloads WHERE raw_payload_id=$1',[id]),error=>error.code==='55000');});

pgtest('数据库断开后实时readiness探针失败而非返回HEALTHY',async()=>{await pool.end();await assert.rejects(repo.readinessSnapshot());pool=null;});
