import test,{after,before} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createPgPool,PostgresRepository} from '../../src/db/postgres.js';
import {canonicalJsonHash} from '../../src/domain/hash.js';
import {normalizeFunding,normalizeKlines} from '../../src/domain/normalize.js';
import {FEATURE_ALGORITHM_VERSION,FEATURE_SET_VERSION} from '../../src/features/feature-version.js';
import {runHistoricalFeatureBackfill,validateHistoricalFeatureInputs} from '../../src/features/historical-feature-backfill.js';
import {findExactFeatureForReplay} from '../../src/validation-replay/replay-generator.js';

const isAllowedTestDatabaseName=name=>name==='eth_alpha_v14d_test'||/^eth_alpha_v14d_test_[a-z0-9_]+$/.test(name)||/^eth_alpha_v14d_round[a-z0-9_]*$/.test(name);
function validateTestDatabaseUrl(value){if(!value)return{ok:false,errorCode:'TEST_DATABASE_URL_REQUIRED'};try{const parsed=new URL(value),databaseName=decodeURIComponent(parsed.pathname.slice(1)),expectedUser=decodeURIComponent(parsed.username);if(!['postgres:','postgresql:'].includes(parsed.protocol))return{ok:false,errorCode:'TEST_DATABASE_PROTOCOL_REJECTED'};if(!databaseName)return{ok:false,errorCode:'TEST_DATABASE_NAME_REQUIRED'};if(databaseName==='eth_alpha'||!isAllowedTestDatabaseName(databaseName))return{ok:false,errorCode:'TEST_DATABASE_NAME_REJECTED'};if(!expectedUser)return{ok:false,errorCode:'TEST_DATABASE_USER_REQUIRED'};return{ok:true,url:value,databaseName,expectedUser};}catch{return{ok:false,errorCode:'TEST_DATABASE_URL_INVALID'};}}
const databaseGate=validateTestDatabaseUrl(process.env.TEST_DATABASE_URL),url=databaseGate.ok?databaseGate.url:null,enabled=databaseGate.ok,pgtest=enabled?test:test.skip;
const START=Date.parse('2025-02-03T00:00:00.000Z'),END=START+4*3600_000-1,EXEC=Date.parse('2025-03-01T00:00:00.000Z'),SOURCE='binance-spot-rest',ENDPOINT='binance-spot-klines',DATASET=`v1.4d-sha256-${'b'.repeat(64)}`,LEASE_NAME=`historical-feature-fixture-${process.pid}`,HOLDER_ID=`historical-feature-it-${process.pid}`;
let pool,repo,lease;
const rawPayloadIds=[];
const opts=(dryRun=false)=>({symbol:'ETHUSDT',from:new Date(START).toISOString(),to:new Date(START+4*3600_000).toISOString(),interval:'15m',featureVersion:FEATURE_SET_VERSION,algorithmVersion:FEATURE_ALGORITHM_VERSION,datasetVersion:DATASET,dryRun,batchSize:5,resumeAfter:null});
async function seed(instrument,interval,step){const rows=Array.from({length:40},(_,i)=>{const close=END-(39-i)*step,open=close-step+1,p=(instrument==='BTCUSDT'?60000:1800)+i;return[open,String(p-1),String(p+2),String(p-2),String(p),String(100+i),close,String((100+i)*p),10,String((100+i)*.55),'0','0'];}),response={body:rows,requestId:randomUUID(),status:200,headers:{},startedAt:EXEC-2,receivedAt:EXEC-1},endpointId=ENDPOINT,rawPayloadId=await repo.saveRaw(response,{sourceId:SOURCE,endpointId,contentHash:canonicalJsonHash(rows),schemaVersion:'v1.4a-server-schema-1',qualityState:'NORMAL'},lease);rawPayloadIds.push(rawPayloadId);const normalized=normalizeKlines({rows,sourceId:SOURCE,endpointId,instrument,marketType:'spot',interval,serverTime:EXEC,fetchedAt:EXEC-1,rawPayloadId,requestId:response.requestId});const saved=await repo.upsertMarketBars(normalized.formal,lease);assert.equal(saved.rejected,0);}
async function seedFunding(){const body=[{symbol:'ETHUSDT',fundingTime:END-1,fundingRate:'0.0001',markPrice:'1839'}],response={body,requestId:randomUUID(),status:200,headers:{},startedAt:END-1,receivedAt:END},sourceId='binance-usdt-futures-rest',endpointId='binance-futures-funding-rate',rawPayloadId=await repo.saveRaw(response,{sourceId,endpointId,contentHash:canonicalJsonHash(body),schemaVersion:'v1.4a-server-schema-1',qualityState:'NORMAL'},lease);rawPayloadIds.push(rawPayloadId);const facts=body.map(row=>normalizeFunding(row,{sourceId,endpointId,instrument:'ETHUSDT',marketType:'usdt_perpetual',interval:null,fetchedAt:END,rawPayloadId,requestId:response.requestId,qualityState:'NORMAL'}));const saved=await repo.savePointFacts('funding_rates',facts,lease);assert.equal(saved.rejected,0);}
async function counts(){return(await pool.query(`SELECT (SELECT count(*)::int FROM feature_sets) sets,(SELECT count(*)::int FROM feature_generation_runs) runs,(SELECT count(*)::int FROM feature_records) records,(SELECT count(*)::int FROM feature_source_refs) refs,(SELECT count(*)::int FROM feature_quality_events) quality`)).rows[0];}
async function cleanupFixture(){if(!pool)return;let cleanupError;try{await pool.query(`DELETE FROM feature_quality_events WHERE feature_record_id IN (SELECT feature_record_id FROM feature_records WHERE source_dataset_version=$1)`,[DATASET]);await pool.query(`DELETE FROM feature_source_refs WHERE feature_record_id IN (SELECT feature_record_id FROM feature_records WHERE source_dataset_version=$1)`,[DATASET]);await pool.query('DELETE FROM feature_records WHERE source_dataset_version=$1',[DATASET]);await pool.query('DELETE FROM feature_generation_runs WHERE symbol=$1 AND range_start=to_timestamp($2/1000.0)', ['ETHUSDT',START]);if(rawPayloadIds.length){await pool.query('DELETE FROM funding_rates WHERE raw_payload_id=ANY($1::uuid[])',[rawPayloadIds]);await pool.query('DELETE FROM market_bars WHERE raw_payload_id=ANY($1::uuid[])',[rawPayloadIds]);}}catch(error){cleanupError=error;}try{await repo?.releaseLease(lease);}catch(error){cleanupError||=error;}await pool.query('DELETE FROM collector_leases WHERE lease_name=$1 AND holder_id=$2',[LEASE_NAME,HOLDER_ID]);assert.equal((await pool.query('SELECT count(*)::int n FROM collector_leases WHERE lease_name=$1 AND holder_id=$2',[LEASE_NAME,HOLDER_ID])).rows[0].n,0);if(cleanupError)throw cleanupError;}
test('PostgreSQL测试数据库URL门禁只接受隔离V1.4D数据库',()=>{for(const name of ['eth_alpha_v14d_test','eth_alpha_v14d_test_round4','eth_alpha_v14d_round4_123456'])assert.deepEqual(validateTestDatabaseUrl(`postgresql://v14d_test:secret@localhost/${name}`),{ok:true,url:`postgresql://v14d_test:secret@localhost/${name}`,databaseName:name,expectedUser:'v14d_test'});for(const value of ['postgresql://v14d_test:secret@localhost/eth_alpha','postgresql://v14d_test:secret@localhost/postgres','postgresql://v14d_test:secret@localhost/','not-a-url','postgresql://v14d_test:secret@localhost/arbitrary_database'])assert.equal(validateTestDatabaseUrl(value).ok,false);});
if(enabled){before(async()=>{pool=await createPgPool({databaseUrl:url,dbSsl:false});try{const identity=(await pool.query('SELECT current_database() AS database,current_user AS "currentUser"')).rows[0];assert.equal(identity.database,databaseGate.databaseName);assert.equal(isAllowedTestDatabaseName(identity.database),true);assert.notEqual(identity.database,'eth_alpha');assert.equal(identity.currentUser,databaseGate.expectedUser);for(const version of ['001','002','003','004','005'])assert.equal((await pool.query('SELECT 1 FROM schema_migrations WHERE version=$1',[version])).rowCount,1);assert.equal((await pool.query('SELECT 1 FROM source_registry s JOIN source_endpoint_registry e ON e.source_id=s.source_id WHERE s.source_id=$1 AND e.endpoint_id=$2 AND e.enabled=true',[SOURCE,ENDPOINT])).rowCount,1);repo=new PostgresRepository(pool);repo.verifyHistoricalFeatureDataset=async()=>({datasetVersion:DATASET,symbol:'ETHUSDT',intervals:['15m','1h','4h'],dataFrom:END-50*14400000,dataTo:START+4*3600_000,researchAvailabilityRuleVersion:'v1.4d-research-availability-1'});lease=await repo.acquireLease(LEASE_NAME,HOLDER_ID,120000);assert.ok(lease);for(const [symbol,interval,step] of [['ETHUSDT','15m',900000],['ETHUSDT','1h',3600000],['ETHUSDT','4h',14400000],['BTCUSDT','15m',900000]])await seed(symbol,interval,step);await seedFunding();}catch(error){try{await cleanupFixture();}finally{await pool.end();pool=undefined;}throw error;}});after(async()=>{if(pool)try{await cleanupFixture();}finally{await pool.end();}});}

pgtest('真实PostgreSQL时间映射、目标点门禁与dry-run五张feature表逐表零写入',async()=>{const input=await repo.loadHistoricalFeatureInputs({targetBarCloseTime:END,historicalAsOfTime:END,replayNowMs:EXEC});for(const row of [...input.eth15,...input.eth1h,...input.eth4h,...input.btc15])for(const field of ['openTime','closeTime','publishedAt','availableAt','fetchedAt','researchAvailabilityAt','operationalAvailableAt','operationalFetchedAt']){assert.equal(typeof row[field],'number',field);assert.equal(Number.isFinite(row[field]),true,field);}assert.equal(input.funding.length,1);for(const field of ['observedAt','publishedAt','availableAt','firstAvailableAt','fetchedAt']){assert.equal(typeof input.funding[0][field],'number',field);assert.equal(Number.isFinite(input.funding[0][field]),true,field);}assert.equal(validateHistoricalFeatureInputs(input,END),true);assert.throws(()=>validateHistoricalFeatureInputs({...input,eth15:input.eth15.slice(0,-1)},END),error=>error.code==='TARGET_BAR_MISSING');const beforeCounts=await counts(),out=await runHistoricalFeatureBackfill({repository:repo,options:opts(true),executionTime:EXEC});assert.equal(out.generatedPoints,1);assert.deepEqual(await counts(),beforeCounts);});
pgtest('真实唯一键与事务：首次插入、replay可消费、相同输入幂等、冲突不覆盖',async()=>{const first=await runHistoricalFeatureBackfill({repository:repo,options:opts(false),executionTime:EXEC});assert.equal(first.generatedPoints,1);const stored=await pool.query(`SELECT feature_record_id,content_hash,as_of_time,generated_at,algorithm_version,source_dataset_version,generation_run_id FROM feature_records WHERE source_dataset_version=$1`,[DATASET]);assert.equal(stored.rowCount,1);assert.equal(stored.rows[0].as_of_time.getTime(),END);assert.equal(stored.rows[0].generated_at.getTime(),EXEC);const replayFeature=await findExactFeatureForReplay(pool,{instrument:'ETHUSDT',targetBarCloseTime:END,historicalAsOfTime:END});assert.equal(String(replayFeature.feature_record_id),String(stored.rows[0].feature_record_id));const second=await runHistoricalFeatureBackfill({repository:repo,options:opts(false),executionTime:EXEC+1});assert.equal(second.alreadyPresent,1);assert.equal((await pool.query('SELECT count(*)::int n FROM feature_records WHERE source_dataset_version=$1',[DATASET])).rows[0].n,1);
  const conflictingHash='c'.repeat(64);await pool.query('UPDATE feature_records SET content_hash=$1 WHERE feature_record_id=$2',[conflictingHash,stored.rows[0].feature_record_id]);await assert.rejects(()=>runHistoricalFeatureBackfill({repository:repo,options:opts(false),executionTime:EXEC+2}),e=>e.code==='HISTORICAL_FEATURE_CONFLICT');const unchanged=await pool.query('SELECT count(*)::int n,min(content_hash) hash FROM feature_records WHERE source_dataset_version=$1',[DATASET]);assert.equal(unchanged.rows[0].n,1);assert.equal(unchanged.rows[0].hash,conflictingHash);});
