import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { sha256 } from '../../src/domain/hash.js';
import { MemoryRepository } from '../../src/db/memory.js';
import { PostgresRepository } from '../../src/db/postgres.js';
import { FeatureEngine } from '../../src/features/feature-engine.js';
import { FEATURE_ALGORITHM_VERSION, FEATURE_SET_VERSION } from '../../src/features/feature-version.js';
import { enumerateHistoricalFeaturePoints, exitCodeForHistoricalBackfill, runHistoricalFeatureBackfill, validateHistoricalBackfillOptions, validateHistoricalFeatureInputs } from '../../src/features/historical-feature-backfill.js';
import { parseHistoricalBackfillArgs, sanitizeHistoricalBackfillError, main } from '../../src/features/historical-feature-backfill-cli.js';
import { enumerateRhythmPoints } from '../../src/validation-replay/cli-entry.js';

const START=Date.parse('2026-07-22T00:00:00.000Z'),REF=START+4*3600_000-1,EXEC=Date.parse('2026-08-01T00:00:00.000Z'),DATASET=`v1.4d-sha256-${'a'.repeat(64)}`;
const options=(extra={})=>({symbol:'ETHUSDT',from:new Date(START).toISOString(),to:new Date(START+4*3600_000).toISOString(),interval:'15m',featureVersion:FEATURE_SET_VERSION,algorithmVersion:FEATURE_ALGORITHM_VERSION,datasetVersion:DATASET,dryRun:false,batchSize:10,resumeAfter:null,...extra});
function makeBars({symbol,interval,step,count=80,end=REF,fetchedAt=EXEC-1}){return Array.from({length:count},(_,i)=>{const closeTime=end-(count-1-i)*step,price=(symbol==='BTCUSDT'?60000:1800)+i;return{sourceId:'fixture',endpointId:'fixture-bars',instrument:symbol,marketType:'spot',interval,openTime:closeTime-step,closeTime,open:String(price-1),high:String(price+2),low:String(price-2),close:String(price),volume:String(100+i),quoteVolume:String((100+i)*price),takerBuyBaseVolume:String(55+i),publishedAt:closeTime,availableAt:fetchedAt,firstAvailableAt:fetchedAt,fetchedAt,revisionNumber:0,vintageId:`${symbol}:${interval}:${closeTime}:rev0`,rawPayloadId:null,marketBarId:`${symbol}-${interval}-${closeTime}`,contentHash:sha256({symbol,interval,closeTime,price})};});}
function seededRepo(){const repo=new MemoryRepository();repo.bars=[...makeBars({symbol:'ETHUSDT',interval:'15m',step:900000}),...makeBars({symbol:'ETHUSDT',interval:'1h',step:3600000}),...makeBars({symbol:'ETHUSDT',interval:'4h',step:14400000}),...makeBars({symbol:'BTCUSDT',interval:'15m',step:900000})];return repo;}

test('冻结节奏在7天窗口精确产生42点，from inclusive/to exclusive且不受本地时区影响',()=>{const from=START,to=Date.parse('2026-07-29T00:00:00.000Z'),points=enumerateHistoricalFeaturePoints({fromMs:from,toMs:to});assert.equal(points.length,42);assert.equal(points[0],from+4*3600_000-1);assert.equal(points.at(-1),to-1);assert.ok(points.every((x,i)=>x>=from&&x<to&&(i===0||x-points[i-1]===4*3600_000)));});
test('24H与72H使用同一底层reference feature时间键，72H节奏点是42点集合的子集',()=>{const to=Date.parse('2026-07-29T00:00:00.000Z'),features=new Set(enumerateHistoricalFeaturePoints({fromMs:START,toMs:to})),seventyTwo=enumerateRhythmPoints({from:START,to,horizon:'72h'});assert.ok(seventyTwo.length>0);assert.ok(seventyTwo.every(point=>features.has(point)));});
test('参数和版本fail closed，resume游标只保留其后的权威节奏点',()=>{assert.throws(()=>validateHistoricalBackfillOptions(options({from:'2026-07-22T00:01:00.000Z'})),e=>e.code==='UNALIGNED_UTC_RANGE');assert.throws(()=>validateHistoricalBackfillOptions(options({featureVersion:'wrong'})),e=>e.code==='FEATURE_VERSION_MISMATCH');assert.throws(()=>validateHistoricalBackfillOptions(options({datasetVersion:'short'})),e=>e.code==='DATASET_VERSION_INVALID');const effective=validateHistoricalBackfillOptions(options({to:new Date(START+12*3600_000).toISOString(),resumeAfter:new Date(REF+4*3600_000).toISOString()}));assert.deepEqual(enumerateHistoricalFeaturePoints(effective),[REF+8*3600_000]);});
test('manifest缺失/校验失败在首次持久化和输入读取前fail closed',async()=>{const repo=seededRepo();let loaded=false,started=false;repo.verifyHistoricalFeatureDataset=async()=>{throw Object.assign(new Error('missing'),{code:'DATASET_MANIFEST_NOT_FOUND'});};repo.loadHistoricalFeatureInputs=async()=>{loaded=true;};repo.startHistoricalFeatureRun=async()=>{started=true;};await assert.rejects(()=>runHistoricalFeatureBackfill({repository:repo,options:options(),executionTime:EXEC}),e=>e.code==='DATASET_MANIFEST_NOT_FOUND');assert.equal(loaded,false);assert.equal(started,false);assert.equal(repo.featureRecords.length,0);});
test('ETH-only manifest缺少BTCUSDT 15m治理成员时在计算与输入查询前fail closed',async()=>{const repo=seededRepo();let loaded=false;repo.verifyHistoricalFeatureDataset=async()=>({datasetVersion:DATASET,symbol:'ETHUSDT',intervals:['15m','1h','4h'],dependencies:['15m','1h','4h'].map(interval=>({symbol:'ETHUSDT',marketType:'spot',interval})),memberVintageIds:repo.bars.filter(x=>x.instrument==='ETHUSDT').map(x=>x.vintageId),dataFrom:START-100*14400000,dataTo:START+4*3600_000,fixedAsOf:START+4*3600_000-1,researchAvailabilityRuleVersion:'v1.4d-research-availability-1'});repo.loadHistoricalFeatureInputs=async()=>{loaded=true;};await assert.rejects(()=>runHistoricalFeatureBackfill({repository:repo,options:options({dryRun:true}),executionTime:EXEC}),e=>e.code==='DATASET_MANIFEST_DEPENDENCY_UNGOVERNED'&&e.missingDependencies.some(x=>x.symbol==='BTCUSDT'&&x.interval==='15m'));assert.equal(loaded,false);});
test('Manifest未列出的BTC vintage在计算前被拒绝，合法ETH/BTC血缘同时出现在输出',async()=>{const repo=seededRepo(),originalVerify=repo.verifyHistoricalFeatureDataset.bind(repo);repo.verifyHistoricalFeatureDataset=async args=>{const manifest=await originalVerify(args);return{...manifest,memberVintageIds:manifest.memberVintageIds.filter(id=>!id.startsWith('BTCUSDT:'))};};await assert.rejects(()=>runHistoricalFeatureBackfill({repository:repo,options:options({dryRun:true}),executionTime:EXEC}),e=>e.code==='SOURCE_NOT_IN_DATASET_MANIFEST'&&e.symbol==='BTCUSDT');const okRepo=seededRepo(),out=await runHistoricalFeatureBackfill({repository:okRepo,options:options({dryRun:true}),executionTime:EXEC}),refs=out.results[0].record.sourceVintageRefs;assert.ok(refs.some(ref=>ref.symbol==='ETHUSDT'));assert.ok(refs.some(ref=>ref.symbol==='BTCUSDT'));assert.ok(out.requiredDependencies.some(x=>x.symbol==='BTCUSDT'&&x.interval==='15m'));});
test('FeatureEngine.generateRange为每个目标显式使用自己的历史asOf而不是墙钟',async()=>{const calls=[],repository={listFeatureTargets:async()=>[{closeTime:REF},{closeTime:REF+900000}],loadFeatureInputs:async args=>{calls.push(args);throw Object.assign(new Error('stop'),{code:'EXPECTED'});}};await assert.rejects(()=>new FeatureEngine({repository,now:()=>EXEC}).generateRange({from:REF,to:REF+900000,dryRun:true}),e=>e.code==='EXPECTED');assert.equal(calls[0].asOfTime,REF);assert.notEqual(calls[0].asOfTime,EXEC);});
test('历史执行显式asOf、保留operational时间审计且dry-run逐表零写入',async()=>{const repo=seededRepo(),before={records:repo.featureRecords.length,quality:repo.featureQuality.length,runs:repo.featureRuns.length};const out=await runHistoricalFeatureBackfill({repository:repo,options:options({dryRun:true}),executionTime:EXEC});assert.equal(out.generatedPoints,1);assert.equal(out.results[0].status,'WOULD_GENERATE');assert.equal(out.results[0].referenceTime,REF);assert.deepEqual({records:repo.featureRecords.length,quality:repo.featureQuality.length,runs:repo.featureRuns.length},before);const record=out.results[0].record;assert.equal(record.asOfTime,REF);assert.equal(record.generatedAt,EXEC);assert.ok(record.sourceVintageRefs.some(ref=>ref.operationalAvailableAt===EXEC-1&&ref.operationalFetchedAt===EXEC-1));assert.ok(record.sourceVintageRefs.every(ref=>ref.sourceTime<=REF&&ref.availableAt<=REF));});
test('未来K线不会被读取，execution之后才fetched的K线导致精确缺口阻断',async()=>{const repo=seededRepo();repo.bars.push(...makeBars({symbol:'ETHUSDT',interval:'15m',step:900000,count:1,end:REF+900000}));const loaded=await repo.loadHistoricalFeatureInputs({targetBarCloseTime:REF,historicalAsOfTime:REF,replayNowMs:EXEC});assert.equal(loaded.eth15.at(-1).closeTime,REF);repo.bars.find(x=>x.instrument==='BTCUSDT'&&x.interval==='15m'&&x.closeTime===REF).fetchedAt=EXEC+1;await assert.rejects(()=>runHistoricalFeatureBackfill({repository:repo,options:options({dryRun:true}),executionTime:EXEC}),e=>e.code==='TARGET_BAR_MISSING'||e.code==='INPUT_WINDOW_INCOMPLETE');});
test('PostgreSQL历史输入映射只将epoch毫秒字段转为有限number',async()=>{const epoch=`${REF}.000000`,bar={marketBarId:'1',sourceId:'fixture',endpointId:'bars',instrument:'ETHUSDT',interval:'15m',openTime:`${REF-899999}.000000`,closeTime:epoch,operationalAvailableAt:epoch,operationalFetchedAt:epoch,revisionNumber:0,vintageId:'bar-vintage',rawPayloadId:'raw',contentHash:'a'.repeat(64)},fact={id:'1',sourceId:'fixture',endpointId:'facts',instrument:'ETHUSDT',interval:null,observedAt:epoch,publishedAt:epoch,availableAt:epoch,firstAvailableAt:epoch,fetchedAt:epoch,revisionNumber:0,vintageId:'fact-vintage',rawPayloadId:'raw',contentHash:'b'.repeat(64),raw:{funding_rate:'0.1'}},manifest={memberVintageIds:['bar-vintage']},pool={query:async sql=>({rows:sql.includes('FROM market_bars')?[bar]:[fact]})},loaded=await new PostgresRepository(pool).loadHistoricalFeatureInputs({targetBarCloseTime:REF,historicalAsOfTime:REF,replayNowMs:EXEC,manifest});for(const field of ['openTime','closeTime','publishedAt','availableAt','fetchedAt','researchAvailabilityAt','operationalAvailableAt','operationalFetchedAt']){assert.equal(typeof loaded.eth15[0][field],'number');assert.equal(Number.isFinite(loaded.eth15[0][field]),true);}for(const field of ['observedAt','publishedAt','availableAt','firstAvailableAt','fetchedAt']){assert.equal(typeof loaded.funding[0][field],'number');assert.equal(Number.isFinite(loaded.funding[0][field]),true);}assert.equal(loaded.funding[0].fundingRate,'0.1');const invalidPool={query:async sql=>({rows:sql.includes('FROM market_bars')?[{...bar,closeTime:'not-a-timestamp'}]:[fact]})};await assert.rejects(()=>new PostgresRepository(invalidPool).loadHistoricalFeatureInputs({targetBarCloseTime:REF,historicalAsOfTime:REF,replayNowMs:EXEC,manifest}),error=>error.code==='INVALID_DATABASE_TIMESTAMP'&&error.field==='closeTime');});
test('真实缺少referenceTime末根K线仍严格抛出TARGET_BAR_MISSING',async()=>{const repo=seededRepo(),input=await repo.loadHistoricalFeatureInputs({targetBarCloseTime:REF,historicalAsOfTime:REF,replayNowMs:EXEC});assert.throws(()=>validateHistoricalFeatureInputs({...input,eth15:input.eth15.slice(0,-1)},REF),error=>error.code==='TARGET_BAR_MISSING');});
test('点事实继续使用真实published/available/fetched as-of，晚到事实不会泄漏',async()=>{const repo=seededRepo(),base={sourceId:'fixture',endpointId:'facts',instrument:'ETHUSDT',interval:'15m',observedAt:REF-1,publishedAt:REF-1,availableAt:REF+1,firstAvailableAt:REF+1,fetchedAt:REF+1,revisionNumber:0,vintageId:'late-fact',contentHash:sha256('late-fact')};repo.facts.funding_rates.push({...base,fundingRate:'0.1'});const loaded=await repo.loadHistoricalFeatureInputs({targetBarCloseTime:REF,historicalAsOfTime:REF,replayNowMs:EXEC});assert.equal(loaded.funding.length,0);});
test('缺少ETH或BTC关键窗口均fail closed并包含symbol/interval/reference',async()=>{for(const symbol of ['ETHUSDT','BTCUSDT']){const repo=seededRepo();repo.bars=repo.bars.filter(x=>!(x.instrument===symbol&&x.interval==='15m'));await assert.rejects(()=>runHistoricalFeatureBackfill({repository:repo,options:options({dryRun:true}),executionTime:EXEC}),e=>e.code==='INPUT_WINDOW_INCOMPLETE'&&e.symbol===symbol&&e.interval==='15m'&&e.referenceTime===REF);}});
test('重复或乱序bar不会被排序掩盖',async()=>{const repo=seededRepo(),input=await repo.loadHistoricalFeatureInputs({targetBarCloseTime:REF,historicalAsOfTime:REF,replayNowMs:EXEC});for(const rows of [[...input.eth15.slice(0,-1),input.eth15.at(-1),input.eth15.at(-1)],[...input.eth15.slice(0,-2),input.eth15.at(-1),input.eth15.at(-2)]])assert.throws(()=>validateHistoricalFeatureInputs({...input,eth15:rows},REF),e=>e.code==='INPUT_BAR_ORDER_INVALID');});
test('正式写入可安全重跑：一致记录ALREADY_PRESENT，内容/vintage冲突不覆盖',async()=>{const repo=seededRepo(),first=await runHistoricalFeatureBackfill({repository:repo,options:options(),executionTime:EXEC});assert.equal(first.generatedPoints,1);const originalHash=repo.featureRecords[0].contentHash;const second=await runHistoricalFeatureBackfill({repository:repo,options:options(),executionTime:EXEC+1});assert.equal(second.alreadyPresent,1);assert.equal(repo.featureRecords.length,1);repo.bars.find(x=>x.instrument==='ETHUSDT'&&x.interval==='15m'&&x.closeTime===REF).close='9999';repo.bars.find(x=>x.instrument==='ETHUSDT'&&x.interval==='15m'&&x.closeTime===REF).contentHash=sha256('changed');await assert.rejects(()=>runHistoricalFeatureBackfill({repository:repo,options:options(),executionTime:EXEC+2}),e=>e.code==='HISTORICAL_FEATURE_CONFLICT');assert.equal(repo.featureRecords.length,1);assert.equal(repo.featureRecords[0].contentHash,originalHash);});
test('CLI参数、退出码和敏感连接目标契约明确',()=>{const parsed=parseHistoricalBackfillArgs(['--symbol','ETHUSDT','--from',new Date(REF).toISOString(),'--to',new Date(REF+1).toISOString(),'--interval','15m','--feature-version',FEATURE_SET_VERSION,'--algorithm-version',FEATURE_ALGORITHM_VERSION,'--dataset-version',DATASET,'--dry-run','--batch-size','5']);assert.equal(parsed.dryRun,true);assert.equal(parsed.batchSize,5);assert.equal(exitCodeForHistoricalBackfill(),0);assert.equal(exitCodeForHistoricalBackfill({code:'INVALID_ARGUMENT'}),2);assert.equal(exitCodeForHistoricalBackfill({code:'INPUT_WINDOW_INCOMPLETE'}),3);assert.equal(exitCodeForHistoricalBackfill({code:'HISTORICAL_FEATURE_CONFLICT'}),4);assert.equal(exitCodeForHistoricalBackfill({code:'08006'}),5);assert.equal(exitCodeForHistoricalBackfill({code:'DATABASE_URL_REQUIRED'}),5);const redacted=sanitizeHistoricalBackfillError('postgresql://alice:secret@db/x password=hunter2 token=abc');assert.doesNotMatch(redacted,/alice|secret|hunter2|abc/);});
test('历史持久化路径物理独立于生产collector lease',async()=>{const source=await readFile(new URL('../../src/db/postgres.js',import.meta.url),'utf8'),section=source.slice(source.indexOf('async historicalFeatureTransaction'),source.indexOf('async listFeatureTargets'));assert.doesNotMatch(section,/collector_leases|assertLease|acquireLease|releaseLease/);assert.match(section,/BEGIN/);assert.match(section,/ROLLBACK/);});

// 回归测试：main()改为委托research-database-guard.js之后，既有的TEST_DATABASE_URL契约（只读TEST_DATABASE_URL、
// 不接受通用DATABASE_URL回退、格式/库名/身份校验、对应错误码）必须逐条保持不变。createPgPool通过main()
// 既有的options对象新增的可选createPgPool字段注入，不需要真实PostgreSQL，且不修改main()的CLI参数/环境变量约定。
const VALID_ARGV = ['--symbol', 'ETHUSDT', '--from', new Date(START).toISOString(), '--to', new Date(START + 4 * 3600_000).toISOString(), '--interval', '15m', '--feature-version', FEATURE_SET_VERSION, '--algorithm-version', FEATURE_ALGORITHM_VERSION, '--dataset-version', DATASET, '--dry-run'];

test('main()（回归）：缺失TEST_DATABASE_URL时DATABASE_URL_REQUIRED，且从不建立数据库连接', async () => {
  let called = false;
  const exitCode = await main(VALID_ARGV, {}, { stdout: () => {}, stderr: () => {}, createPgPool: async () => { called = true; return { query: async () => ({ rows: [] }), end: async () => {} }; } });
  assert.equal(exitCode, 5);
  assert.equal(called, false);
});

test('main()（回归）：TEST_DATABASE_URL格式非法时拒绝，不建立连接', async () => {
  let called = false;
  const exitCode = await main(VALID_ARGV, { TEST_DATABASE_URL: 'not-a-url' }, { stdout: () => {}, stderr: () => {}, createPgPool: async () => { called = true; return { query: async () => ({ rows: [] }), end: async () => {} }; } });
  assert.equal(exitCode, 5);
  assert.equal(called, false);
});

test('main()（回归）：TEST_DATABASE_URL指向生产eth_alpha时拒绝，从不建立数据库连接', async () => {
  let called = false;
  const exitCode = await main(VALID_ARGV, { TEST_DATABASE_URL: 'postgresql://u:p@127.0.0.1:5432/eth_alpha' }, { stdout: () => {}, stderr: () => {}, createPgPool: async () => { called = true; return { query: async () => ({ rows: [] }), end: async () => {} }; } });
  assert.equal(exitCode, 5);
  assert.equal(called, false);
});

test('main()（回归）：TEST_DATABASE_URL指向eth_alpha_v14d_test但current_database()返回其他库名时拒绝，且关闭连接、只发起一次身份核验查询', async () => {
  const calls = { query: 0, end: 0 };
  const pool = { async query() { calls.query += 1; return { rows: [{ database: 'eth_alpha' }] }; }, async end() { calls.end += 1; } };
  const exitCode = await main(VALID_ARGV, { TEST_DATABASE_URL: 'postgresql://u:p@127.0.0.1:5432/eth_alpha_v14d_test' }, { stdout: () => {}, stderr: () => {}, createPgPool: async () => pool });
  assert.equal(exitCode, 5);
  assert.equal(calls.query, 1);
  assert.equal(calls.end, 1);
});

test('main()（回归）：TEST_DATABASE_URL指向eth_alpha_v14d_test且身份核验一致时，保护通过，真正越过guard进入回填业务逻辑（用哨兵错误证明）', async () => {
  let queryCount = 0;
  const pool = {
    async query() {
      queryCount += 1;
      if (queryCount === 1) return { rows: [{ database: 'eth_alpha_v14d_test' }] };
      throw Object.assign(new Error('SENTINEL_PAST_GUARD'), { code: 'SENTINEL_PAST_GUARD' });
    },
    async end() {}
  };
  const exitCode = await main(VALID_ARGV, { TEST_DATABASE_URL: 'postgresql://u:p@127.0.0.1:5432/eth_alpha_v14d_test' }, { stdout: () => {}, stderr: () => {}, createPgPool: async () => pool });
  assert.notEqual(exitCode, 5, 'guard成功后不应报DATABASE_TARGET_REJECTED对应的退出码');
  assert.ok(queryCount >= 2, 'guard通过后必须真的走到了业务查询（verifyHistoricalFeatureDataset），证明保护本身没有误伤正常路径');
});
