import test from 'node:test';import assert from 'node:assert/strict';
import { CollectorService } from '../src/collector/service.js';import { MemoryRepository } from '../src/db/memory.js';

const bar=(t)=>[t,'100','101','99','100','10',t+899999,'1000',10,'5','500','0'];
const response=(body,id='00000000-0000-0000-0000-000000000001')=>({body,requestId:id,status:200,headers:{},startedAt:1,receivedAt:2_000_000,roundTripMs:1});
function adapter({failSymbol}={}){return{client:{breaker:{state:'CLOSED'}},serverTime:async()=>response({serverTime:2_000_000}),spotKlines:async(s)=>{if(s===failSymbol)throw Object.assign(new Error('down'),{code:'UPSTREAM'});return response([bar(0),bar(900000)],`00000000-0000-0000-0000-00000000000${s==='ETHUSDT'?1:2}`)},futuresKlines:async()=>response([bar(0)]),fundingRates:async()=>response([]),openInterest:async(s)=>response({symbol:s,openInterest:'1',time:1}),longShortRatio:async()=>response([]),takerFlow:async()=>response([])};}
const config={collectorId:'test',leaseTtlMs:60000,maxClockOffsetMs:100000,timeoutMs:1000};
test('六路现货任务全部独立成功',async()=>{const repo=new MemoryRepository();const c=new CollectorService({adapter:adapter(),repository:repo,config,now:()=>2_000_000,logger:{error(){}}});const r=await c.runCycle();assert.equal(r.results.length,6);assert.equal(r.results.every(x=>x.ok),true);});
test('单个数据源任务失败不拖垮其他采集任务',async()=>{const repo=new MemoryRepository();const c=new CollectorService({adapter:adapter({failSymbol:'BTCUSDT'}),repository:repo,config,now:()=>2_000_000,logger:{error(){}}});const r=await c.runCycle();assert.equal(r.state,'DEGRADED');assert.equal(r.results.filter(x=>x.ok).length,3);});
test('重复采集不重复写正式K线',async()=>{const repo=new MemoryRepository();const c=new CollectorService({adapter:adapter(),repository:repo,config,now:()=>2_000_000,logger:{error(){}}});await c.runCycle();const count=repo.bars.length;await c.runCycle();assert.equal(repo.bars.length,count);});
test('服务器时间不可用时不采集正式事实',async()=>{const repo=new MemoryRepository();const a=adapter();a.serverTime=async()=>{throw new Error('down')};const c=new CollectorService({adapter:a,repository:repo,config,now:()=>2_000_000,logger:{error(){}}});const r=await c.runCycle();assert.equal(r.state,'BLOCKED');assert.equal(repo.bars.length,0);});
test('启动恢复首先获取单实例租约',async()=>{const repo=new MemoryRepository();await repo.acquireLease('primary-collector','other',100000,Date.now());const c=new CollectorService({adapter:adapter(),repository:repo,config,now:()=>2_000_000,logger:{error(){}}});await assert.rejects(c.start(),/COLLECTOR_LEASE_HELD/);});
test('页面生命周期不存在于服务采集器依赖中',async()=>{const source=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../src/collector/service.js',import.meta.url),'utf8'));assert.doesNotMatch(source,/window\.|document\.|localStorage/);});
