import test from 'node:test';import assert from 'node:assert/strict';
import { CollectorService } from '../src/collector/service.js';import { MemoryRepository } from '../src/db/memory.js';

const NOW=1_784_000_000_000, OPEN=NOW-1_800_000;
const bar=(t)=>[t,'100','101','99','100','10',t+899999,'1000',10,'5','500','0'];
const response=(body,id='00000000-0000-0000-0000-000000000001')=>({body,requestId:id,status:200,headers:{},startedAt:NOW-2,receivedAt:NOW,roundTripMs:2});
function adapter({failSymbol}={}){return{client:{breakerStates:()=>({})},serverTime:async()=>response({serverTime:NOW}),spotKlines:async(s)=>{if(s===failSymbol)throw Object.assign(new Error('down'),{code:'UPSTREAM'});return response([bar(OPEN),bar(OPEN+900000)],`00000000-0000-0000-0000-00000000000${s==='ETHUSDT'?1:2}`)},futuresKlines:async()=>response([bar(OPEN)]),fundingRates:async()=>response([]),openInterest:async(s)=>response({symbol:s,openInterest:'1',time:NOW-1000}),longShortRatio:async()=>response([]),takerFlow:async()=>response([])};}
const config={collectorId:'test',leaseTtlMs:60000,maxClockOffsetMs:100000,timeoutMs:1000};
async function active(repo,a=adapter()){const c=new CollectorService({adapter:a,repository:repo,config,now:()=>NOW,logger:{error(){}}});c.lease=await repo.acquireLease('primary-collector','test',60000,NOW);c.running=true;c.startedAt=NOW;return c;}
test('六路现货任务全部独立成功',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const c=await active(repo);const r=await c.runCycle();assert.equal(r.results.length,6);assert.equal(r.results.every(x=>x.ok),true);});
test('单个数据源任务失败不拖垮其他采集任务',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const c=await active(repo,adapter({failSymbol:'BTCUSDT'}));const r=await c.runCycle();assert.equal(r.state,'DEGRADED');assert.equal(r.results.filter(x=>x.ok).length,3);});
test('重复采集不重复写正式K线',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const c=await active(repo);await c.runCycle();const count=repo.bars.length;await c.runCycle();assert.equal(repo.bars.length,count);});
test('服务器时间不可用时不采集正式事实',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const a=adapter();a.serverTime=async()=>{throw new Error('down')};const c=await active(repo,a);const r=await c.runCycle();assert.equal(r.state,'BLOCKED');assert.equal(repo.bars.length,0);});
test('启动恢复首先获取单实例租约',async()=>{const repo=new MemoryRepository({now:()=>NOW});await repo.acquireLease('primary-collector','other',100000,NOW);const c=new CollectorService({adapter:adapter(),repository:repo,config,now:()=>NOW,logger:{error(){}}});await assert.rejects(c.start(),error=>error.code==='COLLECTOR_LEASE_HELD');});
test('心跳失败立即停止所有调度并阻止后续写入',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const c=await active(repo);c.schedule(()=>Promise.resolve(),100000);repo.heartbeatLease=async()=>null;await assert.rejects(c.heartbeat(),error=>error.code==='LEASE_LOST');assert.equal(c.running,false);assert.equal(c.timers.length,0);assert.throws(()=>c.requireLease(),/active lease holder/);});
test('raw序列化失败记录脱敏审计且不继续生成事实',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const c=await active(repo);await assert.rejects(c.collectBarsFromResponse({response:response(undefined),sourceId:'binance-spot-rest',instrument:'ETHUSDT',marketType:'spot',interval:'15m',serverTime:NOW}));assert.equal(repo.raw.length,0);assert.equal(repo.bars.length,0);assert.equal(repo.audits[0].eventType,'RAW_PAYLOAD_REJECTED');assert.deepEqual(Object.keys(repo.audits[0].detail),['errorCode']);});
test('graceful shutdown取消新任务并等待在途任务完成',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const c=await active(repo);let resolved=false;const pending=Promise.resolve().then(()=>{resolved=true;});c.inflight.add(pending);await c.stop({closeRepository:false});assert.equal(resolved,true);assert.equal(c.running,false);assert.equal(c.abortController.signal.aborted,true);});
test('衍生品周期接入独立collection_run且attempt关联正确runId',async()=>{const repo=new MemoryRepository({requireLease:true,now:()=>NOW});const c=await active(repo);const result=await c.collectDerivatives();assert.equal(result.length,14);assert.equal(repo.runs.length,1);assert.equal(repo.runs[0].status,'SUCCEEDED');assert.ok(repo.attempts.length>=14);assert.equal(repo.attempts.every(x=>x.runId===repo.runs[0].runId),true);});
test('页面生命周期不存在于服务采集器依赖中',async()=>{const source=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../src/collector/service.js',import.meta.url),'utf8'));assert.doesNotMatch(source,/window\.|document\.|localStorage/);});
