import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { detectGaps, normalizeKlines, validateKlineRow } from '../src/domain/normalize.js';
import { assertNoFutureLeak, buildRevisionEvent, buildVintageRef } from '../src/domain/vintage.js';
import { evaluateHealth } from '../src/health/evaluator.js';
import { MemoryRepository } from '../src/db/memory.js';
import { canonicalJsonHash, canonicalJsonStringify, sha256 } from '../src/domain/hash.js';

const bar=(openTime,{open='100.0',high='102.0',low='99.0',close='101.0',volume='10.0',closeTime=openTime+899999}={})=>[openTime,open,high,low,close,volume,closeTime,'1000.0',10,'5.0','500.0','0'];
const context={sourceId:'binance-spot-rest',endpointId:'binance-spot-klines',instrument:'ETHUSDT',marketType:'spot',interval:'15m',fetchedAt:2_000_000,rawPayloadId:'raw-1',requestId:'00000000-0000-0000-0000-000000000001'};

test('合法K线通过OHLC校验',()=>assert.deepEqual(validateKlineRow(bar(0),'15m'),[]));
test('非法OHLC被拒绝',()=>assert.ok(validateKlineRow(bar(0,{high:'98'}),'15m').includes('OHLC_RELATION_INVALID')));
test('负成交量被拒绝',()=>assert.ok(validateKlineRow(bar(0,{volume:'-1'}),'15m').includes('VOLUME_INVALID')));
test('时间错位被拒绝',()=>assert.ok(validateKlineRow(bar(0,{closeTime:10}),'15m').includes('TIME_MISALIGNED')));
test('只将服务器时间前已收盘K线写入正式集合',()=>{const x=normalizeKlines({rows:[bar(0),bar(900000)],serverTime:1_000_000,...context});assert.equal(x.formal.length,1);assert.equal(x.provisional.length,1);});
test('未收盘K线不进入正式集合',()=>{const x=normalizeKlines({rows:[bar(0)],serverTime:899998,...context});assert.equal(x.formal.length,0);assert.equal(x.provisional.length,1);});
test('重复时间被结构校验拒绝',()=>{const x=normalizeKlines({rows:[bar(0),bar(0)],serverTime:2_000_000,...context});assert.equal(x.rejected[0].errors.includes('DUPLICATE_TIME'),true);});
test('非递增时间被拒绝',()=>{const x=normalizeKlines({rows:[bar(900000),bar(0)],serverTime:2_000_000,...context});assert.equal(x.rejected[0].errors.includes('NON_INCREASING_TIME'),true);});
test('缺口检测准确计算缺失根数',()=>assert.deepEqual(detectGaps([{openTime:0},{openTime:2_700_000}],'15m')[0].missingCount,2));
test('连续K线没有缺口',()=>assert.equal(detectGaps([{openTime:0},{openTime:900000}],'15m').length,0));
test('DataVintageRef时间契约完整',()=>{const v=buildVintageRef({sourceId:'s',sourceRef:'e',fieldId:'f',instrument:'ETHUSDT',interval:'15m',observationStart:0,observationEnd:10,publishedAt:10,availableAt:10,firstAvailableAt:11,fetchedAt:12,value:{x:'1'}});assert.equal(v.revisionNumber,0);assert.match(v.vintageId,/rev0$/);});
test('DataVintageRef拒绝时间逆序',()=>assert.throws(()=>buildVintageRef({sourceId:'s',sourceRef:'e',fieldId:'f',instrument:'ETH',interval:'15m',observationStart:0,observationEnd:10,publishedAt:10,availableAt:9,firstAvailableAt:11,fetchedAt:12,value:1}),/INVALID_VINTAGE/));
test('未来数据泄漏红线阻断',()=>assert.throws(()=>assertNoFutureLeak({availableAt:101},100),/FUTURE_DATA_LEAK/));
test('as-of边界相等允许使用',()=>assert.equal(assertNoFutureLeak({availableAt:100},100),true));
test('修订事件必须追加连续版本',()=>{const a={fieldId:'f',vintageId:'a',revisionNumber:0,observationPeriod:{start:0,end:1},contentHash:'a'};const b={...a,vintageId:'b',revisionNumber:1,contentHash:'b'};assert.equal(buildRevisionEvent(a,b,2).previousVintageId,'a');});
test('修订链跳号被拒绝',()=>assert.throws(()=>buildRevisionEvent({vintageId:'a',revisionNumber:0},{vintageId:'b',revisionNumber:2},2),/INVALID_REVISION/));
test('标准化价格保持交易所原始十进制字符串',()=>{const x=normalizeKlines({rows:[bar(0,{open:'1845.12345678',high:'1846.0',low:'1844.0',close:'1845.5'})],serverTime:1_000_000,...context});assert.equal(x.formal[0].open,'1845.12345678');});
test('标准化内容哈希确定',()=>{const input={rows:[bar(0)],serverTime:1_000_000,...context};assert.equal(normalizeKlines(input).formal[0].contentHash,normalizeKlines(input).formal[0].contentHash);});
test('内存仓库事实写入幂等',async()=>{const repo=new MemoryRepository();const row=normalizeKlines({rows:[bar(0)],serverTime:1_000_000,...context}).formal[0];assert.equal((await repo.upsertMarketBars([row])).inserted,1);assert.equal((await repo.upsertMarketBars([row])).deduped,1);});
test('同自然键不同内容追加新revision且不覆盖原事实',async()=>{const repo=new MemoryRepository();const row=normalizeKlines({rows:[bar(0)],serverTime:1_000_000,...context}).formal[0];await repo.upsertMarketBars([row]);const result=await repo.upsertMarketBars([{...row,contentHash:'different'}]);assert.equal(result.revised,1);assert.equal(repo.bars.length,2);assert.equal(repo.bars[0].revisionNumber,0);assert.equal(repo.bars[1].revisionNumber,1);assert.equal(repo.revisions.length,1);});
test('原始响应相同请求与哈希去重',async()=>{const repo=new MemoryRepository();const response={requestId:'r',body:{a:1}};const meta={contentHash:sha256(response.body)};assert.equal(await repo.saveRaw(response,meta),await repo.saveRaw(response,meta));assert.equal(repo.raw.length,1);});
test('原始响应对象被冻结且不被覆盖',async()=>{const repo=new MemoryRepository();const body={a:1};await repo.saveRaw({requestId:'r',body},{contentHash:sha256(body)});assert.equal(Object.isFrozen(repo.raw[0]),true);});
test('JSONB规范化支持数组与JSON原语且对象键顺序不改变哈希',()=>{for(const value of [null,true,false,12.5,'中文',[1,{b:2,a:1}],{b:2,a:1}])assert.doesNotThrow(()=>canonicalJsonStringify(value));assert.equal(sha256(JSON.parse(canonicalJsonStringify({b:2,a:1}))),sha256({a:1,b:2}));});
test('JSONB规范化拒绝undefined、BigInt、循环与非有限数',()=>{const cycle={};cycle.self=cycle;for(const value of [undefined,1n,Infinity,cycle])assert.throws(()=>canonicalJsonStringify(value),/JSON|Circular|serializable|finite/i);});
test('原始响应序列化失败不形成半成品raw',async()=>{const repo=new MemoryRepository();await assert.rejects(repo.saveRaw({requestId:'bad',body:undefined},{contentHash:'x'}));assert.equal(repo.raw.length,0);});
test('字符串根节点的冻结哈希与JSONB序列化一致',async()=>{const repo=new MemoryRepository();const body='plain text';await repo.saveRaw({requestId:'string',body},{contentHash:canonicalJsonHash(body)});assert.equal(repo.raw[0].payload,body);});
test('回补任务按缺口幂等',async()=>{const repo=new MemoryRepository();const gap={key:'g'};await repo.createBackfill(gap);await repo.createBackfill(gap);assert.equal(repo.backfills.length,1);});
test('单实例租约拒绝第二持有者',async()=>{const repo=new MemoryRepository();assert.ok(await repo.acquireLease('p','a',1000,0));assert.equal(await repo.acquireLease('p','b',1000,1),null);});
test('租约过期后允许接管并增加fencing token',async()=>{const repo=new MemoryRepository();const a=await repo.acquireLease('p','a',10,0);const b=await repo.acquireLease('p','b',10,11);assert.equal(b.fencingToken,a.fencingToken+1);});
test('服务器时间不可用进入BLOCKED',()=>assert.equal(evaluateHealth({serverTimeAvailable:false,maxClockOffsetMs:5000}).state,'BLOCKED'));
test('时钟偏差超限进入BLOCKED',()=>assert.equal(evaluateHealth({serverTimeAvailable:true,clockOffsetMs:5001,maxClockOffsetMs:5000}).state,'BLOCKED'));
test('没有任何成功数据不得显示HEALTHY',()=>assert.equal(evaluateHealth({serverTimeAvailable:true,clockOffsetMs:0,maxClockOffsetMs:5000}).state,'DEGRADED'));
test('单个缺口产生WARNING而非伪健康',()=>assert.equal(evaluateHealth({serverTimeAvailable:true,clockOffsetMs:0,maxClockOffsetMs:5000,latestSuccessAt:1,unresolvedGapCount:1}).state,'WARNING'));
test('连续失败产生DEGRADED',()=>assert.equal(evaluateHealth({serverTimeAvailable:true,clockOffsetMs:0,maxClockOffsetMs:5000,latestSuccessAt:1,consecutiveFailures:5}).state,'DEGRADED'));
test('数据库断开和写入失败均不得HEALTHY',()=>{assert.equal(evaluateHealth({databaseAvailable:false,serverTimeAvailable:true,latestSuccessAt:1}).state,'BLOCKED');assert.equal(evaluateHealth({databaseWriteHealthy:false,serverTimeAvailable:true,latestSuccessAt:1}).state,'BLOCKED');});
test('DDL包含全部17个最低要求表及关键约束',async()=>{const sql=await readFile(new URL('../migrations/001_v1_4a_foundation.up.sql',import.meta.url),'utf8');for(const name of ['schema_migrations','source_registry','source_endpoint_registry','collection_runs','collection_attempts','raw_payloads','market_bars','funding_rates','open_interest','long_short_ratios','taker_flow','data_gaps','backfill_jobs','data_health_snapshots','source_audit_events','collector_leases','dead_letter_records'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${name}`));assert.match(sql,/UNIQUE\(source_id, market_type, instrument, interval_name, open_time, revision_number\)/);assert.match(sql,/published_at<=available_at/);});
test('DDL的原始层没有UPDATE覆盖路径',async()=>{const sql=await readFile(new URL('../migrations/001_v1_4a_foundation.up.sql',import.meta.url),'utf8');assert.doesNotMatch(sql,/UPDATE\s+raw_payloads/i);});
