import test from 'node:test';import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';
import { normalizeFunding, normalizeKlines, normalizeLongShort, normalizeOpenInterest, normalizeTakerFlow } from '../src/domain/normalize.js';
import { MemoryRepository } from '../src/db/memory.js';import { MacroSourceAdapter } from '../src/sources/macro-placeholder.js';import { BackfillWorker } from '../src/collector/backfill.js';import { evaluateHealth } from '../src/health/evaluator.js';

const context={sourceId:'binance-usdt-futures-rest',endpointId:'e',instrument:'ETHUSDT',marketType:'usdt_perpetual',interval:'15m',fetchedAt:2000,rawPayloadId:'raw',requestId:'req',qualityState:'NORMAL'};
test('负资金费率是合法精确字符串',()=>assert.equal(normalizeFunding({symbol:'ETHUSDT',fundingTime:1000,fundingRate:'-0.00001262',markPrice:'1800.1'},context).fundingRate,'-0.00001262'));
test('Open Interest保持精确字符串',()=>assert.equal(normalizeOpenInterest({symbol:'ETHUSDT',time:1000,openInterest:'2316902.932'},context).openInterest,'2316902.932'));
test('官方全市场多空比字段完整映射',()=>assert.equal(normalizeLongShort({symbol:'ETHUSDT',timestamp:1000,longShortRatio:'2.2',longAccount:'0.68',shortAccount:'0.32'},context).shortAccount,'0.32'));
test('官方主动买卖量字段完整映射',()=>assert.equal(normalizeTakerFlow({timestamp:1000,buySellRatio:'1.2',buyVol:'12.3',sellVol:'10.2'},context).buyVolume,'12.3'));
test('点状事实相同vintage幂等',async()=>{const repo=new MemoryRepository();const x=normalizeOpenInterest({symbol:'ETHUSDT',time:1000,openInterest:'1'},context);await repo.savePointFacts('open_interest',[x]);assert.equal((await repo.savePointFacts('open_interest',[x])).deduped,1);});
test('点状事实同vintage不同内容拒绝覆盖',async()=>{const repo=new MemoryRepository();const x=normalizeOpenInterest({symbol:'ETHUSDT',time:1000,openInterest:'1'},context);await repo.savePointFacts('open_interest',[x]);await assert.rejects(repo.savePointFacts('open_interest',[{...x,openInterest:'2'}]),/IMMUTABLE/);});
test('未收盘记录没有正式vintage与availableAt',()=>{const row=[0,'1','1','1','1','1',899999,'1',1,'1','1','0'];const x=normalizeKlines({rows:[row],sourceId:'s',endpointId:'e',instrument:'ETHUSDT',marketType:'spot',interval:'15m',serverTime:100,fetchedAt:200,rawPayloadId:'r',requestId:'q'}).provisional[0];assert.equal(x.vintageId,null);assert.equal(x.availableAt,null);});
test('宏观适配器明确UNAVAILABLE而不伪造数据',async()=>assert.deepEqual(await new MacroSourceAdapter().collect(),{ok:false,status:'UNAVAILABLE',reason:'NO_FROZEN_OFFICIAL_KEYLESS_SOURCE'}));
test('回补使用原缺口边界并在完整后标记解决',async()=>{const calls=[];const repo=new MemoryRepository();repo.gaps.push({key:'g',status:'OPEN'});const worker=new BackfillWorker({adapter:{spotKlines:async(s,i,o)=>{calls.push({s,i,o});return{requestId:'r'}}},repository:repo,collector:{collectBarsFromResponse:async()=>({ok:true,gaps:0})}});await worker.execute({gap:{gapId:'g',sourceId:'s',instrument:'ETHUSDT',marketType:'spot',interval:'15m',startOpenTime:10,endOpenTime:20}},100);assert.deepEqual(calls[0].o,{startTime:10,endTime:20,limit:1000});assert.equal(repo.gaps[0].status,'RESOLVED');});
test('恢复阶段健康状态明确为RECOVERING',()=>assert.equal(evaluateHealth({serverTimeAvailable:true,clockOffsetMs:0,maxClockOffsetMs:5000,unresolvedGapCount:1,recovering:true}).state,'RECOVERING'));
test('market_bars索引支持96与288根时间顺序路径查询',async()=>{const sql=await readFile(new URL('../migrations/001_v1_4a_foundation.up.sql',import.meta.url),'utf8');assert.match(sql,/market_bars_path_idx ON market_bars\(instrument, market_type, interval_name, open_time\)/);});
test('DDL含追加式DataRevisionEvent且不更新旧vintage',async()=>{const sql=await readFile(new URL('../migrations/001_v1_4a_foundation.up.sql',import.meta.url),'utf8');assert.match(sql,/CREATE TABLE IF NOT EXISTS data_revision_events/);assert.match(sql,/previous_vintage_id/);assert.match(sql,/new_vintage_id/);});
test('endpoint registry使用已核实的公开接口路径',async()=>{const sql=await readFile(new URL('../migrations/001_v1_4a_foundation.up.sql',import.meta.url),'utf8');for(const path of ['/api/v3/time','/api/v3/klines','/fapi/v1/klines','/fapi/v1/fundingRate','/fapi/v1/openInterest','/futures/data/globalLongShortAccountRatio','/futures/data/takerlongshortRatio'])assert.ok(sql.includes(path));});
